// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/oci8/tests/define3.phpt
  it("Test oci_define_by_name() LOB descriptor", function () {
    expect(parser.parseCode("<?php\nrequire(__DIR__.\"/connect.inc\");\n$stmtarray = array(\n    \"drop table phpdefblobtable\",\n    \"create table phpdefblobtable (id number(10), fileimage blob)\"\n);\noci8_test_sql_execute($c, $stmtarray);\n// Load data\n$stmt = oci_parse ($c, \"insert into phpdefblobtable (id, fileimage) values (:id, empty_blob()) returning fileimage into :fileimage\");\n$fileimage = oci_new_descriptor($c,OCI_D_LOB);\noci_bind_by_name($stmt,\":id\",$id);\noci_bind_by_name($stmt,\":fileimage\",$fileimage,-1,OCI_B_BLOB);\n$id = 1;\noci_execute($stmt, OCI_DEFAULT);\n$fileimage->saveFile(__DIR__.\"/test.gif\");\n$data = $fileimage->load();\nvar_dump(md5($data));  // original md5\noci_commit($c);\n// New row with different data\n$id = 2;\n$data = strrev($data);\nvar_dump(md5($data));\noci_execute($stmt, OCI_DEFAULT);\n$fileimage->save($data);\noci_commit($c);\necho \"Test 1\\n\";\n$stmt = oci_parse($c, \"SELECT fileimage FROM phpdefblobtable\");\nvar_dump(oci_define_by_name($stmt, 'FILEIMAGE', $f));\noci_execute($stmt);\nwhile (oci_fetch($stmt)) {\n   var_dump($f);\n   echo \"file md5:\" . md5($f->load()) . \"\\n\";\n}\necho \"Test 2\\n\";\n$stmt = oci_parse($c, \"SELECT fileimage FROM phpdefblobtable\");\nvar_dump(oci_define_by_name($stmt, 'FILEIMAGE', $outdata, SQLT_STR));\noci_execute($stmt);\nwhile (oci_fetch($stmt)) {\n   echo \"file md5:\" . md5($outdata) . \"\\n\";\n}\necho \"Test 3\\n\";\n$stmt = oci_parse($c, \"SELECT fileimage FROM phpdefblobtable\");\nvar_dump(oci_define_by_name($stmt, 'FILEIMAGE', $outdata, SQLT_BIN));\noci_execute($stmt);\nwhile (oci_fetch($stmt)) {\n   echo \"file md5:\" . md5($outdata) . \"\\n\";\n}\necho \"Test 4\\n\";\n$fid = oci_new_descriptor($c,OCI_D_LOB);\n$stmt = oci_parse($c, \"SELECT fileimage FROM phpdefblobtable\");\nvar_dump(oci_define_by_name($stmt, 'FILEIMAGE', $fid));\noci_execute($stmt);\nwhile (oci_fetch($stmt)) {\n   echo \"file md5:\" . md5($fid->load()) . \"\\n\";\n}\n$stmtarray = array(\n    \"drop table phpdefblobtable\"\n);\noci8_test_sql_execute($c, $stmtarray);\necho \"Done\\n\";\n?>")).toMatchSnapshot();
  });
});
