// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/oci8/tests/xmltype_02.phpt
  it("Basic XMLType test #2", function () {
    expect(parser.parseCode("<?php\nrequire(__DIR__.'/connect.inc');\n// Initialization\n$stmtarray = array(\n    \"drop table xmltype_02_tab\",\n    \"create table xmltype_02_tab (warehouse_id number, warehouse_spec xmltype)\",\n);\noci8_test_sql_execute($c, $stmtarray);\n// Run Test\n$id = 1;\n// Delete any current entry\n$s = oci_parse($c, \"delete from xmltype_02_tab where warehouse_id = :id\");\noci_bind_by_name($s, ':id', $id);\noci_execute($s);\n// XML data to be inserted\n$xml =<<<EOF\n<?xml version=\"1.0\"?>\n<Warehouse>\n<WarehouseId>1</WarehouseId>\n<WarehouseName>Southlake, Texas</WarehouseName>\n<Building>Owned</Building>\n<Area>25000</Area>\n<Docks>2</Docks>\n<DockType>Rear load</DockType>\n<WaterAccess>true</WaterAccess>\n<RailAccess>N</RailAccess>\n<Parking>Street</Parking>\n<VClearance>10</VClearance>\n</Warehouse>\nEOF;\necho \"Test 1 Insert new XML data using a temporary CLOB\\n\";\n$s = oci_parse($c,\n    \"insert into xmltype_02_tab (warehouse_id, warehouse_spec)\n     values (:id, XMLType(:clob))\");\noci_bind_by_name($s, ':id', $id);\n$lob = oci_new_descriptor($c, OCI_D_LOB);\noci_bind_by_name($s, ':clob', $lob, -1, OCI_B_CLOB);\n$lob->writeTemporary($xml);\noci_execute($s);\n$lob->close();\n// Query the row back\n$s = oci_parse($c, 'select xmltype.getclobval(warehouse_spec)\n                    from xmltype_02_tab where warehouse_id = :id');\n$r = oci_bind_by_name($s, ':id', $id);\noci_execute($s);\n$row = oci_fetch_array($s, OCI_NUM);\nvar_dump($row);\necho \"Test 2 Manipulate the data using SimpleXML\\n\";\n$sx = simplexml_load_string($row[0]->load());\n$row[0]->free();\nvar_dump($sx);\n$sx->Docks -= 1;  // change the data\nvar_dump($sx);\necho \"Test 3: Update changes using a temporary CLOB\\n\";\n$s = oci_parse($c, 'update xmltype_02_tab\n                    set warehouse_spec = XMLType(:clob)\n                    where warehouse_id = :id');\noci_bind_by_name($s, ':id', $id);\n$lob = oci_new_descriptor($c, OCI_D_LOB);\noci_bind_by_name($s, ':clob', $lob, -1, OCI_B_CLOB);\n$lob->writeTemporary($sx->asXml());\noci_execute($s);\n$lob->close();\n// Query the changed row back and print it\n$s = oci_parse($c, 'select xmltype.getclobval(warehouse_spec)\n                    from xmltype_02_tab where warehouse_id = :id');\n$r = oci_bind_by_name($s, ':id', $id);\noci_execute($s);\n$row = oci_fetch_array($s, OCI_NUM);\nvar_dump($row[0]->load());\n$row[0]->free();\n// Clean up\n$stmtarray = array(\n    \"drop table xmltype_02_tab\"\n);\noci8_test_sql_execute($c, $stmtarray);\n?>")).toMatchSnapshot();
  });
});
