// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/mysqli/tests/001.phpt
  it("mysqli connect", function () {
    expect(parser.parseCode("<?php\n    require_once(\"connect.inc\");\n    $test = \"\";\n    /*** test mysqli_connect localhost:port ***/\n    $link = my_mysqli_connect($host, $user, $passwd, \"\", $port, $socket);\n    $test .= ($link) ? \"1\" : \"0\";\n    mysqli_close($link);\n    /*** test mysqli_real_connect ***/\n    $link = mysqli_init();\n    $test.= (my_mysqli_real_connect($link, $host, $user, $passwd, \"\", $port, $socket) )\n        ? \"1\" : \"0\";\n    mysqli_close($link);\n    /*** test mysqli_real_connect with db ***/\n    $link = mysqli_init();\n    $test .= (my_mysqli_real_connect($link, $host, $user, $passwd, $db, $port, $socket))\n        ? \"1\" : \"0\";\n    mysqli_close($link);\n    /*** test mysqli_real_connect with port ***/\n    $link = mysqli_init();\n    $test .= (my_mysqli_real_connect($link, $host, $user, $passwd, $db, $port, $socket))\n        ? \"1\":\"0\";\n    mysqli_close($link);\n    /* temporary addition for Kent's setup, Win32 box */\n    for ($i = 0; $i < 10; $i++) {\n        if (!$link = mysqli_init())\n            printf(\"[001 + %d] mysqli_init() failed, [%d] %s\\n\", $i, mysqli_connect_errno(), mysqli_connect_error());\n        if (!my_mysqli_real_connect($link, $host, $user, $passwd, $db, $port, $socket))\n            printf(\"[002 + %d] mysqli_real_connect() failed, [%d] %s\\n\", $i, mysqli_connect_errno(), mysqli_connect_error());\n        mysqli_close($link);\n    }\n    /*** test mysqli_real_connect compressed ***/\n    /*\n    $link = mysqli_init();\n    $test .= (my_mysqli_real_connect($link, $host, $user, $passwd, $db, $port, $socket, MYSQLI_CLIENT_COMPRESS))\n        ? \"1\" : \"0\";\n    mysqli_close($link);\n  */\n    /* todo ssl connections */\n    var_dump($test);\n    print \"done!\";\n?>")).toMatchSnapshot();
  });
});
