// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/standard/tests/array/array_column_variant_objects.phpt
  it("Test array_column() function: testing with objects", function () {
    expect(parser.parseCode("<?php\nclass User\n{\n    public $id, $first_name, $last_name;\n    public function __construct($id, $first_name, $last_name)\n    {\n        $this->id = $id;\n        $this->first_name = $first_name;\n        $this->last_name = $last_name;\n    }\n}\nfunction newUser($id, $first_name, $last_name)\n{\n    $o = new stdClass;\n    $o->{0} = $id;\n    $o->{1} = $first_name;\n    $o->{2} = $last_name;\n    return $o;\n}\nclass Something\n{\n    public function __isset($name)\n    {\n        return $name == 'first_name';\n    }\n    public function __get($name)\n    {\n        return new User(4, 'Jack', 'Sparrow');\n    }\n}\n$records = array(\n    newUser(1, 'John', 'Doe'),\n    newUser(2, 'Sally', 'Smith'),\n    newUser(3, 'Jane', 'Jones'),\n    new User(1, 'John', 'Doe'),\n    new User(2, 'Sally', 'Smith'),\n    new User(3, 'Jane', 'Jones'),\n    new Something,\n);\necho \"*** Testing array_column() : object property fetching (numeric property names) ***\\n\";\necho \"-- first_name column from recordset --\\n\";\nvar_dump(array_column($records, 1));\necho \"-- id column from recordset --\\n\";\nvar_dump(array_column($records, 0));\necho \"-- last_name column from recordset, keyed by value from id column --\\n\";\nvar_dump(array_column($records, 2, 0));\necho \"-- last_name column from recordset, keyed by value from first_name column --\\n\";\nvar_dump(array_column($records, 2, 1));\necho \"*** Testing array_column() : object property fetching (string property names) ***\\n\";\necho \"-- first_name column from recordset --\\n\";\nvar_dump(array_column($records, 'first_name'));\necho \"-- id column from recordset --\\n\";\nvar_dump(array_column($records, 'id'));\necho \"-- last_name column from recordset, keyed by value from id column --\\n\";\nvar_dump(array_column($records, 'last_name', 'id'));\necho \"-- last_name column from recordset, keyed by value from first_name column --\\n\";\nvar_dump(array_column($records, 'last_name', 'first_name'));\necho \"Done\\n\";\n?>")).toMatchSnapshot();
  });
});
