// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/standard/tests/strings/sprintf_variation1.phpt
  it("Test sprintf() function : usage variations - unexpected values for format argument", function () {
    expect(parser.parseCode("<?php\n/*\n* Testing sprintf() : with different unexpected values for format argument other than the strings\n*/\necho \"*** Testing sprintf() : with unexpected values for format argument ***\\n\";\n// initialing required variables\n$arg1 = \"second arg\";\n$arg2 = \"third arg\";\n// declaring class\nclass sample\n{\n  public function __toString() {\n    return \"Object\";\n  }\n}\n// creating a file resource\n$file_handle = fopen(__FILE__, 'r');\n//array of values to iterate over\n$values = array(\n      // int data\n      0,\n      1,\n      12345,\n      -2345,\n      // float data\n      10.5,\n      -10.5,\n      10.1234567e10,\n      10.7654321E-10,\n      .5,\n      // array data\n      array(),\n      array(0),\n      array(1),\n      array(1, 2),\n      array('color' => 'red', 'item' => 'pen'),\n      // boolean data\n      true,\n      false,\n      TRUE,\n      FALSE,\n      // empty data\n      \"\",\n      '',\n      // object data\n      new sample(),\n      // resource data\n      $file_handle\n);\n// loop through each element of the array for format\n$count = 1;\nforeach($values as $value) {\n  echo \"\\n-- Iteration $count --\\n\";\n  // with default argument\n  try {\n    var_dump(sprintf($value));\n  } catch (TypeError $exception) {\n    echo $exception->getMessage() . \"\\n\";\n  }\n  // with two arguments\n  try {\n    var_dump(sprintf($value, $arg1));\n  } catch (TypeError $exception) {\n    echo $exception->getMessage() . \"\\n\";\n  }\n  // with three arguments\n  try {\n    var_dump(sprintf($value, $arg1, $arg2));\n  } catch (TypeError $exception) {\n    echo $exception->getMessage() . \"\\n\";\n  }\n  $count++;\n}\n// close the resource\nfclose($file_handle);\necho \"Done\";\n?>")).toMatchSnapshot();
  });
});
