// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/openssl/tests/openssl_cms_sign_verify_detached.phpt
  it("openssl_cms_sign() and verify detached tests", function () {
    expect(parser.parseCode("<?php\n$infile = __DIR__ . \"/plain.txt\";\n$outfile = tempnam(sys_get_temp_dir(), \"ssl\");\n$vout= $outfile . \".vout\";\nif ($outfile === false) {\n    die(\"failed to get a temporary filename!\");\n}\n$privkey = \"file://\" . __DIR__ . \"/private_rsa_1024.key\";\n$single_cert = \"file://\" . __DIR__ . \"/cert.crt\";\n$assoc_headers = array(\"To\" => \"test@test\", \"Subject\" => \"testing openssl_cms_sign()\");\n$headers = array(\"test@test\", \"testing openssl_cms_sign()\");\n$empty_headers = array();\n$wrong = \"wrong\";\n$empty = \"\";\nprint(\"S/MIME attached\\nPlain text:\\n\");\nreadfile($infile);\nvar_dump(openssl_cms_sign($infile, $outfile, openssl_x509_read($single_cert), $privkey, $headers));\nvar_dump(openssl_cms_verify($outfile,OPENSSL_CMS_NOVERIFY, NULL, array(), NULL, $vout));\nprint(\"\\nValidated content:\\n\");\nreadfile($vout);\nif (file_exists($outfile)) {\n    echo \"true\\n\";\n    unlink($outfile);\n}\nif (file_exists($vout)) {\n    echo \"true\\n\";\n    unlink($vout);\n}\n// test three forms of detached signatures:\n// PEM first\nprint(\"\\nPEM Detached:\\n\");\nvar_dump(openssl_cms_sign($infile, $outfile, openssl_x509_read($single_cert), $privkey, $headers,\n\t     OPENSSL_CMS_DETACHED|OPENSSL_CMS_BINARY,OPENSSL_ENCODING_PEM));\nvar_dump(openssl_cms_verify($infile,OPENSSL_CMS_NOVERIFY|OPENSSL_CMS_DETACHED|OPENSSL_CMS_BINARY,\n         NULL, array(), NULL, $vout, NULL, $outfile, OPENSSL_ENCODING_PEM));\nprint(\"\\nValidated content:\\n\");\nreadfile($vout);\nif (file_exists($outfile)) {\n    echo \"true\\n\";\n    unlink($outfile);\n}\nif (file_exists($vout)) {\n    echo \"true\\n\";\n    unlink($vout);\n}\n// DER next\nprint(\"\\nDER Detached:\\n\");\nvar_dump(openssl_cms_sign($infile, $outfile, openssl_x509_read($single_cert), $privkey, $headers,\n\t     OPENSSL_CMS_DETACHED|OPENSSL_CMS_BINARY,OPENSSL_ENCODING_DER));\nvar_dump(openssl_cms_verify($infile,OPENSSL_CMS_NOVERIFY|OPENSSL_CMS_DETACHED|OPENSSL_CMS_BINARY,\n         NULL, array(), NULL, $vout, NULL, $outfile, OPENSSL_ENCODING_DER));\nprint(\"\\nValidated content:\\n\");\nreadfile($vout);\n// extreme measures to avoid stupid temporary errors for failure to unlink a file.\nif (file_exists($outfile)) {\n    echo \"true\\n\";\n    unlink($outfile);\n}\n$outfile=$outfile . \"x\";\nif (file_exists($vout)) {\n    echo \"true\\n\";\n    unlink($vout);\n}\n// S/MIME next\nprint(\"\\nS/MIME Detached (an error):\\n\");\nvar_dump(openssl_cms_sign($infile, $outfile, openssl_x509_read($single_cert), $privkey, $headers,\n\t     OPENSSL_CMS_DETACHED,OPENSSL_ENCODING_SMIME));\nvar_dump(openssl_cms_verify($infile,OPENSSL_CMS_NOVERIFY|OPENSSL_CMS_DETACHED,\n         NULL, array(), NULL, $vout, NULL, $outfile, OPENSSL_ENCODING_SMIME));\nif (file_exists($outfile)) {\n    echo \"true\\n\";\n    unlink($outfile);\n}\nif (file_exists($vout)) {\n    echo \"true\\n\";\n    unlink($vout);\n}\n?>")).toMatchSnapshot();
  });
});
