// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/standard/tests/file/fwrite_variation1.phpt
  it("Test fwrite() function : usage variations - r, rb & rt modes", function () {
    expect(parser.parseCode("<?php\necho \"*** Testing fwrite() various  operations ***\\n\";\n// include the file.inc for Function: function delete_file($filename)\ninclude (\"file.inc\");\n/*\n Test fwrite with file opened in mode : r,rb,rt\n File having content of type numeric, text,text_with_new_line & alphanumeric\n*/\n$file_modes = array(\"r\",\"rb\",\"rt\");\n$file_content_types = array(\"numeric\",\"text\",\"text_with_new_line\",\"alphanumeric\");\nforeach($file_content_types as $file_content_type) {\n  echo \"\\n-- Testing fwrite() with file having content of type \". $file_content_type .\" --\\n\";\n  /* open the file using $files_modes and perform fwrite() on it */\n  foreach($file_modes as $file_mode) {\n    echo \"-- Opening file in $file_mode --\\n\";\n    // create the temp file with content of type $file_content_type\n    $filename = __DIR__.\"/fwrite_variation1.tmp\"; // this is name of the file\n    create_files ( __DIR__, 1, $file_content_type, 0755, 1, \"w\", \"fwrite_variation\");\n    $file_handle = fopen($filename, $file_mode);\n    if(!$file_handle) {\n      echo \"Error: failed to fopen() file: $filename!\";\n      exit();\n    }\n    $data_to_be_written=\"\";\n    fill_buffer($data_to_be_written,$file_content_type,1024);  //get the data of size 1024\n    /*  Write the data into the file, verify it by checking the file pointer position, eof position,\n        filesize & by displaying the content */\n    var_dump( ftell($file_handle) );  // expected: 0\n    var_dump( fwrite($file_handle, $data_to_be_written ));\n    var_dump( ftell($file_handle) );  // expected: 0\n    var_dump( feof($file_handle) );  // expected: false\n    // move the file pointer to end of the file and try fwrite()\n    fseek($file_handle, SEEK_END, 0);\n    var_dump( ftell($file_handle) );  // expecting 1024\n    var_dump( fwrite($file_handle, $data_to_be_written) ); // fwrite to fail\n    var_dump( ftell($file_handle) );  //check that file pointer points at eof, expected: 1024\n    var_dump( feof($file_handle) );  // ensure that  feof() points to eof, expected: true\n    // ensure that file content/size didn't change.\n    var_dump( fclose($file_handle) );\n    clearstatcache();//clears file status cache\n    var_dump( filesize($filename) );  // expected: 1024\n    var_dump(md5(file_get_contents($filename))); // hash the output\n    delete_file($filename); // delete file with name fwrite_variation1.tmp\n  } // end of inner foreach loop\n} // end of outer foreach loop\necho \"Done\\n\";\n?>")).toMatchSnapshot();
  });
});
