// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/pdo_mysql/tests/bug_61207.phpt
  it("PDO MySQL Bug #61207 (PDO::nextRowset() after a multi-statement query doesn't always work)", function () {
    expect(parser.parseCode("<?php\nrequire_once(__DIR__ . DIRECTORY_SEPARATOR . 'mysql_pdo_test.inc');\n/** @var PDO $db */\n$db = MySQLPDOTest::factory();\n$db->query('DROP TABLE IF EXISTS test');\n$db->query('create table `test`( `id` int )');\n$handle1 = $db->prepare('insert into test(id) values(1);\n                          select * from test where id = ?;\n                          update test set id = 2 where id = ?;');\n$handle1->bindValue(1, '1');\n$handle1->bindValue(2, '1');\n$handle1->execute();\n$i = 1;\nprint(\"Handle 1:\\n\");\ndo {\n    print('Rowset ' . $i++ . \"\\n\");\n    if ($handle1->columnCount() > 0)\n        print(\"Results detected\\n\");\n} while($handle1->nextRowset());\n$handle2 = $db->prepare('select * from test where id = ?;\n                           update test set id = 1 where id = ?;');\n$handle2->bindValue(1, '2');\n$handle2->bindValue(2, '2');\n$handle2->execute();\n$i = 1;\nprint(\"Handle 2:\\n\");\ndo {\n    print('Rowset ' . $i++ . \"\\n\");\n    if ($handle2->columnCount() > 0)\n        print(\"Results detected\\n\");\n} while($handle2->nextRowset());\n$handle3 = $db->prepare('update test set id = 2 where id = ?;\n                           select * from test where id = ?;');\n$handle3->bindValue(1, '1');\n$handle3->bindValue(2, '2');\n$handle3->execute();\n$i = 1;\nprint(\"Handle 3:\\n\");\ndo {\n    print('Rowset ' . $i++ . \"\\n\");\n    if ($handle3->columnCount() > 0)\n        print(\"Results detected\\n\");\n} while($handle3->nextRowset());\n$handle4 = $db->prepare('insert into test(id) values(3);\n                           update test set id = 2 where id = ?;\n                           select * from test where id = ?;');\n$handle4->bindValue(1, '3');\n$handle4->bindValue(2, '2');\n$handle4->execute();\n$i = 1;\nprint(\"Handle 4:\\n\");\ndo {\n    print('Rowset ' . $i++ . \"\\n\");\n    if ($handle1->columnCount() > 0)\n        print(\"Results detected\\n\");\n} while($handle1->nextRowset());\n$db->query(\"DROP TABLE test\");\n?>")).toMatchSnapshot();
  });
});
