// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/standard/tests/array/array_map_variation5.phpt
  it("Test array_map() function : usage variations - associative array with different values", function () {
    expect(parser.parseCode("<?php\n/*\n * Test array_map() by passing associative array with different values for $arr1 argument\n */\necho \"*** Testing array_map() : associative array with diff. values for 'arr1' argument ***\\n\";\nfunction callback($a)\n{\n  return ($a);\n}\n//get an unset variable\n$unset_var = array(1, 2);\nunset ($unset_var);\n//get a resource variable\n$fp = fopen(__FILE__, \"r\");\n//get a class\nclass classA\n{\n  public function __toString(){\n    return \"Class A object\";\n  }\n}\n// get a heredoc string\n$heredoc = <<<EOT\nHello world\nEOT;\n// initializing the array\n$arrays = array (\n       // empty array\n/*1*/  array(),\n       // arrays with integer values\n       array('0' => 0),\n       array(\"1\" => 1),\n       array(\"one\" => 1, 'two' => 2, \"three\" => 3, 4 => 4),\n       // arrays with float values\n/*5*/  array(\"float\" => 2.3333),\n       array(\"f1\" => 1.2, 'f2' => 3.33, 3 => 4.89999922839999, 'f4' => 33333333.3333),\n       // arrays with string values\n       array(111 => \"\\tHello\", \"red\" => \"col\\tor\", 2 => \"\\v\\fworld\", 3 =>  \"pen\\n\"),\n/*8*/  array(111 => '\\tHello', \"red\" => 'col\\tor', 2 => '\\v\\fworld', 3 =>  'pen\\n'),\n       array(1 => \"hello\", \"heredoc\" => $heredoc),\n       // array with object, unset variable and resource variable\n       array(11 => new classA(), \"unset\" => @$unset_var, \"resource\" => $fp),\n       // array with mixed values\n/*11*/ array(1 => 'hello', 2 => new classA(), 222 => \"fruit\",\n             'resource' => $fp, \"int\" => 133, \"float\" => 444.432,\n             \"unset\" => @$unset_var, \"heredoc\" => $heredoc)\n);\n// loop through the various elements of $arrays to test array_map()\n$iterator = 1;\nforeach($arrays as $arr1) {\n  echo \"-- Iteration $iterator --\\n\";\n  var_dump( array_map('callback', $arr1) );\n  $iterator++;\n}\necho \"Done\";\n?>")).toMatchSnapshot();
  });
});
