// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/sockets/tests/mcast_ipv6_recv_limited.phpt
  it("Multicast support: IPv6 receive options (limited)", function () {
    expect(parser.parseCode("<?php\ninclude __DIR__.\"/mcast_helpers.php.inc\";\n$domain = AF_INET6;\n$level = IPPROTO_IPV6;\n$interface = 0;\n$mcastaddr = 'ff01::114';\n$sblock = \"?\";\necho \"creating send socket\\n\";\n$sends1 = socket_create($domain, SOCK_DGRAM, SOL_UDP) or die(\"err\");\nvar_dump($sends1);\necho \"creating receive socket\\n\";\n$s = socket_create($domain, SOCK_DGRAM, SOL_UDP) or die(\"err\");\nvar_dump($s);\n$br = socket_bind($s, '::0', 3000) or die(\"err\");\nvar_dump($br);\n$so = socket_set_option($s, $level, MCAST_JOIN_GROUP, array(\n    \"group\"\t=> $mcastaddr,\n    \"interface\" => $interface,\n)) or die(\"err\");\nvar_dump($so);\n$r = socket_sendto($sends1, $m = \"testing packet\", strlen($m), 0, $mcastaddr, 3000);\nvar_dump($r);\nchecktimeout($s, 500);\n$r = socket_recvfrom($s, $str, 2000, 0, $from, $fromPort);\nvar_dump($r, $str, $from);\n$sblock = $from;\n$r = socket_sendto($sends1, $m = \"initial packet\", strlen($m), 0, $mcastaddr, 3000);\nvar_dump($r);\n$i = 0;\nchecktimeout($s, 500);\nwhile (($str = socket_read($s, 3000, 500)) !== FALSE) {\n    $i++;\n    echo \"$i> \", $str, \"\\n\";\nif ($i == 1) {\n    echo \"leaving group\\n\";\n    $so = socket_set_option($s, $level, MCAST_LEAVE_GROUP, array(\n        \"group\"\t=> $mcastaddr,\n        \"interface\" => $interface,\n    ));\n    var_dump($so);\n    $r = socket_sendto($sends1, $m = \"ignored mcast packet\", strlen($m), 0, $mcastaddr, 3000);\n    var_dump($r);\n    $r = socket_sendto($sends1, $m = \"unicast packet\", strlen($m), 0, \"::1\", 3000);\n    var_dump($r);\n}\nif ($i == 2) {\n    echo \"re-joining group\\n\";\n    $so = socket_set_option($s, $level, MCAST_JOIN_GROUP, array(\n        \"group\"\t=> $mcastaddr,\n        \"interface\" => $interface,\n    ));\n    var_dump($so);\n    $r = socket_sendto($sends1, $m = \"mcast packet\", strlen($m), 0, $mcastaddr, 3000);\n    var_dump($r);\n}\nif ($i == 3) {\n    break;\n}\n}\n?>")).toMatchSnapshot();
  });
});
