// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/dom/tests/DOMNode_cloneNode_basic.phpt
  it("DOM cloneNode : Basic Functionality", function () {
    expect(parser.parseCode("<?php\n$xml = <<< EOXML\n<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>\n<courses>\n    <course title=\"one\">\n        <notes>\n            <note>c1n1</note>\n            <note>c1n2</note>\n        </notes>\n    </course>\n    <course title=\"two\">\n        <notes>\n            <note>c2n1</note>\n            <note>c2n2</note>\n        </notes>\n    </course>\n</courses>\nEOXML;\nfunction dumpcourse($current) {\n    $title = ($current->nodeType != XML_TEXT_NODE && $current->hasAttribute('title')) ? $current->getAttribute('title'):\"no title\";\n    echo \"Course: $title:\";echo(get_class($current)), \"\\n\";\n    echo \"~\";var_dump($current->textContent);\n}\n$dom = new DOMDocument();\n$dom->loadXML($xml);\n$root = $dom->documentElement;\n// strip all text nodes from this tree\n$children = $root->childNodes;\n$len = $children->length;\nfor ($index = $children->length - 1; $index >=0; $index--) {\n    $current = $children->item($index);\n    if ($current->nodeType == XML_TEXT_NODE) {\n        $noderemoved = $root->removeChild($current);\n    }\n}\necho \"Start cloneNode test\\n\";\n$first_course = $children->item(0);\n$cloned_first_course_default = $first_course->cloneNode();\n$first_course->setAttribute('title', 'new title1');\n$cloned_first_course_true = $first_course->cloneNode(true);\n$first_course->setAttribute('title', 'new title2');\n$cloned_first_course_false = $first_course->cloneNode(false);\n$first_course->setAttribute('title', 'new title3');\n$cloned_first_course_default->setAttribute('title', 'new title default');\n$cloned_first_course_true->setAttribute('title', 'new title true');\n$cloned_first_course_false->setAttribute('title', 'new title false');\n$root->appendChild($cloned_first_course_default);\n$root->appendChild($cloned_first_course_true);\n$root->appendChild($cloned_first_course_false);\n$children = $root->childNodes;\nfor ($index = 0; $index < $children->length; $index++) {\n    echo \"node $index\\n\";\n    dumpcourse($children->item($index));\n}\n?>")).toMatchSnapshot();
  });
});
