// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/oci8/tests/lob_022.phpt
  it("fetching the same lob several times", function () {
    expect(parser.parseCode("<?php\nrequire __DIR__.'/connect.inc';\n$drop = \"DROP table lob_test\";\n$statement = oci_parse($c, $drop);\n@oci_execute($statement);\n$create = \"CREATE table lob_test(mykey NUMBER, lob_1 CLOB)\";\n$statement = oci_parse($c, $create);\noci_execute($statement);\n$init = \"INSERT INTO lob_test (mykey, lob_1) VALUES(1, EMPTY_CLOB()) RETURNING lob_1 INTO :mylob\";\n$statement = oci_parse($c, $init);\n$clob = oci_new_descriptor($c, OCI_D_LOB);\noci_bind_by_name($statement, \":mylob\", $clob, -1, OCI_B_CLOB);\noci_execute($statement, OCI_DEFAULT);\noci_lob_save($clob, \"data\");\nunset($clob->descriptor);\noci_commit($c);\n$init = \"INSERT INTO lob_test (mykey, lob_1) VALUES(2, EMPTY_CLOB()) RETURNING lob_1 INTO :mylob\";\n$statement = oci_parse($c, $init);\n$clob = oci_new_descriptor($c, OCI_D_LOB);\noci_bind_by_name($statement, \":mylob\", $clob, -1, OCI_B_CLOB);\noci_execute($statement, OCI_DEFAULT);\n$clob->save(\"long data\");\n$clob->save(\"long data\", 0);\ntry {\n    $clob->save(\"long data\", -1);\n} catch (ValueError $e) {\n    echo $e->getMessage(), \"\\n\";\n}    \noci_commit($c);\n$query = 'SELECT * FROM lob_test ORDER BY mykey ASC';\n$statement = oci_parse ($c, $query);\noci_execute($statement, OCI_DEFAULT);\nwhile ($row = oci_fetch_array($statement, OCI_ASSOC)) {\n    $result = $row['LOB_1']->load();\n    var_dump($result);\n}\n$query = 'SELECT * FROM lob_test ORDER BY mykey DESC';\n$statement = oci_parse ($c, $query);\noci_execute($statement, OCI_DEFAULT);\nwhile ($row = oci_fetch_array($statement, OCI_ASSOC)) {\n    $result = $row['LOB_1']->load();\n    var_dump($result);\n}\n$drop = \"DROP table lob_test\";\n$statement = oci_parse($c, $drop);\n@oci_execute($statement);\necho \"Done\\n\";\n?>")).toMatchSnapshot();
  });
});
