// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/mysqli/tests/mysqli_stmt_insert_id.phpt
  it("mysqli_stmt_insert_id()", function () {
    expect(parser.parseCode("<?php\n    require_once(\"connect.inc\");\n    require('table.inc');\n    $stmt = mysqli_stmt_init($link);\n    try {\n        mysqli_stmt_insert_id($stmt);\n    } catch (Error $exception) {\n        echo $exception->getMessage() . \"\\n\";\n    }\n    if (!mysqli_stmt_prepare($stmt, \"SELECT id, label FROM test ORDER BY id LIMIT 1\") ||\n        !mysqli_stmt_execute($stmt)) {\n        printf(\"[004] [%d] %s\\n\", mysqli_stmt_errno($stmt), mysqli_stmt_error($stmt));\n    }\n    if (0 !== ($tmp = mysqli_stmt_insert_id($stmt)))\n        printf(\"[005] Expecting int/0, got %s/%s\\n\", gettype($tmp), $tmp);\n    mysqli_stmt_close($stmt);\n    // no auto_increment column\n    $stmt = mysqli_stmt_init($link);\n    if (!mysqli_stmt_prepare($stmt, \"INSERT INTO test(id, label) VALUES (100, 'a')\") ||\n        !mysqli_stmt_execute($stmt)) {\n        printf(\"[006] [%d] %s\\n\", mysqli_stmt_errno($stmt), mysqli_stmt_error($stmt));\n    }\n    if (0 !== ($tmp = mysqli_stmt_insert_id($stmt)))\n        printf(\"[007] Expecting int/0, got %s/%s\\n\", gettype($tmp), $tmp);\n    if (mysqli_get_server_version($link) > 50000 &&\n        (!mysqli_stmt_prepare($stmt, \"ALTER TABLE test MODIFY id INT NOT NULL AUTO_INCREMENT\") ||\n        !mysqli_stmt_execute($stmt))) {\n        printf(\"[008] [%d] %s\\n\", mysqli_stmt_errno($stmt), mysqli_stmt_error($stmt));\n    } else if (mysqli_get_server_version($link) < 50000){\n        mysqli_query($link, \"ALTER TABLE test MODIFY id INT NOT NULL AUTO_INCREMENT\");\n    }\n    if (!mysqli_stmt_prepare($stmt, \"INSERT INTO test(label) VALUES ('a')\") ||\n        !mysqli_stmt_execute($stmt)) {\n        printf(\"[009] [%d] %s\\n\", mysqli_stmt_errno($stmt), mysqli_stmt_error($stmt));\n    }\n    if (0 === ($tmp = mysqli_stmt_insert_id($stmt)))\n        printf(\"[010] Expecting int/any non zero, got %s/%s\\n\", gettype($tmp), $tmp);\n    mysqli_stmt_close($stmt);\n    mysqli_close($link);\n    try {\n        mysqli_stmt_insert_id($stmt);\n    } catch (Error $exception) {\n        echo $exception->getMessage() . \"\\n\";\n    }\n    print \"done!\";\n?>")).toMatchSnapshot();
  });
});
