// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/snmp/tests/snmp2_get.phpt
  it("Function snmp2_get", function () {
    expect(parser.parseCode("<?php\nrequire_once(__DIR__.'/snmp_include.inc');\n//EXPECTF format is quickprint OFF\nsnmp_set_quick_print(false);\nsnmp_set_valueretrieval(SNMP_VALUE_PLAIN);\necho \"Checking error handling\\n\";\necho \"Empty OID array\\n\";\ntry {\n    var_dump(snmp2_get($hostname, $community, array(), $timeout, $retries));\n} catch (\\ValueError $e) {\n    echo $e->getMessage() . \\PHP_EOL;\n}\necho \"Checking working\\n\";\necho \"Single OID\\n\";\nvar_dump(snmp2_get($hostname, $community, '.1.3.6.1.2.1.1.1.0', $timeout, $retries));\necho \"Single OID in array\\n\";\nvar_dump(snmp2_get($hostname, $community, array('.1.3.6.1.2.1.1.1.0'), $timeout, $retries));\necho \"Multiple OID\\n\";\nvar_dump(snmp2_get($hostname, $community, array('.1.3.6.1.2.1.1.1.0', '.1.3.6.1.2.1.1.3.0'), $timeout, $retries));\necho \"More error handling\\n\";\necho \"Single OID\\n\";\nvar_dump(snmp2_get($hostname, $community, '.1.3.6.1.2..1.1.1.0', $timeout, $retries));\necho \"Single OID in array\\n\";\nvar_dump(snmp2_get($hostname, $community, array('.1.3.6.1.2.1...1.1.0'), $timeout, $retries));\necho \"Multiple OID\\n\";\nvar_dump(snmp2_get($hostname, $community, array('.1.3.6.1.2.1...1.1.0', '.1.3.6.1.2.1.1.3.0'), $timeout, $retries));\necho \"noSuchName checks\\n\";\necho \"Single OID\\n\";\nvar_dump(snmp2_get($hostname, $community, '.1.3.6.1.2.1.1.1.110', $timeout, $retries));\necho \"Single OID in array\\n\";\nvar_dump(snmp2_get($hostname, $community, array('.1.3.6.1.2.1.1.1.110'), $timeout, $retries));\necho \"Multiple OID\\n\";\nvar_dump(snmp2_get($hostname, $community, array('.1.3.6.1.2.1.1.1.0', '.1.3.6.1.2.1.1.3.220'), $timeout, $retries));\n?>")).toMatchSnapshot();
  });
});
