// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/mysqli/tests/mysqli_stmt_execute_stored_proc_out.phpt
  it("mysqli_stmt_execute() - OUT", function () {
    expect(parser.parseCode("<?php\n    require_once('connect.inc');\n    if (!$link = my_mysqli_connect($host, $user, $passwd, $db, $port, $socket)) {\n        printf(\"[001] Cannot connect to the server using host=%s, user=%s, passwd=***, dbname=%s, port=%s, socket=%s\\n\",\n          $host, $user, $db, $port, $socket);\n    }\n    if (!mysqli_query($link, 'DROP PROCEDURE IF EXISTS p'))\n        printf(\"[003] [%d] %s.\\n\", mysqli_errno($link), mysqli_error($link));\n    if (mysqli_real_query($link, 'CREATE PROCEDURE p(IN ver_in VARCHAR(25), OUT ver_out VARCHAR(25)) BEGIN SELECT ver_in INTO ver_out; END;')) {\n        if (!$stmt = mysqli_prepare($link, 'CALL p(?, ?)'))\n            printf(\"[005] Cannot prepare CALL, [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n        $ver_in = 'myversion';\n        $ver_out = '';\n        if (!mysqli_stmt_bind_param($stmt, 'ss', $ver_in, $ver_out))\n            printf(\"[006] Cannot bind parameter, [%d] %s\\n\", mysqli_stmt_errno($stmt), mysqli_stmt_error($stmt));\n        if (!mysqli_stmt_execute($stmt))\n            printf(\"[007] Cannot execute CALL, [%d] %s\\n\", mysqli_stmt_errno($stmt), mysqli_stmt_error($stmt));\n        printf(\"[008] More results: %s\\n\", (mysqli_more_results($link) ? \"yes\" : \"no\"));\n        printf(\"[009] Next results: %s\\n\", (mysqli_next_result($link) ? \"yes\" : \"no\"));\n        try {\n            if (!mysqli_stmt_bind_result($stmt, $ver_out) || !mysqli_stmt_fetch($stmt))\n                printf(\"[010] [%d] %s\\n\", mysqli_stmt_errno($stmt), mysqli_stmt_error($stmt));\n        } catch (\\ArgumentCountError $e) {\n            echo $e->getMessage() . \\PHP_EOL;\n        }\n        if (\"myversion\" !== $ver_out)\n            printf(\"[011] Results seem wrong got '%s'\\n\", $ver_out);\n        if (!mysqli_stmt_close($stmt))\n            printf(\"[012] Cannot close statement, [%d] %s\\n\", mysqli_stmt_errno($stmt), mysqli_stmt_error($stmt));\n        if (!$res = $link->query(\"SELECT 1\"))\n            printf(\"[013] [%d] %s\\n\", $link->errno, $link->error);\n    } else {\n        printf(\"[004] Cannot create SP, [%d] %s.\\n\", mysqli_errno($link), mysqli_error($link));\n    }\n    mysqli_close($link);\n    print \"done!\";\n?>")).toMatchSnapshot();
  });
});
