// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/standard/tests/array/array_walk_recursive_variation6.phpt
  it("Test array_walk_recursive() function : usage variations - 'input' argument as diff. associative arrays", function () {
    expect(parser.parseCode("<?php\n/*\n * Passing 'input' argument as an associative array\n *    with Numeric & string keys\n*/\necho \"*** Testing array_walk_recursive() : 'input' as an associative array ***\\n\";\nfunction for_numeric($value, $key, $user_data)\n{\n  // dump the input values to see if they are\n  // passed with correct type\n  var_dump($key);\n  var_dump($value);\n  var_dump($user_data);\n  echo \"\\n\"; // new line to separate the output between each element\n}\nfunction for_string($value, $key)\n{\n  // dump the input values to see if they are\n  // passed with correct type\n  var_dump($key);\n  var_dump($value);\n  echo \"\\n\"; // new line to separate the output between each element\n}\nfunction for_mixed($value, $key)\n{\n  // dump the input values to see if they are\n  // passed with correct type\n  var_dump($key);\n  var_dump($value);\n  echo \"\\n\"; // new line to separate the output between each element\n}\n// Numeric keys\n$input = array( 0 => array(1 => 25, 5 => 12, 0 => -80), 1 => array(-2 => 100, 5 => 30));\necho \"-- Associative array with numeric keys --\\n\";\nvar_dump( array_walk_recursive($input, \"for_numeric\", 10));\n// String keys\n$input = array( \"a\" => \"Apple\", 'z' => array('b' => 'Bananna', \"c\" => \"carrot\"), 'x' => array('o' => \"Orange\"));\necho \"-- Associative array with string keys --\\n\";\nvar_dump( array_walk_recursive($input, \"for_string\"));\n// binary key\n$input = array( b\"a\" => \"Apple\", b\"b\" => \"Banana\");\necho \"-- Associative array with binary keys --\\n\";\nvar_dump( array_walk_recursive($input, \"for_string\"));\n// Mixed keys - numeric/string\n$input = array( 0 => array(0 => 1, 1 => 2), \"x\" => array(\"a\" => \"Apple\", \"b\" => \"Banana\"), 2 =>3);\necho \"-- Associative array with numeric/string keys --\\n\";\nvar_dump( array_walk_recursive($input, \"for_mixed\"));\necho \"Done\"\n?>")).toMatchSnapshot();
  });
});
