// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/mysqli/tests/071.phpt
  it("mysqli thread_id & kill", function () {
    expect(parser.parseCode("<?php\n    require_once(\"connect.inc\");\n    $mysql = new my_mysqli($host, $user, $passwd, $db, $port, $socket);\n    $version = $mysql->server_version;\n    var_dump($mysql->ping());\n    $ret = $mysql->kill($mysql->thread_id);\n    if ($IS_MYSQLND) {\n        if ($ret !== true){\n            printf(\"[001] Expecting boolean/true got %s/%s\\n\", gettype($ret), var_export($ret, true));\n        }\n    } else {\n        /* libmysql return value seems to depend on server version */\n        if ((($version >= 50123) || ($version <= 40200)) && $version != 50200) {\n            /* TODO: find exact version */\n            if ($ret !== true){\n                printf(\"[001] Expecting boolean/true got %s/%s @\\n\", gettype($ret), var_export($ret, true), $version);\n            }\n        } else {\n            if ($ret !== false){\n                printf(\"[001] Expecting boolean/false got %s/%s @\\n\", gettype($ret), var_export($ret, true), $version);\n            }\n        }\n    }\n    var_dump($mysql->ping());\n    $mysql->close();\n    $mysql = new my_mysqli($host, $user, $passwd, $db, $port, $socket);\n    var_dump(mysqli_ping($mysql));\n    $ret = $mysql->kill($mysql->thread_id);\n    if ($IS_MYSQLND) {\n        if ($ret !== true){\n            printf(\"[002] Expecting boolean/true got %s/%s\\n\", gettype($ret), var_export($ret, true));\n        }\n    } else {\n        /* libmysql return value seems to depend on server version */\n        if ((($version >= 50123) || ($version <= 40200)) && $version != 50200) {\n            /* TODO: find exact version */\n            if ($ret !== true){\n                printf(\"[002] Expecting boolean/true got %s/%s @\\n\", gettype($ret), var_export($ret, true), $version);\n            }\n        } else {\n            if ($ret !== false){\n            printf(\"[002] Expecting boolean/false got %s/%s @\\n\", gettype($ret), var_export($ret, true), $version);\n            }\n        }\n    }\n    var_dump(mysqli_ping($mysql));\n    $mysql->close();\n    print \"done!\";\n?>")).toMatchSnapshot();
  });
});
