// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/intl/tests/calendar_get_Least_Greatest_Minimum_Maximum_error.phpt
  it("IntlCalendar::get/Least/Greatest/Minimum/Maximum(): bad arguments", function () {
    expect(parser.parseCode("<?php\n$c = new IntlGregorianCalendar(NULL, 'pt_PT');\ntry {\n    var_dump($c->getLeastMaximum(-1));\n} catch (Error $e) {\n    echo get_class($e) . ': ' . $e->getCode() . ', ' . $e->getMessage() . \\PHP_EOL;\n}\ntry {\n    var_dump($c->getMaximum(-1));\n} catch (Error $e) {\n    echo get_class($e) . ': ' . $e->getCode() . ', ' . $e->getMessage() . \\PHP_EOL;\n}\ntry {\n    var_dump($c->getGreatestMinimum(-1));\n} catch (Error $e) {\n    echo get_class($e) . ': ' . $e->getCode() . ', ' . $e->getMessage() . \\PHP_EOL;\n}\ntry {\n    var_dump($c->getMinimum(-1));\n} catch (Error $e) {\n    echo get_class($e) . ': ' . $e->getCode() . ', ' . $e->getMessage() . \\PHP_EOL;\n}\ntry {\n    var_dump(intlcal_get_least_maximum($c, -1));\n} catch (Error $e) {\n    echo get_class($e) . ': ' . $e->getCode() . ', ' . $e->getMessage() . \\PHP_EOL;\n}\ntry {\n    var_dump(intlcal_get_maximum($c, -1));\n} catch (Error $e) {\n    echo get_class($e) . ': ' . $e->getCode() . ', ' . $e->getMessage() . \\PHP_EOL;\n}\ntry {\n    var_dump(intlcal_get_greatest_minimum($c, -1));\n} catch (Error $e) {\n    echo get_class($e) . ': ' . $e->getCode() . ', ' . $e->getMessage() . \\PHP_EOL;\n}\ntry {\n    var_dump(intlcal_get_minimum($c, -1));\n} catch (Error $e) {\n    echo get_class($e) . ': ' . $e->getCode() . ', ' . $e->getMessage() . \\PHP_EOL;\n}\ntry {\n    var_dump(intlcal_get_least_maximum(1, 1));\n} catch (Error $e) {\n    echo get_class($e) . ': ' . $e->getCode() . ', ' . $e->getMessage() . \\PHP_EOL;\n}\ntry {\n    var_dump(intlcal_get_maximum(1, 1));\n} catch (Error $e) {\n    echo get_class($e) . ': ' . $e->getCode() . ', ' . $e->getMessage() . \\PHP_EOL;\n}\ntry {\n    var_dump(intlcal_get_greatest_minimum(1, -1));\n} catch (Error $e) {\n    echo get_class($e) . ': ' . $e->getCode() . ', ' . $e->getMessage() . \\PHP_EOL;\n}\ntry {\n    var_dump(intlcal_get_minimum(1, -1));\n} catch (Error $e) {\n    echo get_class($e) . ': ' . $e->getCode() . ', ' . $e->getMessage() . \\PHP_EOL;\n}\n?>")).toMatchSnapshot();
  });
});
