// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/intl/tests/dateformat_format_relative.phpt
  it("datefmt_format_code() with relative formats", function () {
    expect(parser.parseCode("<?php\nprintFormat(IntlDateFormatter::RELATIVE_FULL, IntlDateFormatter::NONE, getYesterday());\nprintFormat(IntlDateFormatter::RELATIVE_LONG, IntlDateFormatter::NONE, getYesterday());\nprintFormat(IntlDateFormatter::RELATIVE_MEDIUM, IntlDateFormatter::NONE, getYesterday());\nprintFormat(IntlDateFormatter::RELATIVE_SHORT, IntlDateFormatter::NONE, getYesterday());\nprintFormat(IntlDateFormatter::RELATIVE_FULL, IntlDateFormatter::NONE, getToday());\nprintFormat(IntlDateFormatter::RELATIVE_LONG, IntlDateFormatter::NONE, getToday());\nprintFormat(IntlDateFormatter::RELATIVE_MEDIUM, IntlDateFormatter::NONE, getToday());\nprintFormat(IntlDateFormatter::RELATIVE_SHORT, IntlDateFormatter::NONE, getToday());\nprintFormat(IntlDateFormatter::RELATIVE_FULL, IntlDateFormatter::NONE, getTomorrow());\nprintFormat(IntlDateFormatter::RELATIVE_LONG, IntlDateFormatter::NONE, getTomorrow());\nprintFormat(IntlDateFormatter::RELATIVE_MEDIUM, IntlDateFormatter::NONE, getTomorrow());\nprintFormat(IntlDateFormatter::RELATIVE_SHORT, IntlDateFormatter::NONE, getTomorrow());\nprintFormat(IntlDateFormatter::RELATIVE_FULL, IntlDateFormatter::NONE, getDayInPast());\nprintFormat(IntlDateFormatter::RELATIVE_LONG, IntlDateFormatter::NONE, getDayInPast());\nprintFormat(IntlDateFormatter::RELATIVE_MEDIUM, IntlDateFormatter::NONE, getDayInPast());\nprintFormat(IntlDateFormatter::RELATIVE_SHORT, IntlDateFormatter::NONE, getDayInPast());\nfunction printFormat(int $dateFormat, int $timeFormat, DateTimeImmutable $time) {\n    $formatter = new IntlDateFormatter(\n        \"en_US\",\n        $dateFormat,\n        $timeFormat,\n        \"America/Los_Angeles\",\n        IntlDateFormatter::GREGORIAN\n    );\n    echo $formatter->format($time) . \"\\n\";\n}\nfunction getToday(): DateTimeImmutable {\n    return new DateTimeImmutable();\n}\nfunction getYesterday(): DateTimeImmutable {\n    return new DateTimeImmutable(\"-1 day\");\n}\nfunction getTomorrow(): DateTimeImmutable {\n    return new DateTimeImmutable(\"+1 day\");\n}\nfunction getDayInPast(): DateTimeImmutable {\n    return new DateTimeImmutable(\"2020-01-20 20:20:20\", new DateTimeZone(\"UTC\"));\n}\n?>")).toMatchSnapshot();
  });
});
