// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/oci8/tests/imp_res_get_5.phpt
  it("Oracle Database 12c Implicit Result Sets: oci_get_implicit_resultset: get from wrong statement", function () {
    expect(parser.parseCode("<?php\nrequire(__DIR__.'/connect.inc');\nfunction print_row($row)\n{\n    foreach ($row as $item) {\n        echo \"  \".$item;\n    }\n    echo \"\\n\";\n}\n$plsql =\n    \"declare\n      c1 sys_refcursor;\n    begin\n      open c1 for select 1 from dual union all select 2 from dual;\n      dbms_sql.return_result(c1);\n      open c1 for select 3 from dual union all select 4 from dual;\n      dbms_sql.return_result(c1);\n      open c1 for select 5 from dual union all select 6 from dual;\n      dbms_sql.return_result(c1);\n    end;\";\n// Run Test\necho \"Test 1\\n\";\n// This test effectively discards all the first IRS results\n$s = oci_parse($c, $plsql);\noci_execute($s);\nwhile (($s1 = oci_get_implicit_resultset($s))) {  // $s1 is never used again so its results are lost\n    while (($row = oci_fetch_array($s, OCI_ASSOC+OCI_RETURN_NULLS)) != false) {  // use parent $s instead of $s1\n        print_row($row);\n    }\n}\noci_free_statement($s);\necho \"\\nTest 2 - fetch first IRS explicitly\\n\";\n$s = oci_parse($c, $plsql);\noci_execute($s);\n$s1 = oci_get_implicit_resultset($s);\nwhile (($row = oci_fetch_row($s1)) != false) {\n    print_row($row);\n}\nwhile (($row = oci_fetch_row($s)) != false) {\n    print_row($row);\n}\noci_free_statement($s);\necho \"\\nTest 3 - fetch part of IRS explicitly\\n\";\n$s = oci_parse($c, $plsql);\noci_execute($s);\n$s1 = oci_get_implicit_resultset($s);\nwhile (($row = oci_fetch_row($s1)) != false) {\n    print_row($row);\n}\n$row = oci_fetch_row($s);\nprint_row($row);\n$s1 = oci_get_implicit_resultset($s);\nwhile (($row = oci_fetch_row($s1)) != false) {\n    print_row($row);\n}\nwhile (($row = oci_fetch_row($s)) != false) {\n    print_row($row);\n}\noci_free_statement($s);\necho \"\\nTest 4 - skip IRSs\\n\";\n$s = oci_parse($c, $plsql);\noci_execute($s);\n$s1 = oci_get_implicit_resultset($s);\n$s1 = oci_get_implicit_resultset($s);\nwhile (($row = oci_fetch_row($s)) != false) { // parent\n    print_row($row);\n}\noci_free_statement($s);\n?>")).toMatchSnapshot();
  });
});
