// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/mysqli/tests/bug51647.phpt
  it("Bug #51647 (Certificate file without private key (pk in another file) doesn't work)", function () {
    expect(parser.parseCode("<?php\n    include (\"connect.inc\");\n    if (!is_object($link = mysqli_init()))\n        printf(\"[001] Cannot create link\\n\");\n    if (!my_mysqli_real_connect($link, $host, $user, $passwd, $db, $port, $socket, MYSQLI_CLIENT_SSL | MYSQLI_CLIENT_SSL_DONT_VERIFY_SERVER_CERT)) {\n        printf(\"[003] Connect failed, [%d] %s\\n\", mysqli_connect_errno(), mysqli_connect_error());\n    }\n    if (!$res = $link->query('SHOW STATUS like \"Ssl_cipher\"')) {\n        if (1064 == $link->errno) {\n            /* ERROR 1064 (42000): You have an error in your SQL syntax;  = sql strict mode */\n            if ($res = $link->query(\"SHOW STATUS\")) {\n                while ($row = $res->fetch_assoc())\n                    if ($row['Variable_name'] == 'Ssl_cipher')\n                        break;\n            } else {\n                printf(\"[005] [%d] %s\\n\", $link->errno, $link->error);\n            }\n        } else {\n            printf(\"[004] [%d] %s\\n\", $link->errno, $link->error);\n        }\n    } else {\n        if (!$row = $res->fetch_assoc())\n            printf(\"[006] [%d] %s\\n\", $link->errno, $link->error);\n        if (!strlen($row[\"Value\"]))\n            printf(\"[007] Empty cipher. No encryption!\");\n        var_dump($row);\n    }\n    $link->close();\n    if (!is_object($link = mysqli_init()))\n        printf(\"[008] Cannot create link\\n\");\n    if (!my_mysqli_real_connect($link, $host, $user, $passwd, $db, $port, $socket, MYSQLI_CLIENT_SSL)) {\n        printf(\"[009] Connect failed, [%d] %s\\n\", mysqli_connect_errno(), mysqli_connect_error());\n    }\n    if (!$res = $link->query('SHOW STATUS like \"Ssl_cipher\"')) {\n        if (1064 == $link->errno) {\n            /* ERROR 1064 (42000): You have an error in your SQL syntax;  = sql strict mode */\n            if ($res = $link->query(\"SHOW STATUS\")) {\n                while ($row = $res->fetch_assoc())\n                    if ($row['Variable_name'] == 'Ssl_cipher')\n                        break;\n            } else {\n                printf(\"[010] [%d] %s\\n\", $link->errno, $link->error);\n            }\n        } else {\n            printf(\"[011] [%d] %s\\n\", $link->errno, $link->error);\n        }\n    } else {\n        if (!$row = $res->fetch_assoc())\n            printf(\"[012] [%d] %s\\n\", $link->errno, $link->error);\n        if (!strlen($row[\"Value\"]))\n            printf(\"[013] Empty cipher. No encryption!\");\n        var_dump($row);\n    }\n    $link->close();\n    print \"done!\";\n?>")).toMatchSnapshot();
  });
});
