// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/standard/tests/file/filesize_variation2.phpt
  it("Test filesize() function: usage variations - size of dir/subdir", function () {
    expect(parser.parseCode("<?php\n$file_path = __DIR__;\nrequire($file_path.\"/file.inc\");\necho \"*** Testing filesize(): usage variations ***\\n\";\necho \"\\n*** Testing size of a dir, sub-dir and file with filesize() ***\\n\";\necho \"-- Creating a base dir, and checking its size --\\n\";\nmkdir( $file_path.\"/filesize_variation2\");\nvar_dump( filesize( $file_path.\"/filesize_variation2\"));\nclearstatcache();\necho \"-- Creating a file inside base dir, and checking dir & file size --\\n\";\ncreate_files($file_path.\"/filesize_variation2\", 1, \"numeric\", 0755, 1, \"w\", \"filesize_variation\");\nvar_dump( filesize( $file_path.\"/filesize_variation2\"));\nclearstatcache();\nvar_dump( filesize( $file_path.\"/filesize_variation2/filesize_variation1.tmp\"));\nclearstatcache();\ndelete_files($file_path.\"/filesize_variation2\", 1, \"filesize_variation\");\necho \"-- Creating an empty sub-dir in base-dir, and checking size of base and sub dir --\\n\";\nmkdir( $file_path.\"/filesize_variation2/filesize_variation2_sub\");\nvar_dump( filesize( $file_path.\"/filesize_variation2\")); // size of base dir\nclearstatcache();\nvar_dump( filesize( $file_path.\"/filesize_variation2/filesize_variation2_sub\")); // size of subdir\nclearstatcache();\necho \"-- Creating a file inside sub-dir, and checking size of base, subdir and file created --\\n\";\n// create only the file, as base and subdir is already created\n$filename =  $file_path.\"/filesize_variation2/filesize_variation2_sub/filesize_variation2.tmp\";\n$file_handle = fopen($filename, \"w\");\nfwrite($file_handle, str_repeat(\"Hello,World \", 1000) ); // create file of size 12000 bytes\nfclose($file_handle);\n// size of base dir\nvar_dump( filesize( $file_path.\"/filesize_variation2\"));\nclearstatcache();\n// size of subdir\nvar_dump( filesize( $file_path.\"/filesize_variation2/filesize_variation2_sub\"));\nclearstatcache();\n// size of file inside subdir\nvar_dump( filesize( $file_path.\"/filesize_variation2/filesize_variation2_sub/filesize_variation2.tmp\"));\nclearstatcache();\necho \"*** Done ***\\n\";\n?>")).toMatchSnapshot();
  });
});
