// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/date/tests/rfc-datetime_and_daylight_saving_time-type3-bs.phpt
  it("RFC: DateTime and Daylight Saving Time Transitions (zone type 3, bs)", function () {
    expect(parser.parseCode("<?php\ndate_default_timezone_set('America/New_York');\n$tz = new DateTimeZone('America/New_York');\n$date_format = 'Y-m-d H:i:s T e';\n$interval_format = 'P%dDT%hH';\n/*\n * Backward Transitions, sub().\n */\n$end   = new DateTime('2010-11-07 01:00:00 EST');\n$end->setTimeZone($tz);\n$interval_spec = 'PT1S';\n$interval = new DateInterval($interval_spec);\necho 'bs1 ' . $end->format($date_format) . \" - $interval_spec = \"\n    . $end->sub($interval)->format($date_format) . \"\\n\";\n$end   = new DateTime('2010-11-07 04:30:00');\n$interval_spec = 'P1D';\n$interval = new DateInterval($interval_spec);\necho 'bs2 ' . $end->format($date_format) . \" - $interval_spec = \"\n    . $end->sub($interval)->format($date_format) . \"\\n\";\n$end   = new DateTime('2010-11-07 03:30:00');\n$interval_spec = 'PT24H';\n$interval = new DateInterval($interval_spec);\necho 'bs3 ' . $end->format($date_format) . \" - $interval_spec = \"\n    . $end->sub($interval)->format($date_format) . \"\\n\";\n$end   = new DateTime('2010-11-07 02:30:00');\n$interval_spec = 'PT23H';\n$interval = new DateInterval($interval_spec);\necho 'bs4 ' . $end->format($date_format) . \" - $interval_spec = \"\n    . $end->sub($interval)->format($date_format) . \"\\n\";\n$end   = new DateTime('2010-11-07 01:30:00 EST');\n$end->setTimeZone($tz);\n$interval_spec = 'PT22H';\n$interval = new DateInterval($interval_spec);\necho 'bs5 ' . $end->format($date_format) . \" - $interval_spec = \"\n    . $end->sub($interval)->format($date_format) . \"\\n\";\n$end   = new DateTime('2010-11-07 01:30:00 EDT');\n$end->setTimeZone($tz);\n$interval_spec = 'PT21H';\n$interval = new DateInterval($interval_spec);\necho 'bs6 ' . $end->format($date_format) . \" - $interval_spec = \"\n    . $end->sub($interval)->format($date_format) . \"\\n\";\n$end   = new DateTime('2010-11-07 01:30:00');\n$interval_spec = 'P1D';\n$interval = new DateInterval($interval_spec);\necho 'bs7 ' . $end->format($date_format) . \" - $interval_spec = \"\n    . $end->sub($interval)->format($date_format) . \"\\n\";\n$end   = new DateTime('2010-11-07 01:30:00 EST');\n$end->setTimeZone($tz);\n$interval_spec = 'P1DT1H';\n$interval = new DateInterval($interval_spec);\necho 'bs8 ' . $end->format($date_format) . \" - $interval_spec = \"\n    . $end->sub($interval)->format($date_format) . \"\\n\";\n$end   = new DateTime('2010-11-07 03:30:00');\n$interval_spec = 'P1D';\n$interval = new DateInterval($interval_spec);\necho 'bs9 ' . $end->format($date_format) . \" - $interval_spec = \"\n    . $end->sub($interval)->format($date_format) . \"\\n\";\n$end   = new DateTime('2010-11-07 02:30:00');\n$interval_spec = 'P1D';\n$interval = new DateInterval($interval_spec);\necho 'bs10 ' . $end->format($date_format) . \" - $interval_spec = \"\n    . $end->sub($interval)->format($date_format) . \"\\n\";\n?>")).toMatchSnapshot();
  });
});
