// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/mysqli/tests/mysqli_change_user_insert_id.phpt
  it("mysqli_change_user() - LAST_INSERT_ID() - http://bugs.mysql.com/bug.php?id=45184?", function () {
    expect(parser.parseCode("<?php\n    require_once('connect.inc');\n    if (!$link = my_mysqli_connect($host, $user, $passwd, $db, $port, $socket))\n        printf(\"[001] [%d] %s\\n\", mysqli_connect_errno(), mysqli_connect_error());\n    if (!mysqli_query($link, 'DROP TABLE IF EXISTS test'))\n        printf(\"[002] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    if (!mysqli_query($link, 'CREATE TABLE test(id INT AUTO_INCREMENT PRIMARY KEY, label CHAR(10))'))\n        printf(\"[003] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    if (!mysqli_query($link, \"INSERT INTO test(id, label) VALUES (100, 'z')\"))\n        printf(\"[004] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    if (($insert_id = mysqli_insert_id($link)) !== 100)\n        printf(\"[005] Expecting 100, got %d, [%d] %s\\n\",\n            $insert_id,\n            mysqli_errno($link), mysqli_error($link));\n    // LAST_INSERT_ID should be reset\n    mysqli_change_user($link, $user, $passwd, $db);\n    if (($insert_id = mysqli_insert_id($link)) !== 0)\n            printf(\"[006] Expecting 0, got %d, [%d] %s\\n\",\n                $insert_id,\n                mysqli_errno($link), mysqli_error($link));\n    if (!$res = mysqli_query($link, 'SELECT LAST_INSERT_ID() as _insert_id'))\n        printf(\"[007] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    if (!$row = mysqli_fetch_assoc($res))\n        printf(\"[008] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    mysqli_free_result($res);\n    if ($row['_insert_id'] != $insert_id)\n        printf(\"LAST_INSERT_ID() [%d] and mysqli_insert_id [%d] differ!\\n\",\n            $row['_insert_id'], $insert_id);\n    if ($row['_insert_id'] != 0)\n        printf(\"Expecting 0 got %d\\n\", $row['_insert_id']);\n    mysqli_close($link);\n    print \"done!\";\n?>")).toMatchSnapshot();
  });
});
