// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/gmp/tests/overloading.phpt
  it("GMP operator overloading", function () {
    expect(parser.parseCode("<?php\n$a = gmp_init(42);\n$b = gmp_init(17);\nvar_dump($a + $b);\nvar_dump($a + 17);\nvar_dump(42 + $b);\nvar_dump($a - $b);\nvar_dump($a - 17);\nvar_dump(42 - $b);\nvar_dump($a * $b);\nvar_dump($a * 17);\nvar_dump(42 * $b);\nvar_dump($a / $b);\nvar_dump($a / 17);\nvar_dump(42 / $b);\ntry {\n    var_dump($a / 0);\n} catch (\\DivisionByZeroError $e) {\n    echo $e->getMessage() . \\PHP_EOL;\n}\nvar_dump($a % $b);\nvar_dump($a % 17);\nvar_dump(42 % $b);\ntry {\n    var_dump($a % 0);\n} catch (\\DivisionByZeroError $e) {\n    echo $e->getMessage() . \\PHP_EOL;\n}\nvar_dump($a ** $b);\nvar_dump($a ** 17);\nvar_dump(42 ** $b);\nvar_dump($a | $b);\nvar_dump($a | 17);\nvar_dump(42 | $b);\nvar_dump($a & $b);\nvar_dump($a & 17);\nvar_dump(42 & $b);\nvar_dump($a ^ $b);\nvar_dump($a ^ 17);\nvar_dump(42 ^ $b);\nvar_dump($a << $b);\nvar_dump($a << 17);\nvar_dump(42 << $b);\nvar_dump($a >> 2);\nvar_dump(-$a >> 2);\ntry {\n    $a << -1;\n} catch (ValueError $exception) {\n    echo $exception->getMessage() . \"\\n\";\n}\ntry {\n    $a >> -1;\n} catch (ValueError $exception) {\n    echo $exception->getMessage() . \"\\n\";\n}\nvar_dump(~$a);\nvar_dump(-$a);\nvar_dump(+$a);\nvar_dump($a == $b);\nvar_dump($a != $b);\nvar_dump($a < $b);\nvar_dump($a <= $b);\nvar_dump($a > $b);\nvar_dump($a >= $b);\nvar_dump($a == $a);\nvar_dump($a != $a);\nvar_dump($a == 42);\nvar_dump($a != 42);\nvar_dump($a < 42);\nvar_dump($a <= 42);\nvar_dump($a > 42);\nvar_dump($a >= 42);\ntry {\n    var_dump($a == new stdClass);\n} catch (\\TypeError $e) {\n    echo $e->getMessage() . \\PHP_EOL;\n}\n$a += 1;\nvar_dump($a);\n$a -= 1;\nvar_dump($a);\nvar_dump(++$a);\nvar_dump($a++);\nvar_dump($a);\nvar_dump(--$a);\nvar_dump($a--);\nvar_dump($a);\n// Test operator that was not overloaded\nvar_dump($a . $b);\nvar_dump($a . '17');\nvar_dump('42' . $b);\n$a .= '17';\nvar_dump($a);\n?>")).toMatchSnapshot();
  });
});
