// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/xmlreader/tests/003-move-errors.phpt
  it("XMLReader: libxml2 XML Reader, Move cursor to an attribute, with invalid arguments", function () {
    expect(parser.parseCode("<?php\n// Set up test data in a new file\n$xmlstring = '<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<books><book num=\"1\" idx=\"2\">book1</book></books>';\n$filename = __DIR__ . '/003-move-errors.xml';\nfile_put_contents($filename, $xmlstring);\n// Load test data into a new XML Reader\n$reader = new XMLReader();\nif (!$reader->open($filename)) {\n    exit('XML could not be read');\n}\n// Parse the data\nwhile ($reader->read()) {\n    if ($reader->nodeType != XMLREADER::END_ELEMENT) {\n        // Find the book node\n        if ($reader->nodeType == XMLREADER::ELEMENT && $reader->name == 'book') {\n            echo $reader->name . \"\\n\";\n            $attr = $reader->moveToNextAttribute();\n            var_dump($attr);\n            echo $reader->name . \": \";\n            echo $reader->value . \"\\n\";\n            // Test for call with an empty string argument\n            try {\n                $reader->moveToAttribute('');\n            } catch (ValueError $exception) {\n                echo $exception->getMessage() . \"\\n\";\n            }\n            // Ensure that node pointer has not changed position\n            echo $reader->name . \": \";\n            echo $reader->value . \"\\n\";\n            // Test for call by name for an attribute that doesn't exist\n            $attr = $reader->moveToAttribute('isbn');\n            var_dump($attr);\n            // Ensure that node pointer has not changed position\n            echo $reader->name . \": \";\n            echo $reader->value . \"\\n\";\n            // Test for call by number for an attribute that doesn't exist\n            $attr = $reader->moveToAttributeNo(911);\n            var_dump($attr);\n            // Oddly, node pointer moves back to the element in this case\n            echo $reader->name . \"\\n\";\n        }\n    }\n}\n// clean up\n$reader->close();\n?>")).toMatchSnapshot();
  });
});
