// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/standard/tests/array/array_diff_basic.phpt
  it("Test array_diff() function : basic functionality", function () {
    expect(parser.parseCode("<?php\n/*\n * Test basic functionality of array_diff\n */\necho \"*** Testing array_diff() : basic functionality ***\\n\";\n//Test indexed array with integers as elements\n$array_int1 = array (1, 2, 3, 4);\n$array_int2 = array (3, 4, 5, 6);\necho \"-- Test indexed array with integers as elements --\\n\";\nvar_dump(array_diff($array_int1, $array_int2));\nvar_dump(array_diff($array_int2, $array_int1));\n//Test indexed array with strings as elements\n$array_string1 = array ('one', 'two', 'three', 'four');\n$array_string2 = array ('three', 'four', 'five', 'six');\necho \"-- Test indexed array with strings as elements --\\n\";\nvar_dump(array_diff($array_string1, $array_string2));\nvar_dump(array_diff($array_string2, $array_string1));\n//Test associative array with strings as keys and integers as elements\n$array_assoc_int1 = array ('one' => 1, 'two' => 2, 'three' => 3, 'four' => 4);\n$array_assoc_int2 = array ('three' => 3, 'four' => 4, 'five' => 5, 'six' => 6);\necho \"-- Test associative array with strings as keys and integers as elements --\\n\";\nvar_dump(array_diff($array_assoc_int1, $array_assoc_int2));\nvar_dump(array_diff($array_assoc_int2, $array_assoc_int1));\n//Test associative array with strings as keys and elements\n$array_assoc_str1 = array ('one' => 'un', 'two' => 'deux', 'three' => 'trois', 'four' => 'quatre');\n$array_assoc_str2 = array ('three' => 'trois', 'four' => 'quatre', 'five' => 'cinq', 'six' => 'six');\necho \"-- Test associative array with strings as keys and integers as elements --\\n\";\nvar_dump(array_diff($array_assoc_str1, $array_assoc_str2));\nvar_dump(array_diff($array_assoc_str2, $array_assoc_str1));\necho \"-- Test array_diff with more than 2 arguments --\\n\";\nvar_dump(array_diff($array_int1, $array_int2, $array_string1, $array_string2));\necho \"Done\";\n?>")).toMatchSnapshot();
  });
});
