// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/mysqli/tests/mysqli_change_user_rollback.phpt
  it("mysqli_change_user() - ROLLBACK", function () {
    expect(parser.parseCode("<?php\n    require_once('connect.inc');\n    require_once('table.inc');\n    if (!mysqli_query($link, 'ALTER TABLE test ENGINE=InnoDB'))\n        printf(\"[001] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    mysqli_autocommit($link, false);\n    if (!$res = mysqli_query($link, 'SELECT COUNT(*) AS _num FROM test'))\n        printf(\"[002] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    if (!$row = mysqli_fetch_assoc($res))\n        printf(\"[003] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    mysqli_free_result($res);\n    $num = $row['_num'];\n    assert($num > 0);\n    if (!$res = mysqli_query($link, 'DELETE FROM test'))\n        printf(\"[004] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    if (!$res = mysqli_query($link, 'SELECT COUNT(*) AS _num FROM test'))\n        printf(\"[005] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    if (!$row = mysqli_fetch_assoc($res))\n        printf(\"[006] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    mysqli_free_result($res);\n    if (0 != $row['_num'])\n        printf(\"[007] Rows should have been deleted in this transaction\\n\");\n    // DELETE should be rolled back\n    mysqli_change_user($link, $user, $passwd, $db);\n    if (!$res = mysqli_query($link, 'SELECT COUNT(*) AS _num FROM test'))\n        printf(\"[008] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    if (!$row = mysqli_fetch_assoc($res))\n        printf(\"[009] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    if ($row['_num'] != $num)\n        printf(\"[010] Expecting %d rows in the table test, found %d rows\\n\",\n            $num, $row['_num']);\n    mysqli_free_result($res);\n    mysqli_close($link);\n    print \"done!\";\n?>")).toMatchSnapshot();
  });
});
