// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/intl/tests/locale_filter_matches2.phpt
  it("locale_filter_matches.phpt() icu >= 4.8 && icu < 50.1.2", function () {
    expect(parser.parseCode("<?php\n/*\n * Try parsing different Locales\n * with Procedural and Object methods.\n */\nfunction ut_main()\n{\n    $loc_ranges = array(\n        'de-de',\n        'sl_IT',\n        'sl_IT_Nedis',\n        'jbo',\n        'art-lojban',\n        'sl_IT'\n    );\n    $lang_tags = array(\n        'de-DEVA',\n        'de-DE-1996',\n        'de-DE',\n        'zh_Hans',\n        'de-CH-1996',\n        'sl_IT',\n        'sl_IT_nedis-a-kirti-x-xyz',\n        'sl_IT_rozaj',\n        'sl_IT_NEDIS_ROJAZ_1901',\n        'i-enochian',\n        'sgn-CH-de',\n        'art-lojban',\n        'i-lux',\n        'art-lojban',\n        'jbo',\n        'en_sl_IT'\n    );\n    $res_str = '';\n    $isCanonical = false;\n    foreach($loc_ranges as $loc_range){\n        foreach($lang_tags as $lang_tag){\n            $res_str .=\"--------------\\n\";\n            $result= ut_loc_locale_filter_matches( $lang_tag , $loc_range , $isCanonical);\n            $res_str .= \"loc_range:$loc_range matches lang_tag $lang_tag ? \";\n            if( $result){\n                $res_str .= \"YES\\n\";\n            }else{\n                $res_str .= \"NO\\n\";\n            }\n//canonicalized version\n            $result= ut_loc_locale_filter_matches( $lang_tag , $loc_range , !($isCanonical));\n            $can_loc_range = ut_loc_canonicalize($loc_range);\n            $can_lang_tag = ut_loc_canonicalize($lang_tag);\n            $res_str .= \"loc_range:$can_loc_range canonically matches lang_tag $can_lang_tag ? \";\n            if( $result){\n                $res_str .= \"YES\\n\";\n            }else{\n                $res_str .= \"NO\\n\";\n            }\n        }\n    }\n    $res_str .= \"\\n\";\n    return $res_str;\n}\ninclude_once( 'ut_common.inc' );\nut_run();\n?>")).toMatchSnapshot();
  });
});
