// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/mbstring/tests/mb_strlen_variation3.phpt
  it("Test mb_strlen() function : usage variations - Pass list of encodings", function () {
    expect(parser.parseCode("<?php\n/*\n * Pass all encodings listed on php.net to mb_strlen to test that function recognises them\n * NB: The strings passed are *NOT* necessarily encoded in the encoding passed to the function.\n * This test is purely to see whether the function recognises the encoding.\n */\necho \"*** Testing mb_strlen() : usage variations ***\\n\";\n$encoding = array('UCS-4',\t\t\t/*1*/\n                  'UCS-4BE',\n                  'UCS-4LE',\n                  'UCS-2',\n                  'UCS-2BE',\t\t/*5*/\n                  'UCS-2LE',\n                  'UTF-32',\n                  'UTF-32BE',\n                  'UTF-32LE',\n                  'UTF-16',\t\t\t/*10*/\n                  'UTF-16BE',\n                  'UTF-16LE',\n                  'UTF-7',\n                  'UTF7-IMAP',\n                  'UTF-8',\t\t\t/*15*/\n                  'ASCII',\n                  'EUC-JP',\n                  'SJIS',\n                  'eucJP-win',\n                  'SJIS-win',\t\t/*20*/\n                  'ISO-2022-JP',\n                  'JIS',\n                  'ISO-8859-1',\n                  'ISO-8859-2',\n                  'ISO-8859-3',\t\t/*25*/\n                  'ISO-8859-4',\n                  'ISO-8859-5',\n                  'ISO-8859-6',\n                  'ISO-8859-7',\n                  'ISO-8859-8',\t\t/*30*/\n                  'ISO-8859-9',\n                  'ISO-8859-10',\n                  'ISO-8859-13',\n                  'ISO-8859-14',\n                  'ISO-8859-15',\t/*35*/\n                  'byte2be',\n                  'byte2le',\n                  'byte4be',\n                  'byte4le',\n                  'BASE64',\t\t\t/*40*/\n                  'HTML-ENTITIES',\n                  '7bit',\n                  '8bit',\n                  'EUC-CN',\n                  'CP936',\t\t\t/*45*/\n                  'HZ',\n                  'EUC-TW',\n                  'CP950',\n                  'BIG-5',\n                  'EUC-KR',\t\t\t/*50*/\n                  'UHC',\n                  'ISO-2022-KR',\n                  'Windows-1251',\n                  'Windows-1252',\n                  'CP866',\t\t\t/*55*/\n                  'KOI8-R');\t\t/*56*/\n$iterator = 1;\n$string_ascii = 'abc def';\n$string_mb = base64_decode('44K/44OT44Ol44Os44O844OG44Kj44Oz44Kw44O744Oe44K344O844Oz44O744Kr44Oz44OR44OL44O8');\nforeach($encoding as $enc) {\n    echo \"\\n-- Iteration $iterator: $enc --\\n\";\n    echo \"-- ASCII String --\\n\";\n    if(mb_strlen($string_ascii, $enc)) {\n        echo \"Encoding $enc recognised\\n\";\n    } else {\n        echo \"Encoding $enc not recognised\\n\";\n    }\n    echo \"-- Multibyte String --\\n\";\n    if(mb_strlen($string_mb, $enc)){\n        echo \"Encoding $enc recognised\\n\";\n    } else {\n        echo \"Encoding $enc not recognised\\n\";\n    }\n    $iterator++;\n}\necho \"Done\";\n?>")).toMatchSnapshot();
  });
});
