// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/standard/tests/file/stream_rfc2397_007.phpt
  it("Stream: RFC2397 and seeking", function () {
    expect(parser.parseCode("<?php\n$streams = array(\n    \"data:,012345\",\n    );\nforeach($streams as $stream)\n{\n    echo \"===$stream===\\n\";\n    $fp = fopen($stream, 'rb');\n    var_dump(ftell($fp));\n    var_dump(feof($fp));\n    echo \"===S:4,S===\\n\";\n    var_dump(fseek($fp, 4));\n    var_dump(ftell($fp));\n    var_dump(feof($fp));\n    echo \"===GETC===\\n\";\n    var_dump(fgetc($fp));\n    var_dump(ftell($fp));\n    var_dump(feof($fp));\n    echo \"===GETC===\\n\";\n    var_dump(fgetc($fp));\n    var_dump(fgetc($fp));\n    var_dump(ftell($fp));\n    var_dump(feof($fp));\n    echo \"===REWIND===\\n\";\n    var_dump(rewind($fp));\n    var_dump(ftell($fp));\n    var_dump(feof($fp));\n    echo \"===GETC===\\n\";\n    var_dump(fgetc($fp));\n    var_dump(ftell($fp));\n    var_dump(feof($fp));\n    echo \"===S:3,S===\\n\";\n    var_dump(fseek($fp, 3, SEEK_SET));\n    var_dump(ftell($fp));\n    var_dump(feof($fp));\n    echo \"===S:1,C===\\n\";\n    var_dump(fseek($fp, 1, SEEK_CUR));\n    var_dump(ftell($fp));\n    var_dump(feof($fp));\n    echo \"===S:-2,C===\\n\";\n    var_dump(fseek($fp, -2, SEEK_CUR));\n    var_dump(ftell($fp));\n    var_dump(feof($fp));\n    echo \"===S:-10,C===\\n\";\n    var_dump(fseek($fp, -10, SEEK_CUR));\n    var_dump(ftell($fp));\n    var_dump(feof($fp));\n    echo \"===S:3,S===\\n\";\n    var_dump(fseek($fp, 3, SEEK_SET));\n    var_dump(ftell($fp));\n    var_dump(feof($fp));\n    echo \"===S:10,C===\\n\";\n    var_dump(fseek($fp, 10, SEEK_CUR));\n    var_dump(ftell($fp));\n    var_dump(feof($fp));\n    echo \"===S:-1,E===\\n\";\n    var_dump(fseek($fp, -1, SEEK_END));\n    var_dump(ftell($fp));\n    var_dump(feof($fp));\n    echo \"===S:0,E===\\n\";\n    var_dump(fseek($fp, 0, SEEK_END));\n    var_dump(ftell($fp));\n    var_dump(feof($fp));\n    echo \"===S:1,E===\\n\";\n    var_dump(fseek($fp, 1, SEEK_END));\n    var_dump(ftell($fp));\n    var_dump(feof($fp));\n    fclose($fp);\n}\n?>")).toMatchSnapshot();
  });
});
