// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/standard/tests/strings/setlocale_variation2.phpt
  it("Test setlocale() function : usage variations - Setting all available locales in the platform", function () {
    expect(parser.parseCode("<?php\n/* setlocale() to set all available locales in the system and check the success count */\necho \"*** Testing setlocale() : usage variations ***\\n\";\nfunction good_locale($locale) {\n    /**\n    * Note: no_NO is a bogus locale and should not be used, see https://bugzilla.redhat.com/971416\n    **/\n    return $locale !== 'tt_RU@iqtelif.UTF-8' && $locale !== 'no_NO.ISO-8859-1';\n}\nfunction list_system_locales() {\n  // start the buffering of next command to internal output buffer\n  ob_start();\n  // run the command 'locale -a' to fetch all locales available in the system\n  system('locale -a');\n  // get the contents from the internal output buffer\n  $all_locales = ob_get_contents();\n  // fflush and end the output buffering to internal output buffer\n  ob_end_clean();\n  $system_locales = explode(\"\\n\", $all_locales);\n  // return all the locale found in the system, except for broken one\n  return array_filter($system_locales, 'good_locale');\n}\n// gather all the locales installed in the system\n$all_system_locales = list_system_locales();\n//try different locale names\n$failure_locale = array();\n$success_count = 0;\necho \"-- Test setlocale() with all available locale in the system --\\n\";\n// gather all locales installed in the system(stored $all_system_locales),\n// try n set each locale using setlocale() and keep track failures, if any\nforeach($all_system_locales as $value){\n  //set locale to $value, if success, count increments\n  if(setlocale(LC_ALL,$value )){\n   $success_count++;\n  }\n  else{\n   //failure values are put in to an array $failure_locale\n   $failure_locale[] = $value;\n  }\n}\necho \"No of locales found on the machine = \".count($all_system_locales).\"\\n\";\necho \"No of setlocale() success = \".$success_count.\"\\n\";\necho \"Expected no of failures = 0\\n\";\necho \"Test \";\n// check if there were any failure of setlocale() function earlier, if any\n// failure then dump the list of failing locales\nif($success_count != count($all_system_locales)){\n  echo \"FAILED\\n\";\n  echo \"Names of locale() for which setlocale() failed ...\\n\";\n  var_dump($failure_locale);\n}\nelse{\n  echo \"PASSED\\n\";\n}\necho \"Done\\n\";\n?>")).toMatchSnapshot();
  });
});
