// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/oci8/tests/existence_aliases.phpt
  it("Test if function aliases still exist.", function () {
    expect(parser.parseCode("<?php\nvar_dump(function_exists('ocifreecursor'));\nvar_dump(function_exists('ocibindbyname'));\nvar_dump(function_exists('ocidefinebyname'));\nvar_dump(function_exists('ocicolumnisnull'));\nvar_dump(function_exists('ocicolumnname'));\nvar_dump(function_exists('ocicolumnsize'));\nvar_dump(function_exists('ocicolumnscale'));\nvar_dump(function_exists('ocicolumnprecision'));\nvar_dump(function_exists('ocicolumntype'));\nvar_dump(function_exists('ocicolumntyperaw'));\nvar_dump(function_exists('ociexecute'));\nvar_dump(function_exists('ocicancel'));\nvar_dump(function_exists('ocifetch'));\nvar_dump(function_exists('ocifetchstatement'));\nvar_dump(function_exists('ocifreestatement'));\nvar_dump(function_exists('ocinumcols'));\nvar_dump(function_exists('ociparse'));\nvar_dump(function_exists('ocinewcursor'));\nvar_dump(function_exists('ociresult'));\nvar_dump(function_exists('ociserverversion'));\nvar_dump(function_exists('ocistatementtype'));\nvar_dump(function_exists('ocirowcount'));\nvar_dump(function_exists('ocilogoff'));\nvar_dump(function_exists('ocilogon'));\nvar_dump(function_exists('ocinlogon'));\nvar_dump(function_exists('ociplogon'));\nvar_dump(function_exists('ocierror'));\nvar_dump(function_exists('ocifreedesc'));\nvar_dump(function_exists('ocisavelob'));\nvar_dump(function_exists('ocisavelobfile'));\nvar_dump(function_exists('ociwritelobtofile'));\nvar_dump(function_exists('ociloadlob'));\nvar_dump(function_exists('ocicommit'));\nvar_dump(function_exists('ocirollback'));\nvar_dump(function_exists('ocinewdescriptor'));\nvar_dump(function_exists('ocisetprefetch'));\nvar_dump(function_exists('ocipasswordchange'));\nvar_dump(function_exists('ocifreecollection'));\nvar_dump(function_exists('ocinewcollection'));\nvar_dump(function_exists('ocicollappend'));\nvar_dump(function_exists('ocicollgetelem'));\nvar_dump(function_exists('ocicollassignelem'));\nvar_dump(function_exists('ocicollsize'));\nvar_dump(function_exists('ocicollmax'));\nvar_dump(function_exists('ocicolltrim'));\n?>")).toMatchSnapshot();
  });
});
