// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/json/tests/bug73254.phpt
  it("Bug #73254 (Incorrect indentation generated by json_encode() with JSON_PRETTY_PRINT)", function () {
    expect(parser.parseCode("<?php\necho json_encode([json_encode([1], JSON_PRETTY_PRINT)]), \"\\n\";\n$fp = fopen('php://temp', 'r');\n$data = ['a' => $fp];\necho json_encode($data), \"\\n\";\necho json_encode([json_encode([1], JSON_PRETTY_PRINT)]), \"\\n\";\n?>")).toMatchSnapshot();
  });
});
