// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/mysqli/tests/014.phpt
  it("mysqli autocommit/commit/rollback", function () {
    expect(parser.parseCode("<?php\n    require_once(\"connect.inc\");\n    $link = my_mysqli_connect($host, $user, $passwd, $db, $port, $socket);\n    if (!mysqli_autocommit($link, TRUE))\n        printf(\"[001] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    if (!mysqli_query($link, \"DROP TABLE IF EXISTS test\"))\n        printf(\"[002] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    if (!mysqli_query($link, \"CREATE TABLE test(a int, b varchar(10)) engine=InnoDB\"))\n        printf(\"[003] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    if (!mysqli_query($link, \"INSERT INTO test VALUES (1, 'foobar')\"))\n        printf(\"[004] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    if (!mysqli_autocommit($link, FALSE))\n        printf(\"[005] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    if (!mysqli_query($link, \"DELETE FROM test\"))\n        printf(\"[006] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    if (!mysqli_query($link, \"INSERT INTO test VALUES (2, 'egon')\"))\n        printf(\"[007] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    if (!mysqli_rollback($link))\n        printf(\"[008] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    if (!$result = mysqli_query($link, \"SELECT * FROM test\"))\n        printf(\"[009] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    printf(\"Num_of_rows=%d\\n\", mysqli_num_rows($result));\n    if (!$row = mysqli_fetch_row($result))\n        printf(\"[010] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    mysqli_free_result($result);\n    var_dump($row);\n    if (!mysqli_query($link, \"DELETE FROM test\"))\n        printf(\"[011] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    if (!mysqli_query($link, \"INSERT INTO test VALUES (2, 'egon')\"))\n        printf(\"[012] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    if (!mysqli_commit($link))\n        printf(\"[012] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    if (!$result = mysqli_query($link, \"SELECT * FROM test\"))\n        printf(\"[013] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    if (!$row = mysqli_fetch_row($result))\n        printf(\"[014] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    mysqli_free_result($result);\n    var_dump($row);\n    mysqli_query($link, \"DROP TABLE IF EXISTS test\");\n    mysqli_close($link);\n    print \"done!\";\n?>")).toMatchSnapshot();
  });
});
