// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/standard/tests/strings/vprintf_variation18.phpt
  it("Test vprintf() function : usage variations - scientific formats with non-scientific values", function () {
    expect(parser.parseCode("<?php\n/*\n * Test vprintf() when different scientific formats and non-scientific values are passed to\n * the '$format' and '$args' arguments of the function\n*/\necho \"*** Testing vprintf() : scientific formats and non-scientific values ***\\n\";\n// defining array of non-scientific formats\n$formats =\n    '%e %+e %-e\n    %le %4e %-4e\n    %10.4e %-10.4e %04e %04.4e\n    %\\'#2e %\\'2e %\\'$2e %\\'_2e\n    %3$e %4$e %1$e %2$e';\n// Arrays of non scientific values for the format defined in $format.\n// Each sub array contains non scientific values which correspond to each format in $format\n$args_array = array(\n  // array of float values\n  array(2.2, .2, 10.2,\n        123456.234, -1234.6789, +1234.6789,\n        20.00, +212.2, -411000000000, 2212.000000000001,\n        12345.780, 12.000000011111, -12.00000111111, -123456.234,\n        3.33, +4.44, 1.11,-2.22 ),\n  // array of strings\n  array(\" \", ' ', 'hello',\n        '123hello', '-123hello', '+123hello',\n        \"\\12345678hello\", \"-\\12345678hello\", '0123456hello', 'h123456ello',\n        \"1234hello\", \"hello\\0world\", \"NULL\", \"true\",\n        \"3\", \"4\", '1', '2'),\n  // different arrays\n  array( array(0), array(1, 2), array(-1, -1),\n         array(\"123\"), array('-123'), array(\"-123\"),\n         array(true), array(false), array(TRUE), array(FALSE),\n         array(\"123hello\"), array(\"1\", \"2\"), array('123hello'), array(12=>\"12twelve\"),\n         array(\"3\"), array(\"4\"), array(\"1\"), array(\"2\") ),\n  // array of boolean data\n  array( true, TRUE, false,\n         TRUE, FALSE, 1,\n         true, false, TRUE, FALSE,\n         0, 1, 1, 0,\n         1, TRUE, 0, FALSE),\n);\n// looping to test vprintf() with different scientific formats from the above $format array\n// and with non-scientific values from the above $args_array array\n$counter = 1;\nforeach($args_array as $args) {\n  echo \"\\n-- Iteration $counter --\\n\";\n  $result = vprintf($formats, $args);\n  echo \"\\n\";\n  var_dump($result);\n  $counter++;\n}\n?>")).toMatchSnapshot();
  });
});
