// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/mysqli/tests/mysqli_fetch_field.phpt
  it("mysqli_fetch_field()", function () {
    expect(parser.parseCode("<?php\n    require_once(\"connect.inc\");\n    // Note: no SQL type tests, internally the same function gets used as for mysqli_fetch_array() which does a lot of SQL type test\n    require('table.inc');\n    // Make sure that client, connection and result charsets are all the\n    // same. Not sure whether this is strictly necessary.\n    if (!mysqli_set_charset($link, 'utf8'))\n        printf(\"[%d] %s\\n\", mysqli_errno($link), mysqli_errno($link));\n    $charsetInfo = mysqli_get_charset($link);\n    if (!$res = mysqli_query($link, \"SELECT id AS ID, label FROM test AS TEST ORDER BY id LIMIT 1\")) {\n        printf(\"[003] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    }\n    /* ID column, binary charset */\n    $tmp = mysqli_fetch_field($res);\n    var_dump($tmp);\n    /* label column, result set charset */\n    $tmp = mysqli_fetch_field($res);\n    var_dump($tmp);\n    if ($tmp->charsetnr != $charsetInfo->number) {\n        printf(\"[004] Expecting charset %s/%d got %d\\n\",\n            $charsetInfo->charset, $charsetInfo->number, $tmp->charsetnr);\n    }\n    if ($tmp->db != $db) {\n        printf(\"011] Expecting database '%s' got '%s'\\n\",\n            $db, $tmp->db);\n    }\n    var_dump(mysqli_fetch_field($res));\n    mysqli_free_result($res);\n    // Read http://bugs.php.net/bug.php?id=42344 on defaults!\n    try {\n        mysqli_fetch_field($res);\n    } catch (Error $exception) {\n        echo $exception->getMessage() . \"\\n\";\n    }\n    if (!mysqli_query($link, \"DROP TABLE IF EXISTS test\"))\n        printf(\"[007] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    if (!mysqli_query($link, \"CREATE TABLE test(id INT NOT NULL DEFAULT 1)\"))\n        printf(\"[008] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    if (!mysqli_query($link, \"INSERT INTO test(id) VALUES (2)\"))\n        printf(\"[009] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    if (!$res = mysqli_query($link, \"SELECT id as _default_test FROM test\")) {\n        printf(\"[010] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    }\n    var_dump(mysqli_fetch_assoc($res));\n    /* binary */\n    var_dump(mysqli_fetch_field($res));\n    mysqli_free_result($res);\n    mysqli_close($link);\n    print \"done!\";\n?>")).toMatchSnapshot();
  });
});
