// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/mysqli/tests/mysqli_debug_control_string.phpt
  it("mysqli_debug() - invalid debug control strings", function () {
    expect(parser.parseCode("<?php\n    require_once('connect.inc');\n    require_once('table.inc');\n    function try_control_string($link, $control_string, $trace_file, $offset) {\n        if (true !== ($tmp = mysqli_debug($control_string))) {\n            printf(\"[%03d][control string '%s'] Expecting boolean/true, got %s/%s.\\n\",\n                $offset + 1,\n                $control_string,\n                gettype($tmp),\n                $tmp);\n            return false;\n        }\n        if (!$res = mysqli_query($link, 'SELECT * FROM test')) {\n            printf(\"[%03d][control string '%s'] [%d] %s.\\n\",\n                $offset + 2,\n                $control_string,\n                mysqli_errno($link),\n                mysqli_error($link));\n            return false;\n        }\n        clearstatcache();\n        if (!file_exists($trace_file)) {\n            printf(\"[%03d][control string '%s'] Trace file has not been written.\\n\",\n                $offset + 3,\n                $control_string,\n                gettype($tmp),\n                $tmp);\n            return false;\n        }\n        unlink($trace_file);\n    }\n    $trace_file = sprintf('%s%s%s', sys_get_temp_dir(), DIRECTORY_SEPARATOR, 'mysqli_debug_phpt.trace');\n    try_control_string($link, 't:,,:o,' . $trace_file, $trace_file, 10);\n    try_control_string($link, ':' . chr(0) . 'A,' . $trace_file, $trace_file, 20);\n    try_control_string($link, 't:o,' . $trace_file . ':abc', $trace_file, 30);\n    try_control_string($link, 't:o,' . $trace_file . ':ABC,123:b', $trace_file, 40);\n    try_control_string($link, 't:ABC,123:b;:o,' . $trace_file, $trace_file, 50);\n    try_control_string($link, 't:A;BC,123:b;:o,' . $trace_file, $trace_file, 60);\n    try_control_string($link, 't:p:o,' . $trace_file, $trace_file, 70);\n    try_control_string($link, 't:p,1,,2:o,' . $trace_file, $trace_file, 80);\n    try_control_string($link, 't:z,1,,2:o,' . $trace_file, $trace_file, 90);#\n    mysqli_close($link);\n    print \"done\";\n    if ($IS_MYSQLND)\n        print \"libmysql/DBUG package prints some debug info here.\"\n?>")).toMatchSnapshot();
  });
});
