// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/standard/tests/file/007_variation4.phpt
  it("Test fopen and fclose() functions - usage variations - \"w+\" mode", function () {
    expect(parser.parseCode("<?php\n/* Test fopen() and fclose(): Opening the file in \"w+\" mode,\n   checking for the file creation, write & read operations,\n   checking for the file pointer position,\n   checking for the file truncation when trying to open an existing file in \"w+\" mode,\n   and fclose function\n*/\n$file_path = __DIR__;\nrequire($file_path.\"/file.inc\");\ncreate_files($file_path, 1, \"text_with_new_line\", 0755, 20, \"w\", \"007_variation\", 4, \"bytes\");\n$file = $file_path.\"/007_variation4.tmp\";\n$string = \"abcdefghij\\nmnopqrst\\tuvwxyz\\n0123456789\";\necho \"*** Test fopen() & fclose() functions:  with 'w+' mode ***\\n\";\n$file_handle = fopen($file, \"w+\");  //opening the file \"w+\" mode\nvar_dump($file_handle);  //Check for the content of handle\nvar_dump( get_resource_type($file_handle) );  //Check for the type of resource\nvar_dump( ftell($file_handle) );  //Initial file pointer position, expected at the beginning of the file\nvar_dump( fwrite($file_handle, $string) );  //Check for write operation; passes; expected:size of the $string\nvar_dump( ftell($file_handle) );  //File pointer position after write operation, expected at the end of the file\nrewind($file_handle);\nvar_dump( fread($file_handle, 100) );  //Check for read operation; passes; expected: content of file\nvar_dump( ftell($file_handle) );  //File pointer position after read operation, expected at the end of the file\nvar_dump( fclose($file_handle) );  //Check for close operation on the file handle\nvar_dump( get_resource_type($file_handle) );  //Check whether resource is lost after close operation\nvar_dump( filesize($file) );  //Check for size of existing data file before opening the file in \"w+\" mode again, expected: size of content\nclearstatcache();\nfclose( fopen($file, \"w+\") );  //Opening the existing data file again in \"w+\" mode\nvar_dump( filesize($file) );  //Check for size of existing data file after opening the file in \"w+\" mode again, expected: 0 bytes\nclearstatcache();\nunlink($file);  //Deleting the file\nfclose( fopen($file, \"w+\") );  //Opening the non-existing file in \"w+\" mode, which will be created\nvar_dump( file_exists($file) );  //Check for the existence of file\necho \"*** Done ***\\n\";")).toMatchSnapshot();
  });
});
