// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/mysqli/tests/mysqli_stmt_data_seek.phpt
  it("mysqli_stmt_data_seek()", function () {
    expect(parser.parseCode("<?php\n    require_once(\"connect.inc\");\n    require('table.inc');\n    if (!$stmt = mysqli_stmt_init($link))\n        printf(\"[003] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    try {\n        mysqli_stmt_data_seek($stmt, 1);\n    } catch (Error $exception) {\n        echo $exception->getMessage() . \"\\n\";\n    }\n    if (!mysqli_stmt_prepare($stmt, \"SELECT id FROM test ORDER BY id\"))\n        printf(\"[005] [%d] %s\\n\", mysqli_stmt_errno($stmt), mysqli_stmt_error($stmt));\n    if (true !== ($tmp = mysqli_stmt_execute($stmt)))\n        printf(\"[006] Expecting boolean/true, got %s/%s\\n\", gettype($tmp), $tmp);\n    $id = null;\n    if (!mysqli_stmt_bind_result($stmt, $id))\n        printf(\"[007] [%d] %s\\n\", mysqli_stmt_errno($stmt), mysqli_stmt_error($stmt));\n    if (!mysqli_stmt_store_result($stmt))\n        printf(\"[008] [%d] %s\\n\", mysqli_stmt_errno($stmt), mysqli_stmt_error($stmt));\n    if (!is_null($tmp = mysqli_stmt_data_seek($stmt, 2)))\n        printf(\"[009] Expecting NULL, got %s/%s\\n\", gettype($tmp), $tmp);\n    if (!mysqli_stmt_fetch($stmt))\n        printf(\"[010] [%d] %s\\n\", mysqli_stmt_errno($stmt), mysqli_stmt_error($stmt));\n    var_dump($id);\n    if (!is_null($tmp = mysqli_stmt_data_seek($stmt, 0)))\n        printf(\"[011] Expecting NULL, got %s/%s\\n\", gettype($tmp), $tmp);\n    if (!mysqli_stmt_fetch($stmt))\n        printf(\"[012] [%d] %s\\n\", mysqli_stmt_errno($stmt), mysqli_stmt_error($stmt));\n    var_dump($id);\n    if (!is_null($tmp = mysqli_stmt_data_seek($stmt, mysqli_stmt_num_rows($stmt) + 100)))\n        printf(\"[013] Expecting NULL, got %s/%s\\n\", gettype($tmp), $tmp);\n    if (mysqli_stmt_fetch($stmt))\n        printf(\"[014] [%d] %s\\n\", mysqli_stmt_errno($stmt), mysqli_stmt_error($stmt));\n    var_dump($id);\n    try {\n        mysqli_stmt_data_seek($stmt, -1);\n    } catch (\\ValueError $e) {\n        echo $e->getMessage() . \\PHP_EOL;\n    }\n    if (mysqli_stmt_fetch($stmt))\n        printf(\"[016] [%d] %s\\n\", mysqli_stmt_errno($stmt), mysqli_stmt_error($stmt));\n    var_dump($id);\n    mysqli_stmt_close($stmt);\n    try {\n        mysqli_stmt_data_seek($stmt, 0);\n    } catch (Error $exception) {\n        echo $exception->getMessage() . \"\\n\";\n    }\n    mysqli_close($link);\n    print \"done!\";\n?>")).toMatchSnapshot();
  });
});
