// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/mysqli/tests/mysqli_stmt_get_warnings.phpt
  it("mysqli_stmt_get_warnings() - TODO", function () {
    expect(parser.parseCode("<?php\n    require_once(\"connect.inc\");\n    require('table.inc');\n    if (!$stmt = mysqli_stmt_init($link))\n        printf(\"[003] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    try {\n        mysqli_stmt_get_warnings($stmt);\n    } catch (Error $exception) {\n        echo $exception->getMessage() . \"\\n\";\n    }\n    if (!mysqli_stmt_prepare($stmt, \"SET sql_mode=''\") || !mysqli_stmt_execute($stmt))\n        printf(\"[005] [%d] %s\\n\", mysqli_stmt_errno($stmt), mysqli_stmt_error($stmt));\n    if (!mysqli_stmt_prepare($stmt, \"DROP TABLE IF EXISTS test\") || !mysqli_stmt_execute($stmt))\n        printf(\"[006] [%d] %s\\n\", mysqli_stmt_errno($stmt), mysqli_stmt_error($stmt));\n    if (false !== ($tmp = mysqli_stmt_get_warnings($stmt)))\n        printf(\"[007] Expecting boolean/false, got %s/%s\\n\", gettype($tmp), $tmp);\n    if (!mysqli_stmt_prepare($stmt, \"CREATE TABLE test(id SMALLINT, label CHAR(1))\") || !mysqli_stmt_execute($stmt))\n        printf(\"[008] [%d] %s\\n\", mysqli_stmt_errno($stmt), mysqli_stmt_error($stmt));\n    if (false !== ($tmp = mysqli_stmt_get_warnings($stmt)))\n        printf(\"[009] Expecting boolean/false, got %s/%s\\n\", gettype($tmp), $tmp);\n    if (!mysqli_stmt_prepare($stmt, \"INSERT INTO test(id, label) VALUES (100000, 'a'), (100001, 'b')\") ||\n        !mysqli_stmt_execute($stmt))\n        printf(\"[010] [%d] %s\\n\", mysqli_stmt_errno($stmt), mysqli_stmt_error($stmt));\n    if (!is_object($warning = mysqli_stmt_get_warnings($stmt)))\n        printf(\"[011] Expecting mysqli_warning object, got %s/%s\\n\", gettype($warning), $warning);\n    if ('mysqli_warning' !== get_class($warning))\n        printf(\"[012] Expecting object of type mysqli_warning got type '%s'\", get_class($warning));\n    if (!method_exists($warning, 'next'))\n        printf(\"[013] Object mysqli_warning seems to lack method next()\\n\");\n    $i = 0;\n    do {\n        if ('' == $warning->message)\n            printf(\"[014 - %d] Message should not be empty\\n\", $i);\n        if ('' == $warning->sqlstate)\n            printf(\"[015 - %d] SQL State should not be empty\\n\", $i);\n        if (0 == $warning->errno)\n            printf(\"[016 - %d] Error number should not be zero\\n\", $i);\n        $i++;\n    } while ($warning->next());\n    if (2 != $i)\n        printf(\"[017] Expected 2 warnings, got %d warnings\\n\", $i);\n    mysqli_stmt_close($stmt);\n    try {\n        mysqli_stmt_get_warnings($stmt);\n    } catch (Error $exception) {\n        echo $exception->getMessage() . \"\\n\";\n    }\n    mysqli_close($link);\n    print \"done!\";\n?>")).toMatchSnapshot();
  });
});
