// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/soap/tests/bugs/bug39121.phpt
  it("Bug #39121 (Incorrect return array handling in non-wsdl soap client)", function () {
    expect(parser.parseCode("<?php\nclass LocalSoapClient extends SoapClient {\n  function __doRequest($request, $location, $action, $version, $one_way = 0): ?string {\n    return <<<EOF\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:soapenc=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" soap:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">\n        <soap:Body>\n                <getDIDAreaResponse xmlns=\"http://didx.org/GetList\">\n                        <soapenc:Array soapenc:arrayType=\"xsd:string[2]\" xsi:type=\"soapenc:Array\">\n                                <item xsi:type=\"xsd:string\">StateCode</item>\n                                <item xsi:type=\"xsd:string\">description</item>\n                        </soapenc:Array>\n                        <soapenc:Array soapenc:arrayType=\"xsd:anyType[2]\" xsi:type=\"soapenc:Array\">\n                                <item xsi:type=\"xsd:int\">241</item>\n                                <item xsi:type=\"xsd:string\">Carabobo</item>\n                        </soapenc:Array>\n                        <soapenc:Array soapenc:arrayType=\"xsd:anyType[2]\" xsi:type=\"soapenc:Array\">\n                                <item xsi:type=\"xsd:int\">243</item>\n                                <item xsi:type=\"xsd:string\">Aragua and Carabobo</item>\n                        </soapenc:Array>\n                        <soapenc:Array soapenc:arrayType=\"xsd:anyType[2]\" xsi:type=\"soapenc:Array\">\n                                <item xsi:type=\"xsd:int\">261</item>\n                                <item xsi:type=\"xsd:string\">Zulia</item>\n                        </soapenc:Array>\n                </getDIDAreaResponse>\n        </soap:Body>\n</soap:Envelope>\nEOF;\n  }\n}\n$client = new LocalSoapClient(NULL, array('location'=>'test://','uri'=>'test://'));\nprint_r($client->getDIDAreaResponse());\n?>")).toMatchSnapshot();
  });
});
