// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/mysqli/tests/mysqli_real_escape_string_euckr.phpt
  it("mysqli_real_escape_string() - euckr", function () {
    expect(parser.parseCode("<?php\n    require_once(\"connect.inc\");\n    if (!$link = my_mysqli_connect($host, $user, $passwd, $db, $port, $socket))\n{\n        printf(\"[001] Cannot connect to the server using host=%s, user=%s,\npasswd=***, dbname=%s, port=%s, socket=%s - [%d] %s\\n\", $host, $user, $db,\n$port, $socket, mysqli_connect_errno(), mysqli_connect_error());\n    }\n    if (!mysqli_query($link, 'DROP TABLE IF EXISTS test')) {\n        printf(\"Failed to drop old test table: [%d] %s\\n\", mysqli_errno($link),\nmysqli_error($link));\n    }\n    if (!mysqli_query($link, 'CREATE TABLE test(id INT, label CHAR(1), PRIMARY\nKEY(id)) ENGINE=' . $engine . \" DEFAULT CHARSET=euckr\")) {\n        printf(\"Failed to create test table: [%d] %s\\n\", mysqli_errno($link),\nmysqli_error($link));\n    }\n    var_dump(mysqli_set_charset($link, \"euckr\"));\n    if ('�Ǵ뼺\\\\\\\\�Ǵ뼺' !== ($tmp = mysqli_real_escape_string($link, '�Ǵ뼺\\\\�Ǵ뼺')))\n        printf(\"[004] Expecting \\\\\\\\, got %s\\n\", $tmp);\n    if ('�Ǵ뼺\\\"�Ǵ뼺' !== ($tmp = mysqli_real_escape_string($link, '�Ǵ뼺\"�Ǵ뼺')))\n        printf(\"[005] Expecting \\\", got %s\\n\", $tmp);\n    if (\"�Ǵ뼺\\'�Ǵ뼺\" !== ($tmp = mysqli_real_escape_string($link, \"�Ǵ뼺'�Ǵ뼺\")))\n        printf(\"[006] Expecting ', got %s\\n\", $tmp);\n    if (\"�Ǵ뼺\\\\n�Ǵ뼺\" !== ($tmp = mysqli_real_escape_string($link, \"�Ǵ뼺\\n�Ǵ뼺\")))\n        printf(\"[007] Expecting \\\\n, got %s\\n\", $tmp);\n    if (\"�Ǵ뼺\\\\r�Ǵ뼺\" !== ($tmp = mysqli_real_escape_string($link, \"�Ǵ뼺\\r�Ǵ뼺\")))\n        printf(\"[008] Expecting \\\\r, got %s\\n\", $tmp);\n    if (\"�Ǵ뼺\\\\0�Ǵ뼺\" !== ($tmp = mysqli_real_escape_string($link, \"�Ǵ뼺\" . chr(0) . \"�Ǵ뼺\")))\n        printf(\"[009] Expecting %s, got %s\\n\", \"�Ǵ뼺\\\\0�Ǵ뼺\", $tmp);\n    var_dump(mysqli_query($link, \"INSERT INTO test(id, label) VALUES (100, '��')\"));\n    mysqli_close($link);\n    print \"done!\";\n?>")).toMatchSnapshot();
  });
});
