// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/mysqli/tests/mysqli_real_escape_string_nobackslash.phpt
  it("mysqli_real_escape_string() - SQL Mode NO_BACKSLASH_ESCAPE", function () {
    expect(parser.parseCode("<?php\n    require_once(\"connect.inc\");\n    require_once('table.inc');\n    if (!mysqli_query($link, 'SET @@sql_mode=\"NO_BACKSLASH_ESCAPES\"'))\n        printf(\"[001] Cannot set NO_BACKSLASH_ESCAPES, [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    if ('\\\\' !== ($tmp = mysqli_real_escape_string($link, '\\\\')))\n        printf(\"[002] Expecting \\\\, got %s\\n\", $tmp);\n    if ('\"' !== ($tmp = mysqli_real_escape_string($link, '\"')))\n        printf(\"[003] Expecting \\\", got %s\\n\", $tmp);\n    if (\"''\" !== ($tmp = mysqli_real_escape_string($link, \"'\")))\n        printf(\"[004] Expecting '', got %s\\n\", $tmp);\n    if (\"\\n\" !== ($tmp = mysqli_real_escape_string($link, \"\\n\")))\n        printf(\"[005] Expecting \\\\n, got %s\\n\", $tmp);\n    if (\"\\r\" !== ($tmp = mysqli_real_escape_string($link, \"\\r\")))\n        printf(\"[006] Expecting \\\\r, got %s\\n\", $tmp);\n    assert(\"foo\" . chr(0) . \"bar\" === \"foo\" . chr(0) . \"bar\");\n    if (\"foo\" . chr(0) . \"bar\" !== ($tmp = mysqli_real_escape_string($link, \"foo\" . chr(0) . \"bar\")))\n        printf(\"[007] Expecting %s, got %s\\n\", \"foo\" . chr(0) . \"bar\", $tmp);\n    if (!mysqli_query($link, sprintf('INSERT INTO test(id, label) VALUES (100, \"%s\")',\n            mysqli_real_escape_string($link, \"\\\\\"))))\n        printf(\"[009] Cannot INSERT, [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    if (!($res = mysqli_query($link, 'SELECT label FROM test WHERE id = 100')) ||\n            !($row = mysqli_fetch_assoc($res)))\n        printf(\"[010] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    var_dump($row);\n    mysqli_free_result($res);\n    if (!mysqli_query($link, 'SET @@sql_mode=\"\"'))\n        printf(\"[011] Cannot disable NO_BACKSLASH_ESCAPES, [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    if ('\\\\\\\\' !== ($tmp = mysqli_real_escape_string($link, '\\\\')))\n        printf(\"[012] Expecting \\\\, got %s\\n\", $tmp);\n    if (\"foo\\\\0bar\" !== ($tmp = mysqli_real_escape_string($link, \"foo\" . chr(0) . \"bar\")))\n        printf(\"[013] Expecting %s, got %s\\n\", \"foo\" . chr(0) . \"bar\", $tmp);\n    mysqli_close($link);\n    print \"done!\";\n?>")).toMatchSnapshot();
  });
});
