// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/standard/tests/array/array_change_key_case.phpt
  it("Test array_change_key_case() function", function () {
    expect(parser.parseCode("<?php\n$arrays = array (\n  array (),\n  array (0),\n  array (1),\n  array (-1),\n  array (0, 2, 3, 4, 5),\n  array (1, 2, 3, 4, 5),\n  array (\"\" => 1),\n  array (\"a\" => 1),\n  array (\"Z\" => 1),\n  array (\"one\" => 1),\n  array (\"ONE\" => 1),\n  array (\"OnE\" => 1),\n  array (\"oNe\" => 1),\n  array (\"one\" => 1, \"two\" => 2),\n  array (\"ONE\" => 1, \"two\" => 2),\n  array (\"OnE\" => 1, \"two\" => 2),\n  array (\"oNe\" => 1, \"two\" => 2),\n  array (\"one\" => 1, \"TWO\" => 2),\n  array (\"ONE\" => 1, \"TWO\" => 2),\n  array (\"OnE\" => 1, \"TWO\" => 2),\n  array (\"oNe\" => 1, \"TWO\" => 2),\n  array (\"one\" => 1, \"TwO\" => 2),\n  array (\"ONE\" => 1, \"TwO\" => 2),\n  array (\"OnE\" => 1, \"TwO\" => 2),\n  array (\"oNe\" => 1, \"TwO\" => 2),\n  array (\"one\" => 1, \"tWo\" => 2),\n  array (\"ONE\" => 1, \"tWo\" => 2),\n  array (\"OnE\" => 1, \"tWo\" => 2),\n  array (\"oNe\" => 1, \"tWo\" => 2),\n  array (\"one\" => 1, 2),\n  array (\"ONE\" => 1, 2),\n  array (\"OnE\" => 1, 2),\n  array (\"oNe\" => 1, 2),\n  array (\"ONE\" => 1, \"TWO\" => 2, \"THREE\" => 3, \"FOUR\" => \"four\"),\n  array (\"one\" => 1, \"two\" => 2, \"three\" => 3, \"four\" => \"FOUR\"),\n  array (\"ONE\" => 1, \"TWO\" => 2, \"three\" => 3, \"four\" => \"FOUR\"),\n  array (\"one\" => 1, \"two\" => 2, \"THREE\" => 3, \"FOUR\" => \"four\")\n);\necho \"*** Testing basic operations ***\\n\";\n$loop_counter = 1;\nforeach ($arrays as $item) {\n        echo \"** Iteration $loop_counter **\\n\"; $loop_counter++;\n    var_dump(array_change_key_case($item));\n    var_dump(array_change_key_case($item, CASE_UPPER));\n    var_dump(array_change_key_case($item, CASE_LOWER));\n    echo \"\\n\";\n}\necho \"end\\n\";\n?>")).toMatchSnapshot();
  });
});
