// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/mysqli/tests/mysqli_character_set_name.phpt
  it("mysqli_character_set_name(), mysql_client_encoding() [alias]", function () {
    expect(parser.parseCode("<?php\n    /* NOTE: http://bugs.mysql.com/bug.php?id=7923 makes this test fail very likely on all 4.1.x - 5.0.x! */\n    require_once(\"connect.inc\");\n    if (!$link = my_mysqli_connect($host, $user, $passwd, $db, $port, $socket))\n        printf(\"[005] Cannot connect to the server using host=%s, user=%s, passwd=***, dbname=%s, port=%s, socket=%s\\n\",\n            $host, $user, $db, $port, $socket);\n    if (!$res = mysqli_query($link, 'SELECT version() AS server_version'))\n        printf(\"[005] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    $tmp = mysqli_fetch_assoc($res);\n    mysqli_free_result($res);\n    $version = explode('.', $tmp['server_version']);\n    if (empty($version))\n        printf(\"[006] Cannot determine server version, need MySQL Server 4.1+ for the test!\\n\");\n    if ($version[0] <= 4 && $version[1] < 1)\n        printf(\"[007] Need MySQL Server 4.1+ for the test!\\n\");\n    if (!$res = mysqli_query($link, 'SELECT @@character_set_connection AS charset, @@collation_connection AS collation'))\n            printf(\"[008] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    $tmp = mysqli_fetch_assoc($res);\n    mysqli_free_result($res);\n    if (!$tmp['charset'])\n        printf(\"[009] Cannot determine current character set and collation\\n\");\n    $charset = mysqli_character_set_name($link);\n    if ($tmp['charset'] !== $charset) {\n        if ($tmp['collation'] === $charset) {\n            printf(\"[010] Could be known server bug http://bugs.mysql.com/bug.php?id=7923, collation %s instead of character set returned, expected string/%s, got %s/%s\\n\",\n            $tmp['collation'], $tmp['charset'], gettype($charset), $charset);\n        } else {\n            printf(\"[011] Expecting character set %s/%s, got %s/%s\\n\", gettype($tmp['charset']), $tmp['charset'], gettype($charset), $charset);\n        }\n    }\n    $charset2 = mysqli_character_set_name($link);\n    if ($charset2 !== $charset) {\n        printf(\"[012] Alias mysqli_character_set_name returned %s/%s, expected  %s/%s\\n\", gettype($charset2), $charset2, gettype($charset), $charset);\n    }\n    mysqli_close($link);\n    try {\n        mysqli_character_set_name($link);\n    } catch (Error $exception) {\n        echo $exception->getMessage() . \"\\n\";\n    }\n    print \"done!\";\n?>")).toMatchSnapshot();
  });
});
