// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/standard/tests/array/in_array_variation4.phpt
  it("Test in_array() function : usage variations - haystack as resource/multi dimensional array", function () {
    expect(parser.parseCode("<?php\n/* Test in_array() with haystack as resource and multidimensional arrays */\n/* checking for Resources */\necho \"*** Testing resource type with in_array() ***\\n\";\n//file type resource\n$file_handle = fopen(__FILE__, \"r\");\n//directory type resource\n$dir_handle = opendir( __DIR__ );\n//store resources in array for comparison.\n$resources = array($file_handle, $dir_handle);\n// search for resource type in the resource array\nvar_dump( in_array($file_handle, $resources, true) );\n//checking for (int) type resource\nvar_dump( in_array((int)$dir_handle, $resources, true) );\n/* Miscellenous input check  */\necho \"\\n*** Testing miscelleneos inputs with in_array() ***\\n\";\n//matching \"Good\" in array(0,\"hello\"), result:true in loose type check\nvar_dump( in_array(\"Good\", array(0,\"hello\")) );\n//false in strict mode\nvar_dump( in_array(\"Good\", array(0,\"hello\"), TRUE) );\n//matching integer 0 in array(\"this\"), result:true in loose type check\nvar_dump( in_array(0, array(\"this\")) );\n// false in strict mode\nvar_dump( in_array(0, array(\"this\")),TRUE );\n//matching string \"this\" in array(0), result:true in loose type check\nvar_dump( in_array(\"this\", array(0)) );\n// false in stric mode\nvar_dump( in_array(\"this\", array(0), TRUE) );\n//checking for type FALSE in multidimensional array with loose checking, result:false in loose type check\nvar_dump( in_array(FALSE,\n                   array(\"a\"=> TRUE, \"b\"=> TRUE,\n                         array(\"c\"=> TRUE, \"d\"=>TRUE)\n                        )\n                  )\n        );\n//matching string having integer in beginning, result:true in loose type check\nvar_dump( in_array('123abc', array(123)) );\nvar_dump( in_array('123abc', array(123), TRUE) ); // false in strict mode\necho \"Done\\n\";\n?>")).toMatchSnapshot();
  });
});
