// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/oci8/tests/refcur_prefetch_3.phpt
  it("Prefetch with Nested cursors with INI setting.", function () {
    expect(parser.parseCode("<?php\nrequire __DIR__.\"/connect.inc\";\n//Create tables here\n$stmtarray = array(\n    \"drop table nescurtest\",\n    \"create table nescurtest(c1 varchar2(10))\"\n);\noci8_test_sql_execute($c, $stmtarray);\n// Insert 500 rows into the table.\n$insert_sql = \"INSERT INTO nescurtest (c1) VALUES (:c1)\";\nif (!($s = oci_parse($c, $insert_sql))) {\n    die(\"oci_parse(insert) failed!\\n\");\n}\nfor ($i = 0; $i<=500; $i++) {\n    $val2 = 'test'.$i;\n    oci_bind_by_name($s,':c1',$val2);\n    if (!oci_execute($s)) {\n        die(\"oci_execute(insert) failed!\\n\");\n    }\n}\necho\"-----------------------------------------------\\n\";\necho \"Test with Nested Cursors\\n\";\necho\"-----------------------------------------------\\n\";\n$cur1 = oci_new_cursor($c);\n$sqlstmt = \"select cursor(select * from nescurtest) curs1 from dual\";\n$s = oci_parse($c,$sqlstmt);\noci_execute($s);\n$data = oci_fetch_array($s);\noci_execute($data['CURS1']);\n// Calculate round-trips\n$initial_rt = print_roundtrips($c);\nfor ($i = 0;$i<10;$i++) {\n    echo \"Fetch Row using Nested cursor Query\\n\";\n    var_dump(oci_fetch_row($data['CURS1']));\n}\n$cnt = (print_roundtrips($c) - $initial_rt);\necho \"Number of roundtrips made with prefetch count 5 for 10 rows is  $cnt\\n\";\nfunction  print_roundtrips($c) {\n    $sql_stmt = \"select value from v\\$mystat a,v\\$statname c where\n         a.statistic#=c.statistic# and c.name='SQL*Net roundtrips to/from client'\";\n    $s = oci_parse($c,$sql_stmt);\n    oci_define_by_name($s,\"VALUE\",$value);\n    oci_execute($s);\n    oci_fetch($s);\n    return $value;\n}\n// Clean up  here\n$stmtarray = array(\n    \"drop table nescurtest\"\n);\noci8_test_sql_execute($c, $stmtarray);\necho \"Done\\n\";\n?>")).toMatchSnapshot();
  });
});
