// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/standard/tests/file/windows_links/readlink_compat.phpt
  it("Test readlink bc behaviour on Windows", function () {
    expect(parser.parseCode("<?php\n$tmpDir = __DIR__ . '\\\\mnt';\nmkdir($tmpDir);\n// mounted volume\n$volume = trim(exec('mountvol C: /L'));\nexec(sprintf('mountvol \"%s\" %s', $tmpDir, $volume));\nvar_dump(readlink($tmpDir));\nexec(sprintf('mountvol \"%s\" /D', $tmpDir));\nmkdir($tmpDir . '\\\\test\\\\directory', 0777, true);\nchdir($tmpDir . '\\\\test');\n// junction to a volume (same as a mounted volume)\n$link = $tmpDir . '\\\\test\\\\volume_junction';\nexec(sprintf('mklink /J \"%s\" %s', $link, $volume));\nvar_dump(readlink($link));\nrmdir($link);\n// junction to a directory\n$link = $tmpDir . '\\\\test\\\\directory_junction';\n$target = $tmpDir . '\\\\test\\\\directory';\nexec(sprintf('mklink /J \"%s\" \"%s\"', $link, $target));\nvar_dump(readlink($link));\nrmdir($link);\n// symlink to a directory (absolute and relative)\n$link = $tmpDir . '\\\\test\\\\directory_symlink';\n$target = $tmpDir . '\\\\test\\\\directory';\nexec(sprintf('mklink /D \"%s\" \"%s\"', $link, $target));\nvar_dump(readlink($link));\nrmdir($link);\nexec(sprintf('mklink /D \"%s\" directory', $link));\nvar_dump(readlink($link));\nrmdir($link);\n// create a file to link to\n$filename = $tmpDir . '\\\\test\\\\directory\\\\a.php';\n$fh = fopen($filename, 'w');\nfclose($fh);\n// symlink to a file (absolute and relative)\n$link = $tmpDir . '\\\\test\\\\file_symlink';\nexec(sprintf('mklink \"%s\" \"%s\"', $link, $filename));\nvar_dump(readlink($link));\nunlink($link);\nexec(sprintf('mklink \"%s\" directory\\\\a.php', $link));\nvar_dump(readlink($link));\nunlink($link);\n// unexpected behaviour\necho \"\\n*** Unexpected behaviour when not a reparse point\\n\";\nvar_dump(readlink($tmpDir . '\\\\test\\\\directory'));\nvar_dump(readlink($filename));\nunlink($filename);\nchdir(__DIR__);\nrmdir($tmpDir . '\\\\test\\\\directory');\nrmdir($tmpDir . '\\\\test');\nrmdir($tmpDir);\n?>")).toMatchSnapshot();
  });
});
