// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/standard/tests/strings/str_ireplace.phpt
  it("str_ireplace() tests", function () {
    expect(parser.parseCode("<?php\nvar_dump(str_ireplace(\"\", \"\", \"\"));\nvar_dump(str_ireplace(\"tt\", \"a\", \"ttttTttttttttTT\"));\nvar_dump(str_ireplace(\"tt\", \"a\", \"ttttTttttttttTT\", $count));\nvar_dump($count);\nvar_dump(str_ireplace(\"tt\", \"aa\", \"ttttTttttttttTT\"));\nvar_dump(str_ireplace(\"tt\", \"aa\", \"ttttTttttttttTT\", $count));\nvar_dump($count);\nvar_dump(str_ireplace(\"tt\", \"aaa\", \"ttttTttttttttTT\"));\nvar_dump(str_ireplace(\"tt\", \"aaa\", \"ttttTttttttttTT\", $count));\nvar_dump($count);\nvar_dump(str_ireplace(\"tt\", \"aaa\", \"ttttTttttttttTT\"));\nvar_dump(str_ireplace(\"tt\", \"aaa\", \"ttttTttttttttTT\", $count));\nvar_dump($count);\nvar_dump(str_ireplace(array(\"tt\", \"tt\"), \"aaa\", \"ttttTttttttttTT\"));\nvar_dump(str_ireplace(array(\"tt\", \"tt\"), array(\"aaa\"), \"ttttTttttttttTT\"));\nvar_dump(str_ireplace(array(\"tt\", \"y\"), array(\"aaa\", \"bbb\"), \"ttttTttttttttTT\"));\nvar_dump(str_ireplace(array(\"tt\", \"tt\"), \"aaa\", \"ttttTttttttttTT\"));\nvar_dump(str_ireplace(array(\"tt\", \"tt\"), array(\"aaa\"), \"ttttTttttttttTT\"));\nvar_dump(str_ireplace(array(\"tt\", \"y\"), array(\"aaa\", \"bbb\"), \"ttttTttttttttTT\"));\nvar_dump(str_ireplace(array(\"tt\", \"y\"), array(\"aaa\", \"bbb\"), array(\"ttttTttttttttTT\", \"aayyaayasdayYahsdYYY\")));\nvar_dump(str_ireplace(array(\"tt\", \"y\"), array(\"aaa\", \"bbb\"), array(\"key\"=>\"ttttTttttttttTT\", \"test\"=>\"aayyaayasdayYahsdYYY\")));\nvar_dump(str_ireplace(array(\"t\"=>\"tt\", \"y\"=>\"y\"), array(\"a\"=>\"aaa\", \"b\"=>\"bbb\"), array(\"key\"=>\"ttttTttttttttTT\", \"test\"=>\"aayyaayasdayYahsdYYY\")));\n/* separate testcase for str_ireplace() off-by-one */\n$Data = \"Change tracking and management software designed to watch\n    for abnormal system behavior.\\nSuggest features, report bugs, or ask\n    questions here.\";\nvar_dump($Data = str_ireplace(\"\\r\\n\", \"<br>\", $Data));\nvar_dump($Data = str_ireplace(\"\\n\", \"<br>\", $Data));\necho \"Done\\n\";\n?>")).toMatchSnapshot();
  });
});
