// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/standard/tests/file/fseek_ftell_rewind_basic1.phpt
  it("Test fseek(), ftell() & rewind() functions : Basic functionality - all r and a modes", function () {
    expect(parser.parseCode("<?php\n// include the file.inc for common functions for test\ninclude (\"file.inc\");\n/* Testing fseek(),ftell(),rewind() functions on all read and append modes */\necho \"*** Testing fseek(), ftell(), rewind() : basic operations ***\\n\";\n$file_modes = array( \"r\",\"rb\",\"rt\",\"r+\",\"r+b\",\"r+t\",\n                     \"a\",\"ab\",\"at\",\"a+\",\"a+b\",\"a+t\");\n$file_content_types = array( \"text_with_new_line\",\"alphanumeric\");\n$whence_set = array(SEEK_SET,SEEK_CUR,SEEK_END);\n$whence_string = array(\"SEEK_SET\", \"SEEK_CUR\", \"SEEK_END\");\n$filename = __DIR__.\"/fseek_ftell_rewind_basic1.tmp\"; // this is name of the file created by create_files()\n  /* open the file using $files_modes and perform fseek(),ftell() and rewind() on it */\nforeach($file_content_types as $file_content_type){\n  echo \"\\n-- File having data of type \". $file_content_type .\" --\\n\";\n  foreach($file_modes as $file_mode) {\n    echo \"-- File opened in mode \".$file_mode.\" --\\n\";\n    create_files ( __DIR__, 1, $file_content_type, 0755, 512, \"w\", \"fseek_ftell_rewind_basic\"\n                      ,1,\"bytes\",\".tmp\"); //create a file with 512 bytes size\n    $file_handle = fopen($filename, $file_mode);\n    if (!$file_handle) {\n      echo \"Error: failed to fopen() file: $filename!\";\n      exit();\n    }\n    // set the file pointer to 0\n    var_dump( rewind($file_handle) ); // Confirm file pointer moves correctly\n    var_dump( ftell($file_handle) ); // confirm the file pointer position\n    foreach($whence_set as $whence){\n      echo \"-- Testing fseek() with whence = $whence_string[$whence] --\\n\";\n      var_dump( fseek($file_handle,10,$whence) ); //expecting int(0)\n      var_dump( ftell($file_handle) ); // confirm the file pointer position\n      var_dump( feof($file_handle) ); //ensure that file pointer is not at end\n    } //end of whence loop\n    //close the file and check the size\n    fclose($file_handle);\n    var_dump( filesize($filename) );\n    delete_file($filename); // delete file with name\n  } //end of file_modes loop\n} //end of file_content_types loop\necho \"Done\\n\";\n?>")).toMatchSnapshot();
  });
});
