// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/reflection/tests/ReflectionMethod_basic1.phpt
  it("ReflectionMethod class - various methods", function () {
    expect(parser.parseCode("<?php\nfunction reflectMethod($class, $method) {\n    $methodInfo = new ReflectionMethod($class, $method);\n    echo \"**********************************\\n\";\n    echo \"Reflecting on method $class::$method()\\n\\n\";\n    echo \"\\nisFinal():\\n\";\n    var_dump($methodInfo->isFinal());\n    echo \"\\nisAbstract():\\n\";\n    var_dump($methodInfo->isAbstract());\n    echo \"\\nisPublic():\\n\";\n    var_dump($methodInfo->isPublic());\n    echo \"\\nisPrivate():\\n\";\n    var_dump($methodInfo->isPrivate());\n    echo \"\\nisProtected():\\n\";\n    var_dump($methodInfo->isProtected());\n    echo \"\\nisStatic():\\n\";\n    var_dump($methodInfo->isStatic());\n    echo \"\\nisConstructor():\\n\";\n    var_dump($methodInfo->isConstructor());\n    echo \"\\nisDestructor():\\n\";\n    var_dump($methodInfo->isDestructor());\n    echo \"\\n**********************************\\n\";\n}\nclass TestClass\n{\n    public function foo() {\n        echo \"Called foo()\\n\";\n    }\n    static function stat() {\n        echo \"Called stat()\\n\";\n    }\n    private function priv() {\n        echo \"Called priv()\\n\";\n    }\n    protected function prot() {}\n    public function __destruct() {}\n}\nclass DerivedClass extends TestClass {}\ninterface TestInterface {\n    public function int();\n    public function __construct($arg);\n    public function __destruct();\n}\ntrait TestTrait {\n    public abstract function __construct();\n    public function __destruct() {\n    }\n}\nreflectMethod(\"DerivedClass\", \"foo\");\nreflectMethod(\"TestClass\", \"stat\");\nreflectMethod(\"TestClass\", \"priv\");\nreflectMethod(\"TestClass\", \"prot\");\nreflectMethod(\"DerivedClass\", \"prot\");\nreflectMethod(\"TestInterface\", \"int\");\nreflectMethod(\"ReflectionProperty\", \"__construct\");\nreflectMethod(\"TestClass\", \"__destruct\");\nreflectMethod(\"TestInterface\", \"__construct\");\nreflectMethod(\"TestInterface\", \"__destruct\");\nreflectMethod(\"TestTrait\", \"__construct\");\nreflectMethod(\"TestTrait\", \"__destruct\");\n?>")).toMatchSnapshot();
  });
});
