// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/filter/tests/039.phpt
  it("filter_var_array() and different arguments", function () {
    expect(parser.parseCode("<?php\necho \"-- (1)\\n\";\nvar_dump(filter_var_array(array()));\nvar_dump(filter_var_array(array(1,\"blah\"=>\"hoho\")));\nvar_dump(filter_var_array(array(), -1));\nvar_dump(filter_var_array(array(), 1000000));\ntry {\n    filter_var_array(array(), \"\");\n} catch (TypeError $exception) {\n    echo $exception->getMessage() . \"\\n\";\n}\necho \"-- (2)\\n\";\nvar_dump(filter_var_array(array(\"\"=>\"\"), -1));\nvar_dump(filter_var_array(array(\"\"=>\"\"), 1000000));\ntry {\n    filter_var_array(array(\"\"=>\"\"), \"\");\n} catch (TypeError $exception) {\n    echo $exception->getMessage() . \"\\n\";\n}\necho \"-- (3)\\n\";\nvar_dump(filter_var_array(array(\"aaa\"=>\"bbb\"), -1));\nvar_dump(filter_var_array(array(\"aaa\"=>\"bbb\"), 1000000));\ntry {\n    filter_var_array(array(\"aaa\"=>\"bbb\"), \"\");\n} catch (TypeError $exception) {\n    echo $exception->getMessage() . \"\\n\";\n}\necho \"-- (4)\\n\";\ntry {\n    filter_var_array(array(), new stdclass);\n} catch (TypeError $exception) {\n    echo $exception->getMessage() . \"\\n\";\n}\nvar_dump(filter_var_array(array(), array()));\nvar_dump(filter_var_array(array(), array(\"var_name\"=>1)));\nvar_dump(filter_var_array(array(), array(\"var_name\"=>-1)));\nvar_dump(filter_var_array(array(\"var_name\"=>\"\"), array(\"var_name\"=>-1)));\necho \"-- (5)\\n\";\ntry {\n    filter_var_array(array(\"var_name\"=>\"\"), array(\"var_name\"=>-1, \"asdas\"=>\"asdasd\", \"qwe\"=>\"rty\", \"\"=>\"\"));\n} catch (ValueError $exception) {\n    echo $exception->getMessage() . \"\\n\";\n}\ntry {\n    filter_var_array(array(\"asdas\"=>\"text\"), array(\"var_name\"=>-1, \"asdas\"=>\"asdasd\", \"qwe\"=>\"rty\", \"\"=>\"\"));\n} catch (ValueError $exception) {\n    echo $exception->getMessage() . \"\\n\";\n}\n$a = array(\"\"=>\"\"); $b = -1;\nvar_dump(filter_var_array($a, $b));\nvar_dump($a, $b);\n$a = array(\"\"=>\"\"); $b = 100000;\nvar_dump(filter_var_array($a, $b));\nvar_dump($a, $b);\n$a = array(\"\"=>\"\"); $b = \"\";\ntry {\n    filter_var_array($a, $b);\n} catch (TypeError $exception) {\n    echo $exception->getMessage() . \"\\n\";\n}\nvar_dump($a, $b);\necho \"Done\\n\";\n?>")).toMatchSnapshot();
  });
});
