// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/soap/tests/bug47021.phpt
  it("Bug #47021 SoapClient (SoapClient stumbles over WSDL delivered with \"Transfer-Encoding: chunked\")", function () {
    expect(parser.parseCode("<?php\nrequire __DIR__.'/../../standard/tests/http/server.inc';\nfunction chunk_body($body, $n)\n{\n    $chunks = str_split($body, $n);\n    $chunks[] = '';\n    foreach ($chunks as $k => $v) {\n        $chunks[$k] = sprintf(\"%08x\\r\\n%s\\r\\n\", strlen($v), $v);\n    }\n    return join('', $chunks);\n}\n$wsdl = file_get_contents(__DIR__.'/server030.wsdl');\n$soap = <<<EOF\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<SOAP-ENV:Envelope xmlns:SOAP-ENV=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:ns1=\"http://testuri.org\" xmlns:SOAP-ENC=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" SOAP-ENV:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\"><SOAP-ENV:Body><ns1:getItemsResponse><getItemsReturn SOAP-ENC:arrayType=\"ns1:Item[10]\" xsi:type=\"ns1:ItemArray\"><item xsi:type=\"ns1:Item\"><text xsi:type=\"xsd:string\">text0</text></item><item xsi:type=\"ns1:Item\"><text xsi:type=\"xsd:string\">text1</text></item><item xsi:type=\"ns1:Item\"><text xsi:type=\"xsd:string\">text2</text></item><item xsi:type=\"ns1:Item\"><text xsi:type=\"xsd:string\">text3</text></item><item xsi:type=\"ns1:Item\"><text xsi:type=\"xsd:string\">text4</text></item><item xsi:type=\"ns1:Item\"><text xsi:type=\"xsd:string\">text5</text></item><item xsi:type=\"ns1:Item\"><text xsi:type=\"xsd:string\">text6</text></item><item xsi:type=\"ns1:Item\"><text xsi:type=\"xsd:string\">text7</text></item><item xsi:type=\"ns1:Item\"><text xsi:type=\"xsd:string\">text8</text></item><item xsi:type=\"ns1:Item\"><text xsi:type=\"xsd:string\">text9</text></item></getItemsReturn></ns1:getItemsResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>\nEOF;\n$responses = [\n    \"data://text/plain,HTTP/1.1 200 OK\\r\\n\".\n    \"Content-Type: text/xml;charset=utf-8\\r\\n\".\n    \"Transfer-Encoding: \\t  chunked\\t \\r\\n\".\n    \"Connection: close\\r\\n\".\n    \"\\r\\n\".\n    chunk_body($wsdl, 64),\n    \"data://text/plain,HTTP/1.1 200 OK\\r\\n\".\n    \"Content-Type: text/xml;charset=utf-8\\r\\n\".\n    \"Transfer-Encoding: \\t  chunked\\t \\r\\n\".\n    \"Connection: close\\r\\n\".\n    \"\\r\\n\".\n    chunk_body($soap, 156),\n];\n['pid' => $pid, 'uri' => $uri] = http_server($responses);\n$options = [\n    'trace' => true,\n    'location' => $uri,\n];\nclass BugSoapClient extends SoapClient\n{\n    public function __doRequest($request, $location, $action, $version, $one_way = null): ?string\n    {\n        $response = parent::__doRequest($request, $location, $action, $version, $one_way);\n        var_dump(strlen($response));\n        return $response;\n    }\n}\n$client = new BugSoapClient($uri, $options);\nvar_dump(count($client->getItems()));\nhttp_server_kill($pid);")).toMatchSnapshot();
  });
});
