// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/standard/tests/strings/default_charset.phpt
  it("default_charset and htmlentities/htmlspecialchars/html_entity_decode", function () {
    expect(parser.parseCode("<?php\necho \"*** Default php.ini value ***\\n\";\nvar_dump(ini_get('default_charset'),\n         ini_get('internal_encoding'),\n         ini_get('input_encoding'),\n         ini_get('output_encoding')\n    );\necho \"*** Runtime change of default_charset ***\\n\";\nvar_dump(ini_set('default_charset', 'cp1252'));\necho \"*** Test with updated default_charset ***\\n\";\nvar_dump(ini_get('default_charset'),\n         ini_get('internal_encoding'),\n         ini_get('input_encoding'),\n         ini_get('output_encoding')\n    );\nvar_dump(htmlentities(\"\\xA3\", ENT_HTML5));\nvar_dump(htmlentities(\"\\xA3\", ENT_HTML5, 'cp1252'));\nvar_dump(bin2hex(html_entity_decode(\"&pound;\", ENT_HTML5)));\nvar_dump(bin2hex(html_entity_decode(\"&pound;\", ENT_HTML5, 'cp1252')));\n// Set internal_encoding to empty and try again\necho \"*** Change internal_encoding to empty ***\\n\";\nvar_dump(ini_set('internal_encoding', ''));\nvar_dump(ini_get('default_charset'),\n         ini_get('internal_encoding'),\n         ini_get('input_encoding'),\n         ini_get('output_encoding')\n    );\nvar_dump(htmlentities(\"\\xA3\", ENT_HTML5));\nvar_dump(htmlentities(\"\\xA3\", ENT_HTML5, 'cp1252'));\nvar_dump(bin2hex(html_entity_decode(\"&pound;\", ENT_HTML5)));\nvar_dump(bin2hex(html_entity_decode(\"&pound;\", ENT_HTML5, 'cp1252')));\necho \"*** Update input/output_encoding ***\\n\";\nvar_dump(ini_set('input_encoding', 'ISO-8859-1'));\nvar_dump(ini_set('output_encoding', 'ISO-8859-1'));\nvar_dump(ini_get('default_charset'),\n         ini_get('internal_encoding'),\n         ini_get('input_encoding'),\n         ini_get('output_encoding')\n    );\n// Should not be affected\nvar_dump(htmlentities(\"\\xA3\", ENT_HTML5));\nvar_dump(htmlentities(\"\\xA3\", ENT_HTML5, 'cp1252'));\nvar_dump(bin2hex(html_entity_decode(\"&pound;\", ENT_HTML5)));\nvar_dump(bin2hex(html_entity_decode(\"&pound;\", ENT_HTML5, 'cp1252')));\necho \"Done\\n\";\n?>")).toMatchSnapshot();
  });
});
