// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/standard/tests/strings/basename_variation.phpt
  it("Test basename() function : usage variations", function () {
    expect(parser.parseCode("<?php\n$file_path_variations = array (\n  /* paths with shortcut home dir char, with suffix variation */\n  array(\"~/home/user/bar\"),\n  array(\"~/home/user/bar\", \"\"),\n  array(\"~/home/user/bar\", ' '),\n  array(\"~/home/user/bar.tar\", \".tar\"),\n  array(\"~/home/user/bar.tar\", \"~\"),\n  array(\"~/home/user/bar.tar/\", \"~\"),\n  array(\"~/home/user/bar.tar/\", \"\"),\n  array(\"~/home/user/bar.tar\", ''),\n  array(\"~/home/user/bar.tar\", \" \"),\n  /* paths with hostname:dir notation, with suffix variation */\n  array(\"hostname:/home/usr/bar.tar\"),\n  array(\"hostname:/home/user/bar.tar\", \"home\"),\n  array(\"hostname:/home/user/tbar.gz\", \"bar.gz\"),\n  array(\"hostname:/home/user/tbar.gz\", \"/bar.gz\"),\n  array(\"hostname:/home/user/tbar.gz\", \"/bar.gz/\"),\n  array(\"hostname:/home/user/tbar.gz/\", \"/bar.gz/\"),\n  array(\"hostname:/home/user/tbar.gz/\", \"/bar.gz/\"),\n  array(\"hostname:/home/user/My Pics.gz/\", \"/bar.gz/\"),\n  array(\"hostname:/home/user/My Pics.gz/\", \"Pics.gz/\"),\n  array(\"hostname:/home/user/My Pics.gz/\", \"Pics.gz\"),\n  array(\"hostname:/home/user/My Pics.gz/\", \".gz\"),\n  array(\"hostname:/home/user/My Pics.gz/\"),\n  array(\"hostname:/home/user/My Pics.gz/\", ' '),\n  array(\"hostname:/home/user/My Pics.gz/\", ''),\n  array(\"hostname:/home/user/My Pics.gz/\", \"My Pics.gz\"),\n  /* paths with numeirc strings */\n  array(\"10.5\"),\n  array(\"10.5\", \".5\"),\n  array(\"10.5\", \"10.5\"),\n  array(\"10\"),\n  array(\"105\", \"5\"),\n  array(\"/10.5\"),\n  array(\"10.5/\"),\n  array(\"10/10.gz\"),\n  array(\"0\"),\n  array('0'),\n  /* paths and suffix given as same */\n  array(\"bar.gz\", \"bar.gz\"),\n  array(\"/bar.gz\", \"/bar.gz\"),\n  array(\"/bar.gz/\", \"/bar.gz/\"),\n  array(\" \", \" \"),\n  array(' ', ' '),\n  /* path with spaces */\n  array(\" \"),\n  array(' '),\n  /* empty paths */\n  array(\"\"),\n  array(''),\n);\nfunction check_basename( $path_arrays ) {\n   $loop_counter = 1;\n   foreach ($path_arrays as $path) {\n     echo \"\\n--Iteration $loop_counter--\\n\"; $loop_counter++;\n     if( 1 == count($path) ) { // no suffix provided\n       var_dump( basename($path[0]) );\n     } else { // path as well as suffix provided,\n       var_dump( basename($path[0], $path[1]) );\n     }\n   }\n}\necho \"*** Testing possible variations in path and suffix ***\\n\";\ncheck_basename( $file_path_variations );\necho \"Done\\n\";\n?>")).toMatchSnapshot();
  });
});
