// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/soap/tests/custom_content_type.phpt
  it("SOAP customized Content-Type, eg. SwA use case", function () {
    expect(parser.parseCode("<?php\ninclude __DIR__ . \"/../../../sapi/cli/tests/php_cli_server.inc\";\n$args = substr(PHP_OS, 0, 3) == 'WIN'\n    ? [\"-d\", \"extension_dir=\" . ini_get(\"extension_dir\"), \"-d\", \"extension=php_soap.dll\"] : [];\n$code = <<<'PHP'\n/* Receive */\n$content = trim(file_get_contents(\"php://input\")) . PHP_EOL;\nPHP;\nphp_cli_server_start($code, null, $args);\n$client = new soapclient(NULL, [\n  'location' => 'http://' . PHP_CLI_SERVER_ADDRESS,\n  'uri' => 'misc-uri',\n  'soap_version' => SOAP_1_2,\n  'user_agent' => 'Vincent JARDIN, test headers',\n  'trace' => true, /* record the headers before sending */\n  'stream_context' => stream_context_create([\n    'http' => [\n      'header' => sprintf(\"MIME-Version: 1.0\\r\\n\"),\n      'content_type' => sprintf(\"Multipart/Related\")\n    ],\n  ]),\n]);\n$client->__soapCall(\"foo\", [ 'arg1' => \"XXXbar\"]);\n$headers = $client->__getLastRequestHeaders();\nif (strpos($headers, 'Multipart/Related; action=\"misc-uri#foo\"') === FALSE)\n  printf(\"Content-Type NOK %s\" . PHP_EOL, $headers);\nelse\n  printf(\"Content-Type OK\" . PHP_EOL);\n/*\n * In case of an empty content-type, let's fallback to the default content.\n */\n$client2 = new soapclient(NULL, [\n  'location' => 'http://' . PHP_CLI_SERVER_ADDRESS,\n  'uri' => 'misc-uri',\n  'soap_version' => SOAP_1_2,\n  'user_agent' => 'Vincent JARDIN, test headers',\n  'trace' => true, /* record the headers before sending */\n  'stream_context' => stream_context_create([\n    'http' => [\n      'header' => sprintf(\"MIME-Version: 1.0\\r\\n\"),\n      'content_type' => sprintf(\"\")\n    ],\n  ]),\n]);\n$client2->__soapCall(\"foo\", [ 'arg1' => \"XXXbar\"]);\n$headers = $client2->__getLastRequestHeaders();\nif (strpos($headers, 'Content-Type: application/soap+xml; charset=utf-8; action=\"misc-uri#foo\"') === FALSE)\n  printf(\"Content-Type Default NOK %s\" . PHP_EOL, $headers);\nelse\n  printf(\"Content-Type Default OK\" . PHP_EOL);\n?>")).toMatchSnapshot();
  });
});
