// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/mysqli/tests/mysqli_real_escape_string_eucjpms.phpt
  it("mysqli_real_escape_string() - eucjpms", function () {
    expect(parser.parseCode("<?php\nrequire_once(\"connect.inc\");\n    if (!$link = my_mysqli_connect($host, $user, $passwd, $db, $port, $socket))\n{\n        printf(\"[001] Cannot connect to the server using host=%s, user=%s,\npasswd=***, dbname=%s, port=%s, socket=%s - [%d] %s\\n\", $host, $user, $db,\n$port, $socket, mysqli_connect_errno(), mysqli_connect_error());\n    }\n    if (!mysqli_query($link, 'DROP TABLE IF EXISTS test')) {\n        printf(\"Failed to drop old test table: [%d] %s\\n\", mysqli_errno($link),\nmysqli_error($link));\n    }\n    if (!mysqli_query($link, 'CREATE TABLE test(id INT, label CHAR(1), PRIMARY\nKEY(id)) ENGINE=' . $engine . \" DEFAULT CHARSET=eucjpms\")) {\n        printf(\"Failed to create test table: [%d] %s\\n\", mysqli_errno($link),\nmysqli_error($link));\n    }\n    var_dump(mysqli_set_charset($link, \"eucjpms\"));\n    if ('�����Ȥ߹�碌�Ǥ�\\\\\\\\�����Ȥ߹�碌�Ǥ�' !== ($tmp = mysqli_real_escape_string($link, '�����Ȥ߹�碌�Ǥ�\\\\�����Ȥ߹�碌�Ǥ�')))\n        printf(\"[004] Expecting \\\\\\\\, got %s\\n\", $tmp);\n    if ('�����Ȥ߹�碌�Ǥ�\\\"�����Ȥ߹�碌�Ǥ�' !== ($tmp = mysqli_real_escape_string($link, '�����Ȥ߹�碌�Ǥ�\"�����Ȥ߹�碌�Ǥ�')))\n        printf(\"[005] Expecting \\\", got %s\\n\", $tmp);\n    if (\"�����Ȥ߹�碌�Ǥ�\\'�����Ȥ߹�碌�Ǥ�\" !== ($tmp = mysqli_real_escape_string($link, \"�����Ȥ߹�碌�Ǥ�'�����Ȥ߹�碌�Ǥ�\")))\n        printf(\"[006] Expecting ', got %s\\n\", $tmp);\n    if (\"�����Ȥ߹�碌�Ǥ�\\\\n�����Ȥ߹�碌�Ǥ�\" !== ($tmp = mysqli_real_escape_string($link, \"�����Ȥ߹�碌�Ǥ�\\n�����Ȥ߹�碌�Ǥ�\")))\n        printf(\"[007] Expecting \\\\n, got %s\\n\", $tmp);\n    if (\"�����Ȥ߹�碌�Ǥ�\\\\r�����Ȥ߹�碌�Ǥ�\" !== ($tmp = mysqli_real_escape_string($link, \"�����Ȥ߹�碌�Ǥ�\\r�����Ȥ߹�碌�Ǥ�\")))\n        printf(\"[008] Expecting \\\\r, got %s\\n\", $tmp);\n    if (\"�����Ȥ߹�碌�Ǥ�\\\\0�����Ȥ߹�碌�Ǥ�\" !== ($tmp = mysqli_real_escape_string($link, \"�����Ȥ߹�碌�Ǥ�\" . chr(0) . \"�����Ȥ߹�碌�Ǥ�\")))\n        printf(\"[009] Expecting %s, got %s\\n\", \"�����Ȥ߹�碌�Ǥ�\\\\0�����Ȥ߹�碌�Ǥ�\", $tmp);\n    var_dump(mysqli_query($link, \"INSERT INTO test(id, label) VALUES (100, '��')\"));\n    mysqli_close($link);\n    print \"done!\";\n?>")).toMatchSnapshot();
  });
});
