// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/standard/tests/general_functions/parse_ini_file.phpt
  it("parse_ini_file() multiple calls", function () {
    expect(parser.parseCode("<?php\n$filename = __DIR__.\"/parse_ini_file.dat\";\n@unlink($filename); /* Make sure the file really does not exist! */\nvar_dump(parse_ini_file($filename));\nvar_dump(parse_ini_file($filename, true));\n$ini = \"\ntest =\n\";\nfile_put_contents($filename, $ini);\nvar_dump(parse_ini_file($filename));\n$ini = \"\ntest==\n\";\nfile_put_contents($filename, $ini);\nvar_dump(parse_ini_file($filename));\n$ini = \"\ntest=test=\n\";\nfile_put_contents($filename, $ini);\nvar_dump(parse_ini_file($filename));\n$ini = \"\ntest= \\\"new\nline\\\"\n\";\nfile_put_contents($filename, $ini);\nvar_dump(parse_ini_file($filename));\ndefine(\"TEST_CONST\", \"test const value\");\n$ini = \"\ntest=TEST_CONST\n\";\nfile_put_contents($filename, $ini);\nvar_dump(parse_ini_file($filename));\n$ini = \"\n[section]\ntest=hello\n\";\nfile_put_contents($filename, $ini);\nvar_dump(parse_ini_file($filename, true));\n$ini = \"\n[section]\ntest=hello\n\";\nfile_put_contents($filename, $ini);\nvar_dump(parse_ini_file($filename, false));\n$ini = \"\nsection.test=hello\n\";\nfile_put_contents($filename, $ini);\nvar_dump(parse_ini_file($filename, true));\n$ini = \"\n[section]\nsection.test=hello\n\";\nfile_put_contents($filename, $ini);\nvar_dump(parse_ini_file($filename, true));\n$ini = \"\n[section]\n1=2\n\";\nfile_put_contents($filename, $ini);\nvar_dump(parse_ini_file($filename, true));\n$ini = \"\n1=2\n\";\nfile_put_contents($filename, $ini);\nvar_dump(parse_ini_file($filename, true));\n$ini = \"\ntest=test2\ntest=test3\ntest=test4\n\";\nfile_put_contents($filename, $ini);\nvar_dump(parse_ini_file($filename, true));\n/* From bug #44574 */\n$ini = \"[section1]\\nname = value\";\nfile_put_contents($filename, $ini);\nvar_dump(parse_ini_file($filename, true));\n/* #44842, labels starting with underscore */\n$ini = <<<'INI'\nfoo=bar1\n_foo=bar2\nfoo_=bar3\nINI;\nfile_put_contents($filename, $ini);\nvar_dump(parse_ini_file($filename, true));\n/* #44575, comments starting with '#' */\n$ini = <<<'INI'\nfoo=bar1\n; comment\n_foo=bar2\n; comment\nfoo_=bar3\nINI;\nfile_put_contents($filename, $ini);\nvar_dump(parse_ini_file($filename, true));\n@unlink($filename);\necho \"Done\\n\";\n?>")).toMatchSnapshot();
  });
});
