// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/mysqli/tests/015.phpt
  it("mysqli autocommit/commit/rollback with innodb", function () {
    expect(parser.parseCode("<?php\n    require_once(\"connect.inc\");\n    $link = my_mysqli_connect($host, $user, $passwd, $db, $port, $socket);\n    if (!$link)\n        printf(\"[001] Cannot connect, [%d] %s\\n\", mysqli_connect_errno(), mysqli_connect_error());\n    if (!mysqli_select_db($link, $db))\n        printf(\"[002] Cannot select DB '%s', [%d] %s\\n\", $db,\n            mysqli_errno($link), mysqli_error($link));\n    if (!mysqli_autocommit($link, TRUE))\n        printf(\"[003] Cannot turn on autocommit mode, [%d] %s\\n\",\n            mysqli_errno($link), mysqli_error($link));\n    if (!mysqli_query($link,\"DROP TABLE IF EXISTS test\") ||\n        !mysqli_query($link,\"CREATE TABLE test(a int, b varchar(10)) Engine=InnoDB\") ||\n        !mysqli_query($link, \"INSERT INTO test VALUES (1, 'foobar')\"))\n        printf(\"[004] Cannot create test data, [%d] %s\\n\",\n            mysqli_errno($link), mysqli_error($link));\n    if (!mysqli_autocommit($link, FALSE))\n        printf(\"[005] Cannot turn off autocommit mode, [%d] %s\\n\",\n            mysqli_errno($link), mysqli_error($link));\n    if (!mysqli_query($link, \"DELETE FROM test\") ||\n            !mysqli_query($link, \"INSERT INTO test VALUES (2, 'egon')\"))\n        printf(\"[006] Cannot modify test data, [%d] %s\\n\",\n            mysqli_errno($link), mysqli_error($link));\n    if (!mysqli_rollback($link))\n        printf(\"[007] Cannot call rollback, [%d] %s\\n\",\n            mysqli_errno($link), mysqli_error($link));\n    $result = mysqli_query($link, \"SELECT SQL_NO_CACHE * FROM test\");\n    if (!$result)\n        printf(\"[008] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    $row = mysqli_fetch_row($result);\n    mysqli_free_result($result);\n    var_dump($row);\n    if (!mysqli_query($link, \"DELETE FROM test\") ||\n            !mysqli_query($link, \"INSERT INTO test VALUES (2, 'egon')\"))\n        printf(\"[009] Cannot modify test data, [%d] %s\\n\",\n            mysqli_errno($link), mysqli_error($link));\n    mysqli_commit($link);\n    $result = mysqli_query($link, \"SELECT * FROM test\");\n    if (!$result)\n        printf(\"[010] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    $row = mysqli_fetch_row($result);\n    mysqli_free_result($result);\n    var_dump($row);\n    mysqli_query($link, \"DROP TABLE IF EXISTS test\");\n    mysqli_close($link);\n    print \"done!\";\n?>")).toMatchSnapshot();
  });
});
