// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/openssl/tests/streams_crypto_method.phpt
  it("Specific crypto method for ssl:// transports.", function () {
    expect(parser.parseCode("<?php\n$certFile = __DIR__ . DIRECTORY_SEPARATOR . 'streams_crypto_method.pem.tmp';\n$serverCode = <<<'CODE'\n    $serverUri = \"ssl://127.0.0.1:64321\";\n    $serverFlags = STREAM_SERVER_BIND | STREAM_SERVER_LISTEN;\n    $serverCtx = stream_context_create(['ssl' => [\n        'local_cert' => '%s',\n    ]]);\n    $server = stream_socket_server($serverUri, $errno, $errstr, $serverFlags, $serverCtx);\n    phpt_notify();\n    $client = @stream_socket_accept($server);\n    if ($client) {\n        $in = '';\n        while (!preg_match('/\\r?\\n\\r?\\n/', $in)) {\n            $in .= fread($client, 2048);\n        }\n        $response = \"HTTP/1.0 200 OK\\r\\n\"\n                  . \"Content-Type: text/plain\\r\\n\"\n                  . \"Content-Length: 12\\r\\n\"\n                  . \"Connection: close\\r\\n\"\n                  . \"\\r\\n\"\n                  . \"Hello World!\";\n        fwrite($client, $response);\n        fclose($client);\n    }\nCODE;\n$serverCode = sprintf($serverCode, $certFile);\n$clientCode = <<<'CODE'\n    $serverUri = \"https://127.0.0.1:64321/\";\n    $clientFlags = STREAM_CLIENT_CONNECT;\n    $clientCtx = stream_context_create(['ssl' => [\n        'crypto_method' => STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT,\n        'verify_peer' => false,\n        'verify_peer_name' => false\n    ]]);\n    phpt_wait();\n    echo file_get_contents($serverUri, false, $clientCtx);\nCODE;\ninclude 'CertificateGenerator.inc';\n$certificateGenerator = new CertificateGenerator();\n$certificateGenerator->saveNewCertAsFileWithKey('streams_crypto_method', $certFile);\ninclude 'ServerClientTestCase.inc';\nServerClientTestCase::getInstance()->run($clientCode, $serverCode);\n?>")).toMatchSnapshot();
  });
});
