// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/standard/tests/file/is_executable_variation1.phpt
  it("Test is_executable() function: usage variations - diff. path notations", function () {
    expect(parser.parseCode("<?php\n/* test is_executable() with file having different filepath notation */\nrequire __DIR__.'/file.inc';\necho \"*** Testing is_executable(): usage variations ***\\n\";\n$file_path = __DIR__;\nmkdir(\"$file_path/is_executable_variation1\");\n// create a new temporary file\n$fp = fopen(\"$file_path/is_executable_variation1/bar.tmp\", \"w\");\nfclose($fp);\n/* array of files checked to see if they are executable files\n   using is_executable() function */\n$files_arr = array(\n  \"$file_path/is_executable_variation1/bar.tmp\",\n  /* Testing a file with trailing slash */\n  \"$file_path/is_executable_variation1/bar.tmp/\",\n  /* Testing file with double slashes */\n  \"$file_path/is_executable_variation1//bar.tmp\",\n  \"$file_path/is_executable_variation1/*.tmp\",\n  \"$file_path/is_executable_variation1/b*.tmp\",\n  /* Testing Binary safe */\n  \"$file_path/is_executable_variation1\".chr(0).\"bar.temp\",\n  \"$file_path\".chr(0).\"is_executable_variation1/bar.temp\",\n  \"$file_path/is_executable_variation1x000/\",\n  /* Testing directories */\n  \".\",  // current directory, exp: bool(true)\n  \"$file_path/is_executable_variation1\"  // temp directory, exp: bool(true)\n);\n$counter = 1;\n/* loop through to test each element in the above array\n   is an executable file */\nforeach($files_arr as $file) {\n  echo \"-- Iteration $counter --\\n\";\n  try {\n    var_dump( is_executable($file) );\n  } catch (Error $e) {\n    echo $e->getMessage(), \"\\n\";\n  }\n  $counter++;\n  clearstatcache();\n}\necho \"Done\\n\";\n?>")).toMatchSnapshot();
  });
});
