// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/dom/tests/canonicalization.phpt
  it("Test: Canonicalization - C14N()", function () {
    expect(parser.parseCode("<?php\n$xml = <<<EOXML\n<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>\n<foo xmlns=\"http://www.example.com/ns/foo\"\n     xmlns:fubar=\"http://www.example.com/ns/fubar\" xmlns:test=\"urn::test\"><contain>\n  <bar><test1 /></bar>\n  <bar><test2 /></bar>\n  <fubar:bar xmlns:fubar=\"http://www.example.com/ns/fubar\"><test3 /></fubar:bar>\n  <fubar:bar><test4 /></fubar:bar>\n<!-- this is a comment -->\n</contain>\n</foo>\nEOXML;\n$dom = new DOMDocument();\n$dom->loadXML($xml);\n$doc = $dom->documentElement->firstChild;\n/* inclusive/without comments first child element of doc element is context. */\necho $doc->C14N().\"\\n\\n\";\n/* exclusive/without comments first child element of doc element is context. */\necho $doc->c14N(TRUE).\"\\n\\n\";\n/* inclusive/with comments first child element of doc element is context. */\necho $doc->C14N(FALSE, TRUE).\"\\n\\n\";\n/* exclusive/with comments first child element of doc element is context. */\necho $doc->C14N(TRUE, TRUE).\"\\n\\n\";\n/* exclusive/without comments using xpath query. */\necho $doc->c14N(TRUE, FALSE, array('query'=>'(//. | //@* | //namespace::*)')).\"\\n\\n\";\n/* exclusive/without comments first child element of doc element is context.\n   using xpath query with registered namespace.\n   test namespace prefix is also included. */\necho $doc->c14N(TRUE, FALSE,\n                array('query'=>'(//a:contain | //a:bar | .//namespace::*)',\n                      'namespaces'=>array('a'=>'http://www.example.com/ns/foo')),\n                array('test')).\"\\n\\n\";\n/* exclusive/without comments first child element of doc element is context.\n   test namespace prefix is also included */\necho $doc->C14N(TRUE, FALSE, NULL, array('test'));\n?>")).toMatchSnapshot();
  });
});
