// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/mysqli/tests/mysqli_debug_append.phpt
  it("mysqli_debug() - append to trace file", function () {
    expect(parser.parseCode("<?php\n    require_once('connect.inc');\n    if (true !== ($tmp = mysqli_debug(sprintf('d:t:O,%s/mysqli_debug_phpt.trace', sys_get_temp_dir()))))\n        printf(\"[001] Expecting boolean/true, got %s/%s\\n\", gettype($tmp), $tmp);\n    // table.inc will create a database connection and run some SQL queries, therefore\n    // the debug file should have entries\n    require_once('table.inc');\n    clearstatcache();\n    $trace_file = sprintf('%s/mysqli_debug_phpt.trace', sys_get_temp_dir());\n    if (!file_exists($trace_file))\n        printf(\"[002] Trace file '%s' has not been created\\n\", $trace_file);\n    if (filesize($trace_file) < 50)\n        printf(\"[003] Trace file '%s' is very small. filesize() reports only %d bytes. Please check.\\n\",\n            $trace_file,\n            filesize($trace_file));\n    // will mysqli_debug() mind if the trace file gets removed?\n    unlink($trace_file);\n    clearstatcache();\n    if (!$fp = fopen($trace_file, 'w')) {\n        printf(\"[004] Cannot create trace file to test append mode\\n\");\n    } else {\n        if (!fwrite($fp, 'mysqli_debug.phpt test line'))\n            printf(\"[005] Cannot write to trace file.\\n\");\n        fclose($fp);\n        if (true !== ($tmp = mysqli_debug(sprintf('d:a,%s', $trace_file))))\n            printf(\"[006] Expecting boolean/true, got %s/%s\\n\", gettype($tmp), $tmp);\n        if (!$res = mysqli_query($link, 'SELECT * FROM test'))\n            printf(\"[007] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n        else\n            mysqli_free_result($res);\n        $trace = file_get_contents($trace_file);\n        if (!strstr($trace, 'mysqli_debug.phpt test line'))\n            printf(\"[008] Cannot find original file content any more. Seems that the trace file got overwritten and not appended. Please check.\");\n        if (true !== ($tmp = mysqli_debug(sprintf('d:A,%s', $trace_file))))\n            printf(\"[009] Expecting boolean/true, got %s/%s\\n\", gettype($tmp), $tmp);\n        if (!$res = mysqli_query($link, 'SELECT * FROM test'))\n            printf(\"[010] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n        else\n            mysqli_free_result($res);\n        if (!strstr(file_get_contents($trace_file), $trace))\n            printf(\"[011] Cannot find original file content any more. Seems that the trace file got overwritten and not appended. Please check.\");\n    }\n    // what will happen if we create new trace entries...?\n    unlink($trace_file);\n    clearstatcache();\n    if (file_exists($trace_file))\n        printf(\"[012] Could not remove trace file '%s'.\\n\", $trace_file);\n    mysqli_close($link);\n    print \"done\";\n    if ($IS_MYSQLND)\n        print \"libmysql/DBUG package prints some debug info here.\"\n?>")).toMatchSnapshot();
  });
});
