// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/filter/tests/filter_data.phpt
  it("Simple filter_var() tests", function () {
    expect(parser.parseCode("<?php\n/* Integer */\n$data = \"-123\";   var_dump(filter_var($data, FILTER_VALIDATE_INT));\n$data = \"0\";      var_dump(filter_var($data, FILTER_VALIDATE_INT));\n$data = \"-0\";     var_dump(filter_var($data, FILTER_VALIDATE_INT));\n$data = \"+0\";     var_dump(filter_var($data, FILTER_VALIDATE_INT));\n$data = \"123\";    var_dump(filter_var($data, FILTER_VALIDATE_INT));\n$data = -123;     var_dump(filter_var($data, FILTER_VALIDATE_INT));\n$data = 0;        var_dump(filter_var($data, FILTER_VALIDATE_INT));\n$data = -0;        var_dump(filter_var($data, FILTER_VALIDATE_INT));\n$data = +0;        var_dump(filter_var($data, FILTER_VALIDATE_INT));\n$data = 123;      var_dump(filter_var($data, FILTER_VALIDATE_INT));\n$data = \"\";       var_dump(filter_var($data, FILTER_VALIDATE_INT));\necho \"\\n\";\n/* Float */\n$data = \"-0.123\"; var_dump(filter_var($data, FILTER_VALIDATE_FLOAT));\n$data = \"0.00\";   var_dump(filter_var($data, FILTER_VALIDATE_FLOAT));\n$data = \"1.23\";   var_dump(filter_var($data, FILTER_VALIDATE_FLOAT));\n$data = -1.23;    var_dump(filter_var($data, FILTER_VALIDATE_FLOAT));\n$data = 0.0;      var_dump(filter_var($data, FILTER_VALIDATE_FLOAT));\n$data = 1.23;     var_dump(filter_var($data, FILTER_VALIDATE_FLOAT));\n$data = \"\";       var_dump(filter_var($data, FILTER_VALIDATE_FLOAT));\necho \"\\n\";\n/* Boolean */\n$data = \"on\";     var_dump(filter_var($data, FILTER_VALIDATE_BOOLEAN));\n$data = \"off\";    var_dump(filter_var($data, FILTER_VALIDATE_BOOLEAN));\n$data = \"yes\";    var_dump(filter_var($data, FILTER_VALIDATE_BOOLEAN));\n$data = \"no\";     var_dump(filter_var($data, FILTER_VALIDATE_BOOLEAN));\n$data = \"true\";   var_dump(filter_var($data, FILTER_VALIDATE_BOOLEAN));\n$data = \"false\";  var_dump(filter_var($data, FILTER_VALIDATE_BOOLEAN));\n$data = \"1\";      var_dump(filter_var($data, FILTER_VALIDATE_BOOLEAN));\n$data = \"0\";      var_dump(filter_var($data, FILTER_VALIDATE_BOOLEAN));\n$data = 1;        var_dump(filter_var($data, FILTER_VALIDATE_BOOLEAN));\n$data = 0;        var_dump(filter_var($data, FILTER_VALIDATE_BOOLEAN));\n$data = true;     var_dump(filter_var($data, FILTER_VALIDATE_BOOLEAN));\n$data = false;    var_dump(filter_var($data, FILTER_VALIDATE_BOOLEAN));\n$data = \"\";       var_dump(filter_var($data, FILTER_VALIDATE_BOOLEAN));\n?>")).toMatchSnapshot();
  });
});
