// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/mysqli/tests/mysqli_options_init_command.phpt
  it("mysqli_options()", function () {
    expect(parser.parseCode("<?php\n    /* see mysqli.c for details */\n    require_once(\"connect.inc\");\n    if (!($link = my_mysqli_connect($host, $user, $passwd, $db, $port, $socket)))\n        printf(\"[001] Cannot connect to the server using host=%s, user=%s, passwd=***, dbname=%s, port=%s, socket=%s\\n\",\n            $host, $user, $db, $port, $socket);\n    /* TODO: test more options */\n    if (!mysqli_query($link, \"DROP TABLE IF EXISTS test\") ||\n        !mysqli_query($link, sprintf(\"CREATE TABLE test(id INT) ENGINE = %s\\n\", $engine)) ||\n        !mysqli_query($link, \"INSERT INTO test(id) VALUES (1)\"))\n        printf(\"[002] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    if (!$res = mysqli_query($link, \"SELECT COUNT(id) AS _num_rows FROM test\"))\n        printf(\"[003] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    $row = mysqli_fetch_assoc($res);\n    mysqli_free_result($res);\n    if ($row['_num_rows'] != 1)\n        printf(\"[003] Expecting 1 got %s\\n\", $row['_num_rows']);\n    mysqli_close($link);\n    $link = mysqli_init();\n    if (true !== mysqli_options($link, MYSQLI_INIT_COMMAND, \"INSERT INTO test(id) VALUES (2)\"))\n        printf(\"[004] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    if (!my_mysqli_real_connect($link, $host, $user, $passwd, $db, $port, $socket))\n        printf(\"[005] Cannot connect to the server using host=%s, user=%s, passwd=***, dbname=%s, port=%s, socket=%s\\n\",\n            $host, $user, $db, $port, $socket);\n    if (!$res = mysqli_query($link, \"SELECT COUNT(id) AS _num_rows FROM test\"))\n        printf(\"[006] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    $row = mysqli_fetch_assoc($res);\n    mysqli_free_result($res);\n    if ($row['_num_rows'] != 2)\n        printf(\"[007] Expecting 1 got %s\\n\", $row['_num_rows']);\n    mysqli_close($link);\n    $link = mysqli_init();\n    if (true !== mysqli_options($link, MYSQLI_INIT_COMMAND, \"INSERT INTO test(i_do_no_exist) VALUES (2)\"))\n        printf(\"[008] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    mysqli_close($link);\n    $link = mysqli_init();\n    if (true !== mysqli_options($link, MYSQLI_INIT_COMMAND, \"INSERT INTO test(i_do_no_exist) VALUES (2)\"))\n        printf(\"[009] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    if (!my_mysqli_real_connect($link, $host, $user, $passwd, $db, $port, $socket))\n        printf(\"[010] Cannot connect to the server using host=%s, user=%s, passwd=***, dbname=%s, port=%s, socket=%s\\n\",\n            $host, $user, $db, $port, $socket);\n    print \"done!\";\n?>")).toMatchSnapshot();
  });
});
