// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/sockets/tests/socket_export_stream-4-win.phpt
  it("socket_export_stream: effects of closing", function () {
    expect(parser.parseCode("<?php\nfunction test($stream, $sock) {\n    if ($stream !== null) {\n        echo \"stream_set_blocking \";\n        try {\n            print_r(stream_set_blocking($stream, 0));\n        } catch (Error $e) {\n            echo get_class($e), \": \", $e->getMessage(), \"\\n\";\n        }\n        echo \"\\n\";\n    }\n    if ($sock !== null) {\n        echo \"socket_set_block \";\n        try {\n            print_r(socket_set_block($sock));\n        } catch (Error $e) {\n            echo get_class($e), \": \", $e->getMessage(), \"\\n\";\n        }\n        echo \"\\n\";\n        echo \"socket_get_option \";\n        try {\n            print_r(socket_get_option($sock, SOL_SOCKET, SO_TYPE));\n        } catch (Error $e) {\n            echo get_class($e), \": \", $e->getMessage(), \"\\n\";\n        }\n        echo \"\\n\";\n    }\n    echo \"\\n\";\n}\necho \"normal\\n\";\n$sock0 = socket_create(AF_INET, SOCK_DGRAM, SOL_UDP);\nsocket_bind($sock0, '0.0.0.0', 0);\n$stream0 = socket_export_stream($sock0);\ntest($stream0, $sock0);\necho \"\\nunset stream\\n\";\n$sock1 = socket_create(AF_INET, SOCK_DGRAM, SOL_UDP);\nsocket_bind($sock1, '0.0.0.0', 0);\n$stream1 = socket_export_stream($sock1);\nunset($stream1);\ntest(null, $sock1);\necho \"\\nunset socket\\n\";\n$sock2 = socket_create(AF_INET, SOCK_DGRAM, SOL_UDP);\nsocket_bind($sock2, '0.0.0.0', 0);\n$stream2 = socket_export_stream($sock2);\nunset($sock2);\ntest($stream2, null);\necho \"\\nclose stream\\n\";\n$sock3 = socket_create(AF_INET, SOCK_DGRAM, SOL_UDP);\nsocket_bind($sock3, '0.0.0.0', 0);\n$stream3 = socket_export_stream($sock3);\nfclose($stream3);\ntest($stream3, $sock3);\necho \"\\nclose socket\\n\";\n$sock4 = socket_create(AF_INET, SOCK_DGRAM, SOL_UDP);\nsocket_bind($sock4, '0.0.0.0', 0);\n$stream4 = socket_export_stream($sock4);\nsocket_close($sock4);\ntest($stream4, $sock4);\n?>")).toMatchSnapshot();
  });
});
