// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/mysqli/tests/mysqli_real_escape_string_gb2312.phpt
  it("mysqli_real_escape_string() - gb2312", function () {
    expect(parser.parseCode("<?php\n    require_once(\"connect.inc\");\n    if (!$link = my_mysqli_connect($host, $user, $passwd, $db, $port, $socket))\n{\n        printf(\"[001] Cannot connect to the server using host=%s, user=%s,\npasswd=***, dbname=%s, port=%s, socket=%s - [%d] %s\\n\", $host, $user, $db,\n$port, $socket, mysqli_connect_errno(), mysqli_connect_error());\n    }\n    if (!mysqli_query($link, 'DROP TABLE IF EXISTS test')) {\n        printf(\"Failed to drop old test table: [%d] %s\\n\", mysqli_errno($link),\nmysqli_error($link));\n    }\n    if (!mysqli_query($link, 'CREATE TABLE test(id INT, label CHAR(1), PRIMARY\nKEY(id)) ENGINE=' . $engine . \" DEFAULT CHARSET=gb2312\")) {\n        printf(\"Failed to create test table: [%d] %s\\n\", mysqli_errno($link),\nmysqli_error($link));\n    }\n    var_dump(mysqli_set_charset($link, \"gb2312\"));\n    if ('����\\\\\\\\����' !== ($tmp = mysqli_real_escape_string($link, '����\\\\����')))\n        printf(\"[004] Expecting \\\\\\\\, got %s\\n\", $tmp);\n    if ('����\\\"����' !== ($tmp = mysqli_real_escape_string($link, '����\"����')))\n        printf(\"[005] Expecting \\\", got %s\\n\", $tmp);\n    if (\"����\\'����\" !== ($tmp = mysqli_real_escape_string($link, \"����'����\")))\n        printf(\"[006] Expecting ', got %s\\n\", $tmp);\n    if (\"����\\\\n����\" !== ($tmp = mysqli_real_escape_string($link, \"����\\n����\")))\n        printf(\"[007] Expecting \\\\n, got %s\\n\", $tmp);\n    if (\"����\\\\r����\" !== ($tmp = mysqli_real_escape_string($link, \"����\\r����\")))\n        printf(\"[008] Expecting \\\\r, got %s\\n\", $tmp);\n    if (\"����\\\\0����\" !== ($tmp = mysqli_real_escape_string($link, \"����\" . chr(0) . \"����\")))\n        printf(\"[009] Expecting %s, got %s\\n\", \"����\\\\0����\", $tmp);\n    var_dump(mysqli_query($link, \"INSERT INTO test(id, label) VALUES (100, '��')\"));\n    mysqli_close($link);\n    print \"done!\";\n?>")).toMatchSnapshot();
  });
});
