// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/mbstring/tests/mb_substitute_character_variation_weak_types.phpt
  it("Test mb_substitute_character() function : usage variation", function () {
    expect(parser.parseCode("<?php\necho \"*** Testing mb_substitute_character(): various types in weak typing mode ***\\n\";\n// Initialise function arguments not being substituted (if any)\n//get an unset variable\n$unset_var = 10;\nunset ($unset_var);\n// define some classes\nclass classWithToString\n{\n    public function __toString() {\n        return \"Class A object\";\n    }\n}\nclass classWithoutToString\n{\n}\n// heredoc string\n$heredoc = <<<EOT\nhello world\nEOT;\n// get a resource variable\n$fp = fopen(__FILE__, \"r\");\n// add arrays\n$index_array = array (1, 2, 3);\n$assoc_array = array ('one' => 1, 'two' => 2);\n//array of values to iterate over\n$inputs = array(\n      // int data\n      'int 0' => 0,\n      'int 1' => 1,\n      'int 12345' => 12345,\n      'int -12345' => -2345,\n      // float data\n      'float 10.5' => 10.5,\n      'float -10.5' => -10.5,\n      'float 10.0e19' => 10.0e19, // Cannot be represented as int\n      'float -10.0e19' => -10.0e19, // Cannot be represented as int\n      'float .5' => .5,\n      // array data\n      'empty array' => array(),\n      'int indexed array' => $index_array,\n      'associative array' => $assoc_array,\n      'nested arrays' => array('foo', $index_array, $assoc_array),\n      // null data\n      'uppercase NULL' => NULL,\n      'lowercase null' => null,\n      // boolean data\n      'lowercase true' => true,\n      'lowercase false' =>false,\n      'uppercase TRUE' =>TRUE,\n      'uppercase FALSE' =>FALSE,\n      // empty data\n      'empty string DQ' => \"\",\n      'empty string SQ' => '',\n      // string data\n      'string DQ' => \"string\",\n      'string SQ' => 'string',\n      'mixed case string' => \"sTrInG\",\n      'heredoc' => $heredoc,\n      // object data\n      'instance of classWithToString' => new classWithToString(),\n      'instance of classWithoutToString' => new classWithoutToString(),\n      // undefined data\n      'undefined var' => @$undefined_var,\n      // unset data\n      'unset var' => @$unset_var,\n);\n// loop through each element of the array for substchar\nmb_internal_encoding('utf-8');\nforeach($inputs as $key =>$value) {\n      echo \"--$key--\\n\";\n      try {\n          var_dump( mb_substitute_character($value) );\n      } catch (\\ValueError|\\TypeError $e) {\n          echo get_class($e) . ': ' . $e->getMessage() . \\PHP_EOL;\n      }\n}\nfclose($fp);\n?>")).toMatchSnapshot();
  });
});
