// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/oci8/tests/imp_res_3.phpt
  it("Oracle Database 12c Implicit Result Sets: bigger data size", function () {
    expect(parser.parseCode("<?php\nrequire(__DIR__.'/connect.inc');\n// Initialization\n$stmtarray = array(\n    \"drop table imp_res_3_tab_1\",\n    \"create table imp_res_3_tab_1 (c1 number, c2 varchar2(10))\",\n    \"insert into imp_res_3_tab_1 values (1, 'a')\",\n    \"insert into imp_res_3_tab_1 values (2, 'f')\",\n    \"drop table imp_res_3_tab_2\",\n    \"create table imp_res_3_tab_2 (c3 varchar2(1))\",\n    \"insert into imp_res_3_tab_2 values ('t')\",\n    \"insert into imp_res_3_tab_2 values ('u')\",\n    \"insert into imp_res_3_tab_2 values ('v')\",\n    \"insert into imp_res_3_tab_2 values ('w')\",\n    \"create or replace procedure imp_res_3_proc as\n      c1 sys_refcursor;\n      i pls_integer;\n    begin\n      for i in 1..30 loop  -- if this value is too big for Oracle's open_cursors, calling imp_res_3_proc() can fail with ORA-1000\n        open c1 for select t1.*, t2.*, t3.*, t4.*, t5.*\n            from imp_res_3_tab_1 t1, imp_res_3_tab_1 t2, imp_res_3_tab_1 t3,\n                 imp_res_3_tab_1 t4, imp_res_3_tab_1 t5 order by 1,3,5,7,9,2,4,6,8,10;\n        dbms_sql.return_result(c1);\n        open c1 for select c2 from imp_res_3_tab_1 order by 1;\n        dbms_sql.return_result(c1);\n        open c1 for select * from imp_res_3_tab_2 order by 1;\n        dbms_sql.return_result(c1);\n        open c1 for select * from dual;\n        dbms_sql.return_result (c1);\n      end loop;\n    end;\"\n);\noci8_test_sql_execute($c, $stmtarray);\n// Run Test\necho \"Test 1\\n\";\n$s = oci_parse($c, \"begin imp_res_3_proc(); end;\");\noci_execute($s);\nwhile (($row = oci_fetch_array($s, OCI_NUM+OCI_RETURN_NULLS)) != false) {\n    foreach ($row as $item) {\n        echo \"  \".$item;\n    }\n    echo \"\\n\";\n}\n// Clean up\n$stmtarray = array(\n    \"drop procedure imp_res_3_proc\",\n    \"drop table imp_res_3_tab_1\",\n    \"drop table imp_res_3_tab_2\"\n);\noci8_test_sql_execute($c, $stmtarray);\n?>")).toMatchSnapshot();
  });
});
