// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/mysqli/tests/002.phpt
  it("mysqli bind_result 1", function () {
    expect(parser.parseCode("<?php\n    require_once(\"connect.inc\");\n    /*** test mysqli_connect 127.0.0.1 ***/\n    if (!$link = my_mysqli_connect($host, $user, $passwd, $db, $port, $socket))\n       printf(\"[001] [%d] %s\\n\", mysqli_connect_errno(), mysqli_connect_error());\n    if (!mysqli_query($link, \"DROP TABLE IF EXISTS test_fetch_null\"))\n        printf(\"[002] Cannot drop table, [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    $rc = mysqli_query($link,\"CREATE TABLE test_fetch_null(col1 tinyint, col2 smallint,\n        col3 int, col4 bigint,\n        col5 float, col6 double,\n        col7 date, col8 time,\n        col9 varbinary(10),\n        col10 varchar(50),\n        col11 char(20)) ENGINE=\" . $engine);\n    if (!$rc)\n        printf(\"[003] Cannot create table, [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    $rc = mysqli_query($link, \"INSERT INTO test_fetch_null(col1,col10, col11) VALUES(1,'foo1', 1000),(2,'foo2', 88),(3,'foo3', 389789)\");\n    if (!$rc)\n        printf(\"[004] Cannot insert records, [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    $stmt = mysqli_prepare($link, \"SELECT col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11 from test_fetch_null ORDER BY col1\");\n    mysqli_stmt_bind_result($stmt, $c1, $c2, $c3, $c4, $c5, $c6, $c7, $c8, $c9, $c10, $c11);\n    mysqli_stmt_execute($stmt);\n    mysqli_stmt_fetch($stmt);\n    $test = array($c1,$c2,$c3,$c4,$c5,$c6,$c7,$c8,$c9,$c10,$c11);\n    var_dump($test);\n    mysqli_stmt_close($stmt);\n    @mysqli_query($link, \"DROP TABLE IF EXISTS test_fetch_null\");\n    mysqli_close($link);\n    print \"done!\";\n?>")).toMatchSnapshot();
  });
});
