// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/standard/tests/array/array_intersect_assoc_variation2.phpt
  it("Test array_intersect_assoc() function : usage variations - unexpected values for 'array2' argument(Bug#43196)", function () {
    expect(parser.parseCode("<?php\n/*\n* Testing array_intersect_assoc() function by passing values to $array2 argument other than arrays\n* and see that function emits proper warning messages wherever expected.\n* The $array1 argument passed is a fixed array.\n*/\necho \"*** Testing array_intersect_assoc() : Passing non-array values to \\$array2 argument ***\\n\";\n// array to be passsed to $array1 as default argument\n$array1 = array(1, 2);\n// additional array to be passed for intersection\n$arr3 = array(1, 2, \"one\" => 1, \"two\" => 2);\n// get an unset variable\n$unset_var = 10;\nunset ($unset_var);\n// get a class\nclass classA\n{\n  public function __toString() {\n    return \"Class A object\";\n  }\n}\n// heredoc string\n$heredoc = <<<EOT\nhello world\nEOT;\n// get a resource variable\n$fp = fopen(__FILE__, \"r\");\n// unexpected values to be passed to $array2 argument\n$arrays = array(\n       // int data\n/*1*/  0,\n       1,\n       12345,\n       -2345,\n       // float data\n/*5*/  10.5,\n       -10.5,\n       12.3456789000e10,\n       12.3456789000E-10,\n       .5,\n       // null data\n/*10*/ NULL,\n       null,\n       // boolean data\n/*12*/ true,\n       false,\n       TRUE,\n       FALSE,\n       // empty data\n/*16*/ \"\",\n       '',\n       // string data\n/*18*/ \"string\",\n       'string',\n       $heredoc,\n       // object data\n/*21*/ new classA(),\n       // undefined data\n/*22*/ @$undefined_var,\n       // unset data\n/*23*/ @$unset_var,\n       // resource variable\n/*24*/ $fp\n);\n// loop through each sub-array within $arrays to check the behavior of array_intersect_assoc()\n$iterator = 1;\nforeach($arrays as $unexpected_value) {\n    echo \"\\n-- Iteration $iterator --\";\n    // Calling array_intersect_assoc() with default arguments\n    try {\n        var_dump( array_intersect_assoc($array1,$unexpected_value) );\n    } catch (TypeError $e) {\n        echo $e->getMessage(), \"\\n\";\n    }\n    // Calling array_intersect_assoc() with more arguments\n    try {\n        var_dump( array_intersect_assoc($array1, $unexpected_value, $arr3) );\n    } catch (TypeError $e) {\n        echo $e->getMessage(), \"\\n\";\n    }\n    $iterator++;\n}\n// close the file resource used\nfclose($fp);\necho \"Done\";\n?>")).toMatchSnapshot();
  });
});
