// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/standard/tests/file/copy_variation7.phpt
  it("Test copy() function: usage variations - links", function () {
    expect(parser.parseCode("<?php\n/* Test copy() function: Trying to create copy of links */\n$file_path = __DIR__;\necho \"*** Testing copy() with symlink and hardlink ***\\n\";\n$file = $file_path.\"/copy_variation7.tmp\";\n$file_handle = fopen($file, \"w\");\nfwrite( $file_handle, str_repeat(\"Hello World, this is 2007 year ....\\n\", 100) );\nfclose($file_handle);\n$symlink = $file_path.\"/copy_variation7_symlink.tmp\";\n$hardlink = $file_path.\"/copy_variation7_hardlink.tmp\";\nsymlink($file, $symlink);  //creating symlink\nlink($file, $hardlink);  //creating hardlink\necho \"Size of source files => \\n\";\nvar_dump( filesize($file_path.\"/copy_variation7_symlink.tmp\") );  //size of the symlink itself\nclearstatcache();\nvar_dump( filesize($file_path.\"/copy_variation7_hardlink.tmp\") );  //size of the file\nclearstatcache();\necho \"-- Now applying copy() on source link to create copies --\\n\";\necho \"-- With symlink --\\n\";\nvar_dump( copy($symlink, $file_path.\"/copy_copy_variation7_symlink.tmp\") );\nvar_dump( file_exists($file_path.\"/copy_copy_variation7_symlink.tmp\") );\nvar_dump( is_link($file_path.\"/copy_copy_variation7_symlink.tmp\") );\nvar_dump( is_file($file_path.\"/copy_copy_variation7_symlink.tmp\") );\nvar_dump( filesize($file_path.\"/copy_copy_variation7_symlink.tmp\") );\nclearstatcache();\necho \"-- With hardlink --\\n\";\nvar_dump( copy($hardlink, $file_path.\"/copy_copy_variation7_hardlink.tmp\") );\nvar_dump( file_exists($file_path.\"/copy_copy_variation7_hardlink.tmp\") );\nvar_dump( is_link($file_path.\"/copy_copy_variation7_hardlink.tmp\") );\nvar_dump( is_file($file_path.\"/copy_copy_variation7_hardlink.tmp\") );\nvar_dump( filesize($file_path.\"/copy_copy_variation7_hardlink.tmp\") );\nclearstatcache();\necho \"*** Done ***\\n\";\n?>")).toMatchSnapshot();
  });
});
