// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/gd/tests/libgd00100.phpt
  it("libgd #100 (spurious horizontal line drawn by gdImageFilledPolygon)", function () {
    expect(parser.parseCode("<?php\n$im = imagecreatetruecolor(256, 256);\n$white   = imagecolorallocatealpha($im, 255, 255, 255, 10);\n$black   = imagecolorallocatealpha($im,   0,   0,   0, 10);\n$red     = imagecolorallocatealpha($im, 255,   0,   0, 10);\n$green   = imagecolorallocatealpha($im,   0, 255,   0, 10);\n$blue    = imagecolorallocatealpha($im,   0,   0, 255, 10);\n$yellow  = imagecolorallocatealpha($im, 255, 255,   0, 10);\n$cyan    = imagecolorallocatealpha($im,   0, 255, 255, 10);\n$magenta = imagecolorallocatealpha($im, 255,   0, 255, 10);\n$purple  = imagecolorallocatealpha($im, 100,   0, 100, 10);\nimagefilledrectangle($im, 0, 0, 255, 255, $white);\n// M (bridge)\n$top = 240;\n$bot = 255;\n$d = 30;\n$x = 100;\n$points = array(\n  $x,      $top,\n  $x+2*$d, $top,\n  $x+2*$d, $bot,\n  $x+$d,   (int) (($top+$bot)/2),\n  $x,      $bot\n);\nimagefilledpolygon($im, $points, $yellow);\n// left-facing M not on baseline\n$top = 40;\n$bot = 70;\n$left = 120;\n$right = 180;\n$points = array(\n  $left,  $top,\n  $right, $top,\n  $right, $bot,\n  $left,  $bot,\n  ($left+$right)/2, ($top+$bot)/2\n);\nimagefilledpolygon($im, $points, $purple);\n// left-facing M on baseline\n$top = 240;\n$bot = 270;\n$left = 20;\n$right = 80;\n$points = array(\n  $left,  $top,\n  $right, $top,\n  $right, $bot,\n  $left,  $bot,\n  ($left+$right)/2, ($top+$bot)/2\n);\nimagefilledpolygon($im, $points, $magenta);\n// left-facing M on ceiling\n$top = -15;\n$bot = 15;\n$left = 20;\n$right = 80;\n$points = array(\n  $left,  $top,\n  $right, $top,\n  $right, $bot,\n  $left,  $bot,\n  ($left+$right)/2, ($top+$bot)/2\n);\nimagefilledpolygon($im, $points, $blue);\n$d = 30;\n$x = 150;\n$y = 150;\n$diamond = array($x-$d, $y, $x, $y+$d, $x+$d, $y, $x, $y-$d);\nimagefilledpolygon($im, $diamond, $green);\n$x = 180;\n$y = 225;\n$diamond = array($x-$d, $y, $x, $y+$d, $x+$d, $y, $x, $y-$d);\nimagefilledpolygon($im, $diamond, $red);\n$x = 225;\n$y = 255;\n$diamond = array($x-$d, $y, $x, $y+$d, $x+$d, $y, $x, $y-$d);\nimagefilledpolygon($im, $diamond, $cyan);\n// M (bridge) not touching bottom boundary\n$top = 100;\n$bot = 150;\n$x = 30;\n$points = array(\n  $x,      $top,\n  $x+2*$d, $top,\n  $x+2*$d, $bot,\n  $x+$d,   ($top+$bot)/2,\n  $x,      $bot\n);\nimagefilledpolygon($im, $points, $black);\ninclude_once __DIR__ . '/func.inc';\ntest_image_equals_file(__DIR__ . '/libgd00100.png', $im);\nimagedestroy($im);\n?>")).toMatchSnapshot();
  });
});
