// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/oci8/tests/define6.phpt
  it("oci_define_by_name tests with REF CURSORs", function () {
    expect(parser.parseCode("<?php\nrequire(__DIR__.'/connect.inc');\n// Initialization\n$stmtarray = array(\n    \"drop table define6_tab\",\n    \"create table define6_tab (id number)\",\n    \"insert into define6_tab values (1)\"\n);\noci8_test_sql_execute($c, $stmtarray);\n// Run Test\n$sql =\n\"DECLARE\n  TYPE curtype IS REF CURSOR;\n  cursor_var curtype;\nBEGIN\n  OPEN cursor_var FOR SELECT id FROM define6_tab;\n  :curs := cursor_var;\nEND;\";\necho \"Test 1 - define last\\n\";\n$s1 = oci_parse($c, $sql);\n$cursor1 = oci_new_cursor($c);\noci_bind_by_name($s1, \":curs\", $cursor1, -1, OCI_B_CURSOR);\noci_execute($s1);\noci_execute($cursor1);\noci_define_by_name($cursor1, 'ID', $id1);\nwhile (oci_fetch_row($cursor1)) {\n    var_dump($id1);\n}\necho \"Test 2 - define last with preset var\\n\";\n$s2 = oci_parse($c, $sql);\n$cursor2 = oci_new_cursor($c);\noci_bind_by_name($s2, \":curs\", $cursor2, -1, OCI_B_CURSOR);\noci_execute($s2);\noci_execute($cursor2);\n$id2 = '';\noci_define_by_name($cursor2, 'ID', $id2);\nwhile (oci_fetch_row($cursor2)) {\n    var_dump($id2);\n}\necho \"Test 3 - define before cursor execute\\n\";\n$s3 = oci_parse($c, $sql);\n$cursor3 = oci_new_cursor($c);\noci_bind_by_name($s3, \":curs\", $cursor3, -1, OCI_B_CURSOR);\noci_execute($s3);\noci_define_by_name($cursor3, 'ID', $id3);\noci_execute($cursor3);\nwhile (oci_fetch_row($cursor3)) {\n    var_dump($id3);\n}\necho \"Test 4 - define before top level execute\\n\";\n$s4 = oci_parse($c, $sql);\n$cursor4 = oci_new_cursor($c);\noci_bind_by_name($s4, \":curs\", $cursor4, -1, OCI_B_CURSOR);\noci_define_by_name($cursor4, 'ID', $id4);\noci_execute($s4);\noci_execute($cursor4);\nwhile (oci_fetch_row($cursor4)) {\n    var_dump($id4);\n}\necho \"Test 5 - define before bind\\n\";\n$s5 = oci_parse($c, $sql);\n$cursor5 = oci_new_cursor($c);\noci_define_by_name($cursor5, 'ID', $id5);\noci_bind_by_name($s5, \":curs\", $cursor5, -1, OCI_B_CURSOR);\noci_execute($s5);\noci_execute($cursor5);\nwhile (oci_fetch_row($cursor5)) {\n    var_dump($id5);\n}\necho \"Test 6 - fetch on wrong handle\\n\";\n$s6 = oci_parse($c, $sql);\n$cursor6 = oci_new_cursor($c);\noci_define_by_name($cursor6, 'ID', $id6);\noci_bind_by_name($s6, \":curs\", $cursor6, -1, OCI_B_CURSOR);\noci_execute($s6);\noci_execute($cursor6);\nwhile (oci_fetch_row($s6)) {\n    var_dump($id6);\n}\n// Clean up\n$stmtarray = array(\n    \"drop table define6_tab\"\n);\noci8_test_sql_execute($c, $stmtarray);\n?>")).toMatchSnapshot();
  });
});
