// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/hash/tests/hash_hkdf_basic.phpt
  it("Hash: hash_hkdf() function: basic functionality", function () {
    expect(parser.parseCode("<?php\necho \"*** Testing hash_hkdf(): basic functionality ***\\n\";\n$ikm = 'input key material';\necho 'md2: ', bin2hex(hash_hkdf('md2', $ikm)), \"\\n\";\necho 'md4: ', bin2hex(hash_hkdf('md4', $ikm)), \"\\n\";\necho 'md5: ', bin2hex(hash_hkdf('md5', $ikm)), \"\\n\";\necho 'sha1: ', bin2hex(hash_hkdf('sha1', $ikm)), \"\\n\";\necho 'sha224: ', bin2hex(hash_hkdf('sha224', $ikm)), \"\\n\";\necho 'sha256: ', bin2hex(hash_hkdf('sha256', $ikm)), \"\\n\";\necho 'sha384: ', bin2hex(hash_hkdf('sha384', $ikm)), \"\\n\";\necho 'sha512: ', bin2hex(hash_hkdf('sha512', $ikm)), \"\\n\";\necho 'ripemd128: ', bin2hex(hash_hkdf('ripemd128', $ikm)), \"\\n\";\necho 'ripemd160: ', bin2hex(hash_hkdf('ripemd160', $ikm)), \"\\n\";\necho 'ripemd256: ', bin2hex(hash_hkdf('ripemd256', $ikm)), \"\\n\";\necho 'ripemd320: ', bin2hex(hash_hkdf('ripemd320', $ikm)), \"\\n\";\necho 'whirlpool: ', bin2hex(hash_hkdf('whirlpool', $ikm)), \"\\n\";\necho 'tiger128,3: ', bin2hex(hash_hkdf('tiger128,3', $ikm)), \"\\n\";\necho 'tiger160,3: ', bin2hex(hash_hkdf('tiger160,3', $ikm)), \"\\n\";\necho 'tiger192,3: ', bin2hex(hash_hkdf('tiger192,3', $ikm)), \"\\n\";\necho 'tiger128,4: ', bin2hex(hash_hkdf('tiger128,4', $ikm)), \"\\n\";\necho 'tiger160,4: ', bin2hex(hash_hkdf('tiger160,4', $ikm)), \"\\n\";\necho 'tiger192,4: ', bin2hex(hash_hkdf('tiger192,4', $ikm)), \"\\n\";\necho 'haval128,3: ', bin2hex(hash_hkdf('haval128,3', $ikm)), \"\\n\";\necho 'haval160,3: ', bin2hex(hash_hkdf('haval160,3', $ikm)), \"\\n\";\necho 'haval192,3: ', bin2hex(hash_hkdf('haval192,3', $ikm)), \"\\n\";\necho 'haval224,3: ', bin2hex(hash_hkdf('haval224,3', $ikm)), \"\\n\";\necho 'haval256,3: ', bin2hex(hash_hkdf('haval256,3', $ikm)), \"\\n\";\necho 'haval128,4: ', bin2hex(hash_hkdf('haval128,4', $ikm)), \"\\n\";\necho 'haval160,4: ', bin2hex(hash_hkdf('haval160,4', $ikm)), \"\\n\";\necho 'haval192,4: ', bin2hex(hash_hkdf('haval192,4', $ikm)), \"\\n\";\necho 'haval224,4: ', bin2hex(hash_hkdf('haval224,4', $ikm)), \"\\n\";\necho 'haval256,4: ', bin2hex(hash_hkdf('haval256,4', $ikm)), \"\\n\";\necho 'haval128,5: ', bin2hex(hash_hkdf('haval128,5', $ikm)), \"\\n\";\necho 'haval160,5: ', bin2hex(hash_hkdf('haval160,5', $ikm)), \"\\n\";\necho 'haval192,5: ', bin2hex(hash_hkdf('haval192,5', $ikm)), \"\\n\";\necho 'haval224,5: ', bin2hex(hash_hkdf('haval224,5', $ikm)), \"\\n\";\necho 'haval256,5: ', bin2hex(hash_hkdf('haval256,5', $ikm)), \"\\n\";\necho 'snefru: ', bin2hex(hash_hkdf('snefru', $ikm)), \"\\n\";\necho 'snefru256: ', bin2hex(hash_hkdf('snefru256', $ikm)), \"\\n\";\necho 'gost: ', bin2hex(hash_hkdf('gost', $ikm)), \"\\n\";\n?>")).toMatchSnapshot();
  });
});
