// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/zip/tests/oo_extract.phpt
  it("extractTo", function () {
    expect(parser.parseCode("<?php\n$dirname = __DIR__ . '/';\n$file = $dirname . 'test_with_comment.zip';\ninclude $dirname . 'utils.inc';\n$zip = new ZipArchive;\nif ($zip->open($file) !== TRUE) {\n    echo \"open failed.\\n\";\n    exit('failed');\n}\n$zip->extractTo($dirname . '__oo_extract_tmp');\nif (!is_dir($dirname . '__oo_extract_tmp')) {\n    echo \"failed. mkdir\\n\";\n}\nif (!is_dir($dirname .'__oo_extract_tmp/foobar')) {\n    echo \"failed. mkdir foobar\\n\";\n}\nif (!file_exists($dirname . '__oo_extract_tmp/foobar/baz')) {\n    echo \"failed. extract foobar/baz\\n\";\n} else {\n    echo file_get_contents($dirname . '__oo_extract_tmp/foobar/baz') . \"\\n\";\n}\nif (!file_exists($dirname . '__oo_extract_tmp/bar')) {\n    echo \"failed. bar file\\n\";\n} else {\n    echo file_get_contents($dirname . '__oo_extract_tmp/bar') . \"\\n\";\n}\nif (!file_exists($dirname . '__oo_extract_tmp/foo')) {\n    echo \"failed. foo file\\n\";\n} else {\n    echo file_get_contents($dirname . '__oo_extract_tmp/foo') . \"\\n\";\n}\n/* extract one file */\n$zip->extractTo($dirname . '__oo_extract_tmp', 'bar');\nif (!file_exists($dirname . '__oo_extract_tmp/bar')) {\n    echo \"failed. extract  bar file\\n\";\n} else {\n    echo file_get_contents($dirname . '__oo_extract_tmp/bar') . \"\\n\";\n}\n/* extract two files */\n$zip->extractTo($dirname . '__oo_extract_tmp', array('bar','foo'));\nif (!file_exists($dirname . '__oo_extract_tmp/bar')) {\n    echo \"failed. extract  bar file\\n\";\n} else {\n    echo file_get_contents($dirname . '__oo_extract_tmp/bar') . \"\\n\";\n}\nif (!file_exists($dirname . '__oo_extract_tmp/foo')) {\n    echo \"failed. extract foo file\\n\";\n} else {\n    echo file_get_contents($dirname . '__oo_extract_tmp/foo') . \"\\n\";\n}\nrmdir_rf($dirname . '__oo_extract_tmp');\n?>")).toMatchSnapshot();
  });
});
