// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/standard/tests/file/symlink_link_linkinfo_is_link_variation3.phpt
  it("Test symlink(), linkinfo(), link() and is_link() functions : usage variations - access/update file through softlink", function () {
    expect(parser.parseCode("<?php\n/* Variation 3 : Create file and a soft link to the file\n                 Access data of the file through the soft link\n                 Update the file through soft link\n                 Check size of file and soft link link\n*/\n$file_path = __DIR__;\necho \"*** Accessing and updating data of file through soft link ***\\n\";\n// Creating file and inserting data into it\n$filename = \"$file_path/symlink_link_linkinfo_is_link_variation3.tmp\";\n// create temp file\n$file = fopen($filename, \"w\");\n// create soft link to file\n$linkname = \"$file_path/symlink_link_linkinfo_is_link_link_variation3.tmp\";\nvar_dump( symlink($filename, $linkname) );\n// storing size of symlink in a local variable\n$link_stat = lstat($linkname);  // lstat of link\n$link_size = $link_stat[7];  // size of soft link\n// fill data into file\nfwrite($file, str_repeat(\"text\", 20) );\nfclose($file);\necho \"\\n-- Access data of the file through the soft link --\\n\";\n$data_from_link = file_get_contents($linkname);  // data read from $filename\nvar_dump( $data_from_link );\necho \"\\n-- Check size of soft link and file --\\n\";\nvar_dump( filesize($filename) );\nvar_dump( filesize($linkname) );\n// taking lstat of symlink\n$stat = lstat($linkname);\n// checking that size of symlink remains same\nif ($link_size == $stat[7])\n  echo \"\\nSoft link size remains same \\n\";\nelse\n  echo \"\\nWarning: Soft link size has changed \\n\";\necho \"\\n-- Updating file with data through soft link --\\n\";\n// append link with data\n$fp = fopen($linkname, \"a\");  // open in append mode\nfwrite($fp, \"Hello World\");\nfclose($fp);\n// now check temp file for data; it should append \"Hello World\"\n$data_from_file = file_get_contents($filename);\nvar_dump( $data_from_file );\necho \"\\n-- Check size of soft link and file --\\n\";\nvar_dump( filesize($filename) );\nvar_dump( filesize($linkname) );\n// taking lstat of symlink\n$stat = lstat($linkname);\n// checking that size of symlink remains same\nif ($link_size == $stat[7])\n  echo \"\\nSoft link size remains same \\n\";\nelse\n  echo \"\\nWarning: Soft link size has changed \\n\";\necho \"\\n-- Updating file with data and check data through soft link --\\n\";\n// write to temp file\n$file = fopen($filename, \"w\");\nfwrite($file, \"Hello World\");\nfclose($file);\n// now check link for data; it should echo \"Hello World\"\n$data_from_link = file_get_contents($linkname);\nvar_dump( $data_from_link );\necho \"\\n-- Check size of soft link and file --\\n\";\nvar_dump( filesize($filename) );\nvar_dump( filesize($linkname) );\n// taking lstat of symlink\n$stat = lstat($linkname);\n// checking that size of symlink remains same\nif ($link_size == $stat[7])\n  echo \"\\nSoft link size remains same \\n\";\nelse\n  echo \"\\nWarning: Soft link size has changed \\n\";\n// delete the link\nunlink($linkname);\n// delete the temporary file\nunlink($filename);\necho \"Done\\n\";\n?>")).toMatchSnapshot();
  });
});
