// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/oci8/tests/error_parse.phpt
  it("Test error handling when persistent connection is passed to oci_error()", function () {
    expect(parser.parseCode("<?php\n// As part of the fix for Bug 42134, an error handling difference was\n// noticed when oci_error() was passed a persistent connection.  This\n// was fixed and the behavior of oci_error() for all connections types\n// was made consistent.\nrequire(__DIR__.'/details.inc');\n// Test parse error for normal connection\nif (!empty($dbase)) {\n    $c1 = oci_connect($user,$password,$dbase);\n}\nelse {\n    $c1 = oci_connect($user,$password);\n}\n$s = @oci_parse($c1, \"select ' from dual\");\nif (!$s) {\n    echo \"Normal connection: Parse error\\n\";\n    $m = oci_error($c1);\n    var_dump($m);\n}\n// Test parse error for new connection\nif (!empty($dbase)) {\n    $c2 = oci_new_connect($user,$password,$dbase);\n}\nelse {\n    $c2 = oci_new_connect($user,$password);\n}\n$s = @oci_parse($c2, \"select ' from dual\");\nif (!$s) {\n    echo \"New connection: Parse error\\n\";\n    $m = oci_error($c2);\n    var_dump($m);\n}\n// Test parse error for persistent connection\nif (!empty($dbase)) {\n    $c3 = oci_pconnect($user,$password,$dbase);\n}\nelse {\n    $c3 = oci_pconnect($user,$password);\n}\n$s = @oci_parse($c3, \"select ' from dual\");\nif (!$s) {\n    echo \"Persistent connection: Parse error\\n\";\n    $m = oci_error($c3);\n    var_dump($m);\n}\n// Verify that passing no connection doesn't affect future calls\n$m = oci_error();\necho \"No connection: error: \";\nvar_dump($m);\n// Check the errors are still accessible in the respective handles\n$m = oci_error($c1);\necho \"Normal connection (take #2): Parse error: \";\necho $m[\"message\"], \"\\n\";\n$m = oci_error($c2);\necho \"New connection (take #2): Parse error: \";\necho $m[\"message\"], \"\\n\";\n$m = oci_error($c3);\necho \"Persistent connection (take #2): Parse error: \";\necho $m[\"message\"], \"\\n\";\n// Now create a new error for a normal connection and check all again\n$s = @oci_new_collection($c1, \"ABC\");\n$m = oci_error($c1);\necho \"Normal connection: New Collection error: \";\necho $m[\"message\"], \"\\n\";\n$m = oci_error($c2);\necho \"New connection (take #3): Parse error: \";\necho $m[\"message\"], \"\\n\";\n$m = oci_error($c3);\necho \"Persistent connection (take #3): Parse error: \";\necho $m[\"message\"], \"\\n\";\necho \"Done\\n\";\n?>")).toMatchSnapshot();
  });
});
