// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/standard/tests/array/array_unique_variation9.phpt
  it("Test array_unique() function : usage variations - more than 16 elements", function () {
    expect(parser.parseCode("<?php\n$a = array (\n  0 => 'acls_channel',\n  1 => 'acls_channel',\n  2 => 'ad_zone_assoc',\n  3 => 'ad_zone_assoc',\n  4 => 'ad_zone_assoc',\n  5 => 'affiliates',\n  6 => 'affiliates',\n  7 => 'affiliates',\n  8 => 'banners',\n  9 => 'banners',\n  10 => 'banners',\n  11 => 'campaigns',\n  12 => 'campaigns',\n  13 => 'campaigns',\n  14 => 'campaigns_trackers',\n  15 => 'campaigns_trackers',\n  16 => 'campaigns_trackers',\n  17 => 'clients',\n  18 => 'clients',\n  19 => 'clients',\n  20 => 'data_intermediate_ad',\n  21 => 'data_intermediate_ad',\n  22 => 'data_summary_ad_hourly',\n  23 => 'data_summary_ad_hourly',\n  24 => 'data_summary_zone_country_daily',\n  25 => 'data_summary_zone_country_daily',\n  26 => 'data_summary_zone_country_daily',\n  27 => 'data_summary_zone_country_forecast',\n  28 => 'data_summary_zone_country_forecast',\n  29 => 'data_summary_zone_country_forecast',\n  30 => 'data_summary_zone_country_monthly',\n  31 => 'data_summary_zone_country_monthly',\n  32 => 'data_summary_zone_country_monthly',\n  33 => 'data_summary_zone_domain_page_daily',\n  34 => 'data_summary_zone_domain_page_daily',\n  35 => 'data_summary_zone_domain_page_daily',\n  36 => 'data_summary_zone_domain_page_forecast',\n  37 => 'data_summary_zone_domain_page_forecast',\n  38 => 'data_summary_zone_domain_page_forecast',\n  39 => 'data_summary_zone_domain_page_monthly',\n  40 => 'data_summary_zone_domain_page_monthly',\n  41 => 'data_summary_zone_domain_page_monthly',\n  42 => 'data_summary_zone_site_keyword_daily',\n  43 => 'data_summary_zone_site_keyword_daily',\n  44 => 'data_summary_zone_site_keyword_daily',\n  45 => 'data_summary_zone_site_keyword_forecast',\n  46 => 'data_summary_zone_site_keyword_forecast',\n  47 => 'data_summary_zone_site_keyword_forecast',\n  48 => 'data_summary_zone_site_keyword_monthly',\n  49 => 'data_summary_zone_site_keyword_monthly',\n  50 => 'data_summary_zone_site_keyword_monthly',\n  51 => 'data_summary_zone_source_daily',\n  52 => 'data_summary_zone_source_daily',\n  53 => 'data_summary_zone_source_daily',\n  54 => 'data_summary_zone_source_forecast',\n  55 => 'data_summary_zone_source_forecast',\n  56 => 'data_summary_zone_source_forecast',\n  57 => 'data_summary_zone_source_monthly',\n  58 => 'data_summary_zone_source_monthly',\n  59 => 'data_summary_zone_source_monthly',\n  60 => 'placement_zone_assoc',\n  61 => 'placement_zone_assoc',\n  62 => 'placement_zone_assoc',\n  63 => 'trackers',\n  64 => 'trackers',\n  65 => 'trackers',\n  66 => 'variables',\n  67 => 'variables',\n  68 => 'variables',\n);\nprint_r(array_unique($a));\n?>")).toMatchSnapshot();
  });
});
