// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/session/tests/session_ini_set.phpt
  it("Test ini_set() for session : basic functionality", function () {
    expect(parser.parseCode("<?php\nob_start();\n/*\n * Prototype : string ini_set(string $name, string $value)\n * Description : Set session ini\n * Source code : ext/session/session.c\n */\necho \"*** Testing ini_set() for session ini: basic functionality ***\\n\";\nvar_dump(ini_set(\"session.save_path\", \"\"));\nvar_dump(ini_set(\"session.name\", \"PHPSESSID\"));\nvar_dump(ini_set(\"session.save_handler\", \"files\"));\nvar_dump(ini_set(\"session.auto_start\", \"0\"));\nvar_dump(ini_set(\"session.gc_probability\", \"1\"));\nvar_dump(ini_set(\"session.gc_divisor\", \"100\"));\nvar_dump(ini_set(\"session.gc_maxlifetime\", \"1440\"));\nvar_dump(ini_set(\"session.serialize_handler\", \"php\"));\nvar_dump(ini_set(\"session.cookie_path\", \"/\"));\nvar_dump(ini_set(\"session.cookie_domain\", \"\"));\nvar_dump(ini_set(\"session.cookie_secure\", \"0\"));\nvar_dump(ini_set(\"session.cookie_httponly\", \"0\"));\nvar_dump(ini_set(\"session.use_cookies\", \"1\"));\nvar_dump(ini_set(\"session.use_only_cookies\", \"1\"));\nvar_dump(ini_set(\"session.use_strict_mode\", \"0\"));\nvar_dump(ini_set(\"session.referer_check\", \"\"));\nvar_dump(ini_set(\"session.cache_limiter\", \"nocache\"));\nvar_dump(ini_set(\"session.cache_expire\", \"180\"));\nvar_dump(ini_set(\"session.use_trans_sid\", \"0\"));\nvar_dump(ini_set(\"session.sid_length\", \"32\"));\nvar_dump(ini_set(\"session.sid_bits_per_character\", \"4\"));\nvar_dump(ini_set(\"session.lazy_write\", \"1\"));\nsession_start();\nvar_dump(\"session started\");\nvar_dump(ini_set(\"session.save_path\", \"\"));\nvar_dump(ini_set(\"session.name\", \"PHPSESSID\"));\nvar_dump(ini_set(\"session.save_handler\", \"files\"));\nvar_dump(ini_set(\"session.auto_start\", \"0\"));\nvar_dump(ini_set(\"session.gc_probability\", \"1\"));\nvar_dump(ini_set(\"session.gc_divisor\", \"100\"));\nvar_dump(ini_set(\"session.gc_maxlifetime\", \"1440\"));\nvar_dump(ini_set(\"session.serialize_handler\", \"php\"));\nvar_dump(ini_set(\"session.cookie_path\", \"/\"));\nvar_dump(ini_set(\"session.cookie_domain\", \"\"));\nvar_dump(ini_set(\"session.cookie_secure\", \"0\"));\nvar_dump(ini_set(\"session.cookie_httponly\", \"0\"));\nvar_dump(ini_set(\"session.use_cookies\", \"1\"));\nvar_dump(ini_set(\"session.use_only_cookies\", \"1\"));\nvar_dump(ini_set(\"session.use_strict_mode\", \"0\"));\nvar_dump(ini_set(\"session.referer_check\", \"\"));\nvar_dump(ini_set(\"session.cache_limiter\", \"nocache\"));\nvar_dump(ini_set(\"session.cache_expire\", \"180\"));\nvar_dump(ini_set(\"session.use_trans_sid\", \"0\"));\nvar_dump(ini_set(\"session.sid_length\", \"32\"));\nvar_dump(ini_set(\"session.sid_bits_per_character\", \"4\"));\nvar_dump(ini_set(\"session.lazy_write\", \"1\"));\necho \"Done\";\nob_end_flush();\n?>")).toMatchSnapshot();
  });
});
