// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/intl/tests/locale_get_display_variant2.phpt
  it("locale_get_display_variant() icu >= 4.8", function () {
    expect(parser.parseCode("<?php\n/*\n * Try getting the display_variant for different locales\n * with Procedural and Object methods.\n */\nfunction ut_main()\n{\n    $res_str = '';\n    $disp_locales=array('en','fr','de');\n    $locales = array(\n        'uk-ua_CALIFORNIA@currency=;currency=GRN',\n        'root',\n        'uk@currency=EURO',\n        'Hindi',\n//Simple language subtag\n        'de',\n        'fr',\n        'ja',\n        'i-enochian', //(example of a grandfathered tag)\n//Language subtag plus Script subtag:\n        'zh-Hant',\n        'zh-Hans',\n        'sr-Cyrl',\n        'sr-Latn',\n//Language-Script-Region\n        'zh-Hans-CN',\n        'sr-Latn-CS',\n//Language-Variant\n        'sl-rozaj',\n        'sl-nedis',\n//Language-Region-Variant\n        'de-CH-1901',\n        'sl-IT-nedis',\n//Language-Script-Region-Variant\n        'sl-Latn-IT-nedis',\n//Language-Region:\n        'de-DE',\n        'en-US',\n        'es-419',\n//Private use subtags:\n        'de-CH-x-phonebk',\n        'az-Arab-x-AZE-derbend',\n//Extended language subtags\n        'zh-min',\n        'zh-min-nan-Hant-CN',\n//Private use registry values\n        'x-whatever',\n        'qaa-Qaaa-QM-x-southern',\n        'sr-Latn-QM',\n        'sr-Qaaa-CS',\n/*Tags that use extensions (examples ONLY: extensions MUST be defined\n   by revision or update to this document or by RFC): */\n        'en-US-u-islamCal',\n        'zh-CN-a-myExt-x-private',\n        'en-a-myExt-b-another',\n//Some Invalid Tags:\n        'de-419-DE',\n        'a-DE',\n        'ar-a-aaa-b-bbb-a-ccc'\n    );\n    $res_str = '';\n    foreach( $locales as $locale )\n    {\n        $res_str .= \"locale='$locale'\\n\";\n        foreach( $disp_locales as $disp_locale )\n        {\n            $scr = ut_loc_get_display_variant( $locale ,$disp_locale );\n            $res_str .= \"disp_locale=$disp_locale :  display_variant=$scr\";\n            $res_str .= \"\\n\";\n        }\n        $res_str .= \"-----------------\\n\";\n    }\n    return $res_str;\n}\ninclude_once( 'ut_common.inc' );\nut_run();\n?>")).toMatchSnapshot();
  });
});
