// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/standard/tests/file/copy_variation8.phpt
  it("Test copy() function: usage variations - copying links across dirs", function () {
    expect(parser.parseCode("<?php\n/* Trying to copy the links across dir paths given in various notations\n     and dirs having limited access */\necho \"*** Testing copy() function: copying links across different directories ***\\n\";\n$file_path = __DIR__;\n$base_dir = $file_path.\"/copy_variation8\";\nmkdir($base_dir);\n$sub_dir = $base_dir.\"/copy_variation8_sub\";\nmkdir($sub_dir);\n$dirname_with_blank = $sub_dir.\"/copy variation6\";\nmkdir($dirname_with_blank);\n$file = $file_path.\"/copy_variation8.tmp\";\nfclose( fopen($file, \"w\") );\n$symlink = $file_path.\"/copy_variation8_symlink.tmp\";\n$hardlink = $file_path.\"/copy_variation8_hardlink.tmp\";\nsymlink($file, $symlink);  //creating symlink\nlink($file, $hardlink);  //creating hardlink\n$dests = array(\n  $base_dir.\"/copy_copy_variation8.tmp\",\n  $base_dir.\"/copy_variation8_sub/copy_copy_variation8.tmp\",\n  \"$sub_dir/copy_copy_variation8.tmp\",\n  \"$sub_dir/../copy_copy_variation8.tmp\",\n  \"$sub_dir/../copy_variation8_sub/copy_copy_variation8.tmp\",\n  \"$sub_dir/..///../copy_copy_variation8.tmp\",\n  \"$sub_dir///../*\",\n  \"$dirname_with_blank/copy_copy_variation8.tmp\"\n);\n$count = 1;\nforeach($dests as $dest) {\n  echo \"\\n-- Iteration $count --\\n\";\n  echo \"- With symlink -\\n\";\n  var_dump( copy($symlink, $dest) );\n  var_dump( file_exists($dest) );\n  var_dump( is_link($dest) ); //expected: bool(false)\n  var_dump( is_file($dest) );  //expected: bool(true)\n  clearstatcache();\n  unlink(\"$dest\");\n  echo \"- With hardlink -\\n\";\n  var_dump( copy($hardlink, $dest) );\n  var_dump( file_exists($dest) );\n  var_dump( is_link($dest) );  //expected: bool(flase)\n  var_dump( is_file($dest) );  //expected: bool(true)\n  clearstatcache();\n  unlink(\"$dest\");\n  $count++;\n}\nunlink($symlink);\nunlink($hardlink);\nunlink($file);\nrmdir($dirname_with_blank);\nrmdir($sub_dir);\nrmdir($base_dir);\necho \"*** Done ***\\n\";\n?>")).toMatchSnapshot();
  });
});
