// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/mysqli/tests/mysqli_stmt_fetch.phpt
  it("mysqli_stmt_fetch()", function () {
    expect(parser.parseCode("<?php\n    /*\n    NOTE: no datatype tests here! This is done by\n    mysqli_stmt_bind_result.phpt already. Restrict\n    this test case to the basics.\n    */\n    require_once(\"connect.inc\");\n    require('table.inc');\n    if (!$stmt = mysqli_stmt_init($link))\n        printf(\"[003] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    // stmt object status test\n    try {\n        mysqli_stmt_fetch($stmt);\n    } catch (Error $exception) {\n        echo $exception->getMessage() . \"\\n\";\n    }\n    if (!mysqli_stmt_prepare($stmt, \"SELECT id, label FROM test ORDER BY id LIMIT 2\"))\n        printf(\"[005] [%d] %s\\n\", mysqli_stmt_errno($stmt), mysqli_stmt_error($stmt));\n    // FIXME - different versions return different values ?!\n    if ((NULL !== ($tmp = mysqli_stmt_fetch($stmt))) && (false !== $tmp))\n        printf(\"[006] Expecting NULL or boolean/false, got %s/%s\\n\", gettype($tmp), $tmp);\n    if (!mysqli_stmt_execute($stmt))\n        printf(\"[007] [%d] %s\\n\", mysqli_stmt_errno($stmt), mysqli_stmt_error($stmt));\n    if (true !== ($tmp = mysqli_stmt_fetch($stmt)))\n        printf(\"[008] NULL, got %s/%s\\n\", gettype($tmp), $tmp);\n    mysqli_stmt_close($stmt);\n    if (!$stmt = mysqli_stmt_init($link))\n        printf(\"[009] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    if (!mysqli_stmt_prepare($stmt, \"SELECT id, label FROM test ORDER BY id LIMIT 2\"))\n        printf(\"[010] [%d] %s\\n\", mysqli_stmt_errno($stmt), mysqli_stmt_error($stmt));\n    if (!mysqli_stmt_execute($stmt))\n        printf(\"[011] [%d] %s\\n\", mysqli_stmt_errno($stmt), mysqli_stmt_error($stmt));\n    $id = NULL;\n    $label = NULL;\n    if (true !== ($tmp = mysqli_stmt_bind_result($stmt, $id, $label)))\n        printf(\"[012] Expecting boolean/true, got %s/%s\\n\", gettype($tmp), $tmp);\n    if (true !== ($tmp = mysqli_stmt_fetch($stmt)))\n        printf(\"[013] Expecting boolean/true, got %s/%s, [%d] %s\\n\",\n            gettype($tmp), $tmp, mysqli_stmt_errno($stmt), mysqli_stmt_error($stmt));\n    if (!mysqli_kill($link, mysqli_thread_id($link)))\n        printf(\"[014] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    if (true !== ($tmp = mysqli_stmt_fetch($stmt)))\n        printf(\"[015] Expecting boolean/true, got %s/%s\\n\", gettype($tmp), $tmp);\n    mysqli_stmt_close($stmt);\n    try {\n        mysqli_stmt_fetch($stmt);\n    } catch (Error $exception) {\n        echo $exception->getMessage() . \"\\n\";\n    }\n    mysqli_close($link);\n    print \"done!\";\n?>")).toMatchSnapshot();
  });
});
