// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/oci8/tests/edition_1.phpt
  it("Basic test for setting Oracle 11gR2 \"edition\" attribute", function () {
    expect(parser.parseCode("<?php\n/* In 11.2, there can only be one child edition.  So this test will\n * fail to create the necessary editions if a child edition exists\n * already\n */\n$testuser     = 'testuser_attr_1';  // Used in conn_attr.inc\n$testpassword = 'testuser';\nrequire(__DIR__.\"/conn_attr.inc\");\nfunction select_fn($conn) {\n    $s = oci_parse($conn,\"select * from view_ed\");\n    oci_execute($s);\n    while ($row = oci_fetch_row($s)) {\n        var_dump($row);\n    }\n}\n/* Create a editon MYEDITION\n   create a view view_ed in MYEDITION1.\n   create the same view 'view_ed' with a different definition in MYEDITION.\n   select from both the editions and verify the contents. */\nset_edit_attr('MYEDITION');\n$conn = oci_connect($testuser,$testpassword,$dbase);\nif ($conn === false) {\n    $m = oci_error();\n    die(\"Error:\" . $m['message']);\n}\n$stmtarray = array(\n    \"drop table edit_tab\",\n    \"create table edit_tab (name varchar2(10),age number,job varchar2(50), salary number)\",\n    \"insert into edit_tab values('mike',30,'Senior engineer',200)\",\n    \"insert into edit_tab values('juan',25,'engineer',100)\",\n    \"create or replace editioning view view_ed as select name,age,job from edit_tab\",\n);\noci8_test_sql_execute($conn, $stmtarray);\n// Check the current edition of the DB and the contents of view_ed.\nget_edit_attr($conn);\nselect_fn($conn);\n// Create a different version of view_ed in MYEDITION1.\nset_edit_attr('MYEDITION1');\n$conn2 = oci_new_connect($testuser,$testpassword,$dbase);\n$stmt = \"create or replace editioning view view_ed as select name,age,job,salary from edit_tab\";\n$s = oci_parse($conn2, $stmt);\noci_execute($s);\n// Check the current edition of the DB and the contents of view_ed.\nget_edit_attr($conn2);\nselect_fn($conn2);\n// Verify the contents in MYEDITION EDITION.\necho \"version of view_ed in MYEDITION\\n\";\nget_edit_attr($conn);\nselect_fn($conn);\nclean_up($c);\noci_close($conn);\noci_close($conn2);\necho \"Done\\n\";\n?>")).toMatchSnapshot();
  });
});
