// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/standard/tests/array/array_push_variation2.phpt
  it("Test array_push() function : usage variations - Pass different data types as $var arg", function () {
    expect(parser.parseCode("<?php\n/*\n * Pass different data types as $var argument to array_push to test behaviour\n */\necho \"*** Testing array_push() : usage variations ***\\n\";\n// Initialise function arguments not being substituted\n$stack = array (1, 2);\n//get an unset variable\n$unset_var = 10;\nunset ($unset_var);\n// get a class\nclass classA\n{\n  public function __toString() {\n    return \"Class A object\";\n  }\n}\n// heredoc string\n$heredoc = <<<EOT\nhello world\nEOT;\n// get a resource variable\n$fp = fopen(__FILE__, \"r\");\n// unexpected values to be passed to $var argument\n$inputs = array(\n       // int data\n/*1*/  0,\n       1,\n       12345,\n       -2345,\n       // float data\n/*5*/  10.5,\n       -10.5,\n       12.3456789000e10,\n       12.3456789000E-10,\n       .5,\n       // null data\n/*10*/ NULL,\n       null,\n       // boolean data\n/*12*/ true,\n       false,\n       TRUE,\n       FALSE,\n       // empty data\n/*16*/ \"\",\n       '',\n       array(),\n       // string data\n/*19*/ \"string\",\n       'string',\n       $heredoc,\n       // object data\n/*22*/ new classA(),\n       // undefined data\n/*23*/ @$undefined_var,\n       // unset data\n/*24*/ @$unset_var,\n       // resource variable\n/*25*/ $fp\n);\n// loop through each element of $inputs to check the behavior of array_push()\n$iterator = 1;\nforeach($inputs as $input) {\n  echo \"\\n-- Iteration $iterator --\\n\";\n  $temp_array = $stack;\n  var_dump( array_push($temp_array, $input) );\n  $iterator++;\n};\nfclose($fp);\necho \"Done\";\n?>")).toMatchSnapshot();
  });
});
