// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/standard/tests/array/array_splice_variation3.phpt
  it("Test array_splice() function : usage variations - lengths and offsets", function () {
    expect(parser.parseCode("<?php\n/*\n * Function is implemented in ext/standard/array.c\n*/\necho \"*** array_splice() function : usage variations - lengths and offsets\\n\";\nfunction test_splice ($offset, $length)\n{\n    echo \"  - No replacement\\n\";\n    $input_array=array(0,1,2,3,4,5);\n    var_dump (array_splice ($input_array,$offset,$length));\n    var_dump ($input_array);\n    echo \"  - With replacement\\n\";\n    $input_array=array(0,1,2,3,4,5);\n    var_dump (array_splice ($input_array,$offset,$length,array (\"A\",\"B\",\"C\")));\n    var_dump ($input_array);\n}\necho \"absolute offset - absolute length - cut from beginning\\n\";\ntest_splice (0,2);\necho \"absolute offset - absolute length - cut from middle\\n\";\ntest_splice (2,2);\necho \"absolute offset - absolute length - cut from end\\n\";\ntest_splice (4,2);\necho \"absolute offset - absolute length - attempt to cut past end\\n\";\ntest_splice (4,4);\necho \"absolute offset - absolute length - cut everything\\n\";\ntest_splice (0,7);\necho \"absolute offset - absolute length - cut nothing\\n\";\ntest_splice (3,0);\necho \"absolute offset - relative length - cut from beginning\\n\";\ntest_splice (0,-4);\necho \"absolute offset - relative length - cut from middle\\n\";\ntest_splice (2,-2);\necho \"absolute offset - relative length - attempt to cut form before beginning \\n\";\ntest_splice (0,-7);\necho \"absolute offset - relative length - cut nothing\\n\";\ntest_splice (2,-7);\necho \"relative offset - absolute length - cut from beginning\\n\";\ntest_splice (-6,2);\necho \"relative offset - absolute length - cut from middle\\n\";\ntest_splice (-4,2);\necho \"relative offset - absolute length - cut from end\\n\";\ntest_splice (-2,2);\necho \"relative offset - absolute length - attempt to cut past end\\n\";\ntest_splice (-2,4);\necho \"relative offset - absolute length - cut everything\\n\";\ntest_splice (-6,6);\necho \"relative offset - absolute length - cut nothing\\n\";\ntest_splice (-6,0);\necho \"relative offset - relative length - cut from beginning\\n\";\ntest_splice (-6,-4);\necho \"relative offset - relative length - cut from middle\\n\";\ntest_splice (-4,-2);\necho \"relative offset - relative length - cut nothing\\n\";\ntest_splice (-4,-7);\necho \"Done\\n\";\n?>")).toMatchSnapshot();
  });
});
