// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/standard/tests/file/is_writable_variation2.phpt
  it("Test is_writable() and its alias is_writeable() function: usage variations - file/dir with diff. perms", function () {
    expect(parser.parseCode("<?php\n/* test is_executable() with file/dir having different permissions */\nrequire __DIR__.'/file.inc';\necho \"*** Testing is_writable(): usage variations ***\\n\";\n$file_path = __DIR__;\nmkdir(\"$file_path/is_writable_variation2\");\necho \"\\n*** Testing is_writable() on directory without write permission ***\\n\";\nchmod(\"$file_path/is_writable_variation2\", 0004);\nvar_dump( is_writable(\"$file_path/is_writable_variation2\") );  // exp: bool(false)\nvar_dump( is_writeable(\"$file_path/is_writable_variation2\") );  // exp: bool(false)\nchmod(\"$file_path/is_writable_variation2\", 0777);  // chmod to enable deletion of directory\necho \"\\n*** Testing miscellaneous input for is_writable() function ***\\n\";\n$name_prefix = \"is_writable_variation2\";\ncreate_files(__DIR__, 1, \"numeric\", 0755, 1, \"w\", $name_prefix, 1);\ncreate_files(__DIR__, 1, \"text\", 0755, 1, \"w\", $name_prefix, 2);\ncreate_files(__DIR__, 1, \"empty\", 0755, 1, \"w\", $name_prefix, 3);\ncreate_files(__DIR__, 1, \"numeric\", 0555, 1, \"w\", $name_prefix, 4);\ncreate_files(__DIR__, 1, \"text\", 0222, 1, \"w\", $name_prefix, 5);\ncreate_files(__DIR__, 1, \"numeric\", 0711, 1, \"w\", $name_prefix, 6);\ncreate_files(__DIR__, 1, \"text\", 0114, 1, \"w\", $name_prefix, 7);\ncreate_files(__DIR__, 1, \"numeric\", 0244, 1, \"w\", $name_prefix, 8);\ncreate_files(__DIR__, 1, \"text\", 0421, 1, \"w\", $name_prefix, 9);\ncreate_files(__DIR__, 1, \"text\", 0422, 1, \"w\", $name_prefix, 10);\n$misc_files = array (\n  \"$file_path/is_writable_variation21.tmp\",\n  \"$file_path/is_writable_variation22.tmp\",\n  \"$file_path/is_writable_variation23.tmp\",\n  \"$file_path/is_writable_variation24.tmp\",\n  \"$file_path/is_writable_variation25.tmp\",\n  \"$file_path/is_writable_variation26.tmp\",\n  \"$file_path/is_writable_variation27.tmp\",\n  \"$file_path/is_writable_variation28.tmp\",\n  \"$file_path/is_writable_variation29.tmp\",\n  \"$file_path/is_writable_variation210.tmp\"\n);\n$counter = 1;\n/* loop through to test each element in the above array\n   is a writable file */\nforeach($misc_files as $misc_file) {\n  echo \"-- Iteration $counter --\\n\";\n  var_dump( is_writable($misc_file) );\n  var_dump( is_writeable($misc_file) );\n  $counter++;\n  clearstatcache();\n}\n// change all file's permissions to 777 before deleting\nchange_file_perms($file_path, 10, 0777, $name_prefix);\ndelete_files($file_path, 10, $name_prefix);\necho \"Done\\n\";\n?>")).toMatchSnapshot();
  });
});
