// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/mbstring/tests/casemapping.phpt
  it("Unicode case mapping", function () {
    expect(parser.parseCode("<?php\nfunction toCases($str) {\n    echo \"String: $str\\n\";\n    echo \"Lower: \", mb_convert_case($str, MB_CASE_LOWER), \"\\n\";\n    echo \"Lower Simple: \", mb_convert_case($str, MB_CASE_LOWER_SIMPLE), \"\\n\";\n    echo \"Upper: \", mb_convert_case($str, MB_CASE_UPPER), \"\\n\";\n    echo \"Upper Simple: \", mb_convert_case($str, MB_CASE_UPPER_SIMPLE), \"\\n\";\n    echo \"Title: \", mb_convert_case($str, MB_CASE_TITLE), \"\\n\";\n    echo \"Title Simple: \", mb_convert_case($str, MB_CASE_TITLE_SIMPLE), \"\\n\";\n    echo \"Fold: \", mb_convert_case($str, MB_CASE_FOLD), \"\\n\";\n    echo \"Fold Simple: \", mb_convert_case($str, MB_CASE_FOLD_SIMPLE), \"\\n\";\n    echo \"\\n\";\n}\ntoCases(\"ß\");\ntoCases(\"ﬀ\");\ntoCases(\"İ\");\n// Make sure that case-conversion in Turkish still works correctly.\n// Using the language-agnostic Unicode case mappings would result in\n// characters that are illegal under ISO-8859-9.\nmb_internal_encoding('ISO-8859-9');\n// Capital I with dot (U+0130)\n$str = \"\\xdd\";\necho bin2hex(mb_convert_case($str, MB_CASE_LOWER)), \"\\n\";\necho bin2hex(mb_convert_case($str, MB_CASE_LOWER_SIMPLE)), \"\\n\";\necho bin2hex(mb_convert_case($str, MB_CASE_FOLD)), \"\\n\";\necho bin2hex(mb_convert_case($str, MB_CASE_FOLD_SIMPLE)), \"\\n\";\necho \"\\n\";\n// Lower i without dot (U+0131)\n$str = \"\\xfd\";\necho bin2hex(mb_convert_case($str, MB_CASE_UPPER)), \"\\n\";\necho bin2hex(mb_convert_case($str, MB_CASE_UPPER_SIMPLE)), \"\\n\";\necho bin2hex(mb_convert_case($str, MB_CASE_FOLD)), \"\\n\";\necho bin2hex(mb_convert_case($str, MB_CASE_FOLD_SIMPLE)), \"\\n\";\necho \"\\n\";\n// Capital I without dot (U+0049)\n$str = \"\\x49\";\necho bin2hex(mb_convert_case($str, MB_CASE_LOWER)), \"\\n\";\necho bin2hex(mb_convert_case($str, MB_CASE_LOWER_SIMPLE)), \"\\n\";\necho bin2hex(mb_convert_case($str, MB_CASE_FOLD)), \"\\n\";\necho bin2hex(mb_convert_case($str, MB_CASE_FOLD_SIMPLE)), \"\\n\";\necho \"\\n\";\n// Lower i with dot (U+0069)\n$str = \"\\x69\";\necho bin2hex(mb_convert_case($str, MB_CASE_UPPER)), \"\\n\";\necho bin2hex(mb_convert_case($str, MB_CASE_UPPER_SIMPLE)), \"\\n\";\necho bin2hex(mb_convert_case($str, MB_CASE_FOLD)), \"\\n\";\necho bin2hex(mb_convert_case($str, MB_CASE_FOLD_SIMPLE)), \"\\n\";\n?>")).toMatchSnapshot();
  });
});
