// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/standard/tests/file/symlink_link_linkinfo_is_link_variation4.phpt
  it("Test symlink(), linkinfo(), link() and is_link() functions : usage variations - access/update file through hard link", function () {
    expect(parser.parseCode("<?php\n/* Variation 4 : Create file and a hard link to the file\n                 Access data of the file through the hard link\n                 Update the file through hard link\n                 Check size of file and hard link\n*/\n$file_path = __DIR__;\necho \"*** Accessing and updating data of file through hard link ***\\n\";\n// Creating file and inserting data into it\n$filename = \"$file_path/symlink__link_linkinfo_is_link_variation4.tmp\";\n// create temp file\n$file = fopen($filename, \"w\");\n// fill data into file\nfwrite($file, str_repeat(\"text\", 20) );\nfclose($file);\necho \"\\n-- Access data of the file through the hard link --\\n\";\n// create hard link to file\n$linkname = \"$file_path/symlink_link_linkinfo_is_link_link_variation4.tmp\";\nvar_dump( link($filename, $linkname) );\n$data_from_link = file_get_contents($linkname);  // data read from $filename\nvar_dump( $data_from_link );\necho \"\\n-- Check size of hard link and file --\\n\";\nif( filesize($filename) == filesize($linkname) )\n  echo \"\\nSize of file and hard link are same\\n\";\nelse\n  echo \"\\nWarning: Size of file and hard link differ\\n\";\necho \"\\n-- Updating file with data through hard link --\\n\";\n// append link with data\n$fp = fopen($linkname, \"a\");  // open in append mode\nfwrite($fp, \"Hello World\");\nfclose($fp);\n// now check temp file for data; it should append \"Hello World\"\n$data_from_file = file_get_contents($filename);\nvar_dump( $data_from_file );\necho \"\\n-- Check size of hard link and file --\\n\";\nif( filesize($filename) == filesize($linkname) )\n  echo \"\\nSize of file and hard link are same\\n\";\nelse\n  echo \"\\nWarning: Size of file and hard link differ\\n\";\necho \"\\n-- Updating file with data and check data through hard link --\\n\";\n// write to temp file\n$file = fopen($filename, \"w\");\nfwrite($file, \"Hello World\");\nfclose($file);\n// now check link for data; it should echo \"Hello World\"\n$data_from_link = file_get_contents($linkname);\nvar_dump( $data_from_link );\necho \"\\n-- Check size of hard link and file --\\n\";\nvar_dump( filesize($filename) );\nvar_dump( filesize($linkname) );\nif( filesize($filename) == filesize($linkname) )\n  echo \"\\nSize of file and hard link are same\\n\";\nelse\n  echo \"\\nWarning: Size of file and hard link differ\\n\";\n// delete the link\nunlink($linkname);\n// delete the temporary file\nunlink($filename);\necho \"Done\\n\";\n?>")).toMatchSnapshot();
  });
});
