// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/mysqli/tests/057.phpt
  it("mysqli_stmt_result_metadata", function () {
    expect(parser.parseCode("<?php\n    require_once(\"connect.inc\");\n    /*** test mysqli_connect 127.0.0.1 ***/\n    $link = my_mysqli_connect($host, $user, $passwd, $db, $port, $socket);\n    mysqli_select_db($link, $db);\n    mysqli_query($link,\"DROP TABLE IF EXISTS test_store_result\");\n    mysqli_query($link,\"CREATE TABLE test_store_result (a int)\");\n    mysqli_query($link, \"INSERT INTO test_store_result VALUES (1),(2),(3)\");\n    $stmt = mysqli_prepare($link, \"SELECT * FROM test_store_result\");\n    mysqli_stmt_execute($stmt);\n    /* this should produce an out of sync error */\n    if ($result = mysqli_query($link, \"SELECT * FROM test_store_result\")) {\n        mysqli_free_result($result);\n        printf (\"Query ok\\n\");\n    }\n    mysqli_stmt_close($stmt);\n    /* now we should try mysqli_stmt_reset() */\n    $stmt = mysqli_prepare($link, \"SELECT * FROM test_store_result\");\n    var_dump(mysqli_stmt_execute($stmt));\n    var_dump(mysqli_stmt_reset($stmt));\n    var_dump($stmt = mysqli_prepare($link, \"SELECT * FROM test_store_result\"));\n    if ($stmt->affected_rows !== 0)\n            printf(\"[001] Expecting 0, got %d\\n\", $stmt->affected_rows);\n    var_dump(mysqli_stmt_execute($stmt));\n    var_dump($stmt = @mysqli_prepare($link, \"SELECT * FROM test_store_result\"), mysqli_error($link));\n    $stmt = mysqli_prepare($link, \"SELECT * FROM test_store_result\");\n    mysqli_stmt_execute($stmt);\n    $result1 = mysqli_stmt_result_metadata($stmt);\n    mysqli_stmt_store_result($stmt);\n    printf (\"Rows: %d\\n\", mysqli_stmt_affected_rows($stmt));\n    /* this should show an error, cause results are not buffered */\n    if ($result = mysqli_query($link, \"SELECT * FROM test_store_result\")) {\n        $row = mysqli_fetch_row($result);\n        mysqli_free_result($result);\n    }\n    var_dump($row);\n    mysqli_free_result($result1);\n    mysqli_stmt_close($stmt);\n    mysqli_close($link);\n    echo \"done!\";\n?>")).toMatchSnapshot();
  });
});
