// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/pdo_mysql/tests/pdo_mysql_stmt_columncount.phpt
  it("MySQL PDOStatement->columnCount()", function () {
    expect(parser.parseCode("<?php\n    require_once(__DIR__ . DIRECTORY_SEPARATOR . 'mysql_pdo_test.inc');\n    $db = MySQLPDOTest::factory();\n    MySQLPDOTest::createTestTable($db);\n    // The only purpose of this is to check if emulated and native PS\n  // return the same. If it works for one, it should work for all.\n    // Internal data structures should be the same in both cases.\n    printf(\"Testing emulated PS...\\n\");\n    try {\n        $db->setAttribute(PDO::MYSQL_ATTR_DIRECT_QUERY, 1);\n        if (1 != $db->getAttribute(PDO::MYSQL_ATTR_DIRECT_QUERY))\n            printf(\"[002] Unable to turn on emulated prepared statements\\n\");\n        $stmt = $db->prepare(\"SELECT id, label, '?' as foo FROM test\");\n        $stmt->execute();\n        var_dump($stmt->columnCount());\n        $stmt = $db->query('SELECT * FROM test');\n        var_dump($stmt->columnCount());\n    } catch (PDOException $e) {\n        printf(\"[001] %s [%s] %s\\n\",\n            $e->getMessage(), $db->errorCode(), implode(' ', $db->errorInfo()));\n    }\n    printf(\"Testing native PS...\\n\");\n    try {\n        $db->setAttribute(PDO::MYSQL_ATTR_DIRECT_QUERY, 0);\n        if (0 != $db->getAttribute(PDO::MYSQL_ATTR_DIRECT_QUERY))\n            printf(\"[004] Unable to turn off emulated prepared statements\\n\");\n        $stmt = $db->prepare(\"SELECT id, label, '?' as foo, 'TODO - Stored Procedure' as bar FROM test\");\n        $stmt->execute();\n        var_dump($stmt->columnCount());\n        $stmt = $db->query('SELECT * FROM test');\n        var_dump($stmt->columnCount());\n    } catch (PDOException $e) {\n        printf(\"[003] %s [%s] %s\\n\",\n            $e->getMessage(), $db->errorCode(), implode(' ', $db->errorInfo()));\n    }\n    print \"done!\";\n?>")).toMatchSnapshot();
  });
});
