// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/mysqli/tests/mysqli_query_iterators.phpt
  it("mysqli iterators", function () {
    expect(parser.parseCode("<?php\n    require_once(\"connect.inc\");\n    $tmp    = NULL;\n    $link   = NULL;\n    require('table.inc');\n    echo \"--- Testing default ---\\n\";\n    if (!is_object($res = mysqli_query($link, \"SELECT id FROM test ORDER BY id\")))\n        printf(\"[011] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    else {\n        foreach ($res as $row) {\n            var_dump($row);\n        }\n        echo \"======\\n\";\n        foreach ($res as $row) {\n            var_dump($row);\n        }\n        mysqli_free_result($res);\n        try {\n            foreach ($res as $row) {\n                $row;\n            }\n        } catch (Error $exception) {\n            echo $exception->getMessage() . \"\\n\";\n        }\n    }\n    echo \"--- Testing USE_RESULT ---\\n\";\n    if (!is_object($res = mysqli_query($link, \"SELECT id FROM test ORDER BY id\", MYSQLI_USE_RESULT)))\n        printf(\"[011] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    else {\n        foreach ($res as $row) {\n            var_dump($row);\n        }\n        echo \"======\\n\";\n        foreach ($res as $row) {\n            var_dump($row);\n        }\n        mysqli_free_result($res);\n    }\n    echo \"--- Testing STORE_RESULT ---\\n\";\n    if (!is_object($res = mysqli_query($link, \"SELECT id FROM test ORDER BY id\", MYSQLI_STORE_RESULT)))\n        printf(\"[012] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    else {\n        foreach ($res as $row) {\n            var_dump($row);\n        }\n        echo \"======\\n\";\n        foreach ($res as $row) {\n            var_dump($row);\n        }\n        mysqli_free_result($res);\n    }\n    mysqli_close($link);\n    print \"done!\";\n?>")).toMatchSnapshot();
  });
});
