// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/filter/tests/015.phpt
  it("filter_var() and FILTER_VALIDATE_URL", function () {
    expect(parser.parseCode("<?php\n$values = Array(\n'http://example.com/index.html',\n'http://www.example.com/index.php',\n'http://www.example/img/test.png',\n'http://www.example/img/dir/',\n'http://www.example/img/dir',\n'http://www.thelongestdomainnameintheworldandthensomeandthensomemoreandmore.com/',\n'http://toolongtoolongtoolongtoolongtoolongtoolongtoolongtoolongtoolongtoolong.com',\n'http://eauBcFReEmjLcoZwI0RuONNnwU4H9r151juCaqTI5VeIP5jcYIqhx1lh5vV00l2rTs6y7hOp7rYw42QZiq6VIzjcYrRm8gFRMk9U9Wi1grL8Mr5kLVloYLthHgyA94QK3SaXCATklxgo6XvcbXIqAGG7U0KxTr8hJJU1p2ZQ2mXHmp4DhYP8N9SRuEKzaCPcSIcW7uj21jZqBigsLsNAXEzU8SPXZjmVQVtwQATPWeWyGW4GuJhjP4Q8o0.com',\n'http://kDTvHt1PPDgX5EiP2MwiXjcoWNOhhTuOVAUWJ3TmpBYCC9QoJV114LMYrV3Zl58.kDTvHt1PPDgX5EiP2MwiXjcoWNOhhTuOVAUWJ3TmpBYCC9QoJV114LMYrV3Zl58.kDTvHt1PPDgX5EiP2MwiXjcoWNOhhTuOVAUWJ3TmpBYCC9QoJV114LMYrV3Zl58.CQ1oT5Uq3jJt6Uhy3VH9u3Gi5YhfZCvZVKgLlaXNFhVKB1zJxvunR7SJa.com.',\n'http://kDTvHt1PPDgX5EiP2MwiXjcoWNOhhTuOVAUWJ3TmpBYCC9QoJV114LMYrV3Zl58R.example.com',\n'http://[2001:0db8:0000:85a3:0000:0000:ac1f:8001]',\n'http://[2001:db8:0:85a3:0:0:ac1f:8001]:123/me.html',\n'http://[2001:db8:0:85a3::ac1f:8001]/',\n'http://[::1]',\n'http://cont-ains.h-yph-en-s.com',\n'http://..com',\n'http://a.-bc.com',\n'http://ab.cd-.com',\n'http://-.abc.com',\n'http://abc.-.abc.com',\n'http://underscore_.example.com',\n'http//www.example/wrong/url/',\n'http:/www.example',\n'file:///tmp/test.c',\n'ftp://ftp.example.com/tmp/',\n'/tmp/test.c',\n'/',\n'http://',\n'http:/',\n'http:',\n'http',\n'',\n-1,\narray(),\n'mailto:foo@bar.com',\n'news:news.php.net',\n'file://foo/bar',\n\"http://\\r\\n/bar\",\n\"http://example.com:qq\",\n\"http://example.com:-2\",\n\"http://example.com:65536\",\n\"http://example.com:65537\",\n);\nforeach ($values as $value) {\n    var_dump(filter_var($value, FILTER_VALIDATE_URL));\n}\nvar_dump(filter_var(\"qwe\", FILTER_VALIDATE_URL));\nvar_dump(filter_var(\"http://qwe\", FILTER_VALIDATE_URL));\nvar_dump(filter_var(\"http://\", FILTER_VALIDATE_URL));\nvar_dump(filter_var(\"/tmp/test\", FILTER_VALIDATE_URL));\nvar_dump(filter_var(\"http://www.example.com\", FILTER_VALIDATE_URL));\nvar_dump(filter_var(\"http://www.example.com\", FILTER_VALIDATE_URL, FILTER_FLAG_PATH_REQUIRED));\nvar_dump(filter_var(\"http://www.example.com/path/at/the/server/\", FILTER_VALIDATE_URL, FILTER_FLAG_PATH_REQUIRED));\nvar_dump(filter_var(\"http://www.example.com/index.html\", FILTER_VALIDATE_URL, FILTER_FLAG_QUERY_REQUIRED));\nvar_dump(filter_var(\"http://www.example.com/index.php?a=b&c=d\", FILTER_VALIDATE_URL, FILTER_FLAG_QUERY_REQUIRED));\necho \"Done\\n\";\n?>")).toMatchSnapshot();
  });
});
