// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/pdo_dblib/tests/stringify_uniqueidentifier.phpt
  it("PDO_DBLIB: Uniqueidentifier column data type stringifying", function () {
    expect(parser.parseCode("<?php\nrequire __DIR__ . '/config.inc';\n$testGUID = '82A88958-672B-4C22-842F-216E2B88E72A';\n$testGUIDBinary = base64_decode('WImogitnIkyELyFuK4jnKg==');\n$sql = \"SELECT CAST('$testGUID' as uniqueidentifier) as [guid]\";\n//--------------------------------------------------------------------------------\n// 1. Get and Set the attribute\n//--------------------------------------------------------------------------------\n$db->setAttribute(PDO::DBLIB_ATTR_STRINGIFY_UNIQUEIDENTIFIER, true);\nvar_dump(true === $db->getAttribute(PDO::DBLIB_ATTR_STRINGIFY_UNIQUEIDENTIFIER));\n$db->setAttribute(PDO::DBLIB_ATTR_STRINGIFY_UNIQUEIDENTIFIER, false);\nvar_dump(false === $db->getAttribute(PDO::DBLIB_ATTR_STRINGIFY_UNIQUEIDENTIFIER));\n//--------------------------------------------------------------------------------\n// 2. Binary\n//--------------------------------------------------------------------------------\n$stmt = $db->query($sql);\n$row = $stmt->fetch(PDO::FETCH_ASSOC);\nvar_dump($row['guid'] === $testGUIDBinary);\n//--------------------------------------------------------------------------------\n// 3. PDO::ATTR_STRINGIFY_FETCHES must not affect `uniqueidentifier` representation\n//--------------------------------------------------------------------------------\n$db->setAttribute(PDO::ATTR_STRINGIFY_FETCHES, true);\n$stmt = $db->query($sql);\n$row = $stmt->fetch(PDO::FETCH_ASSOC);\n$db->setAttribute(PDO::ATTR_STRINGIFY_FETCHES, false);\nvar_dump($row['guid'] === $testGUIDBinary);\n//--------------------------------------------------------------------------------\n// 4. Stringifying\n// ! With TDS protocol version <7.0 binary will be returned and the test will fail !\n// TODO: something from PDO::ATTR_SERVER_VERSION, PDO::ATTR_CLIENT_VERSION or PDO::ATTR_SERVER_INFO should be used\n// to get TDS version and skip this test in this case.\n//--------------------------------------------------------------------------------\n$db->setAttribute(PDO::DBLIB_ATTR_STRINGIFY_UNIQUEIDENTIFIER, true);\n$stmt = $db->query($sql);\n$row = $stmt->fetch(PDO::FETCH_ASSOC);\nvar_dump($row['guid'] === $testGUID);\nvar_dump($row['guid']);\n?>")).toMatchSnapshot();
  });
});
