// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/oci8/tests/lob_029.phpt
  it("reading/writing BFILE LOBs", function () {
    expect(parser.parseCode("<?php\nrequire(__DIR__.'/connect.inc');\n$realdirname = \"/tmp\";  // Use /tmp because a local dir can give ORA-22288 depending on perms\n$realfilename1 = \"oci8bfiletest1.txt\";\n$fullname1 = $realdirname.\"/\".$realfilename1;\n$realfilename2 = \"oci8bfiletest2.txt\";\n$fullname2 = $realdirname.\"/\".$realfilename2;\n$realfilename3 = \"oci8bfiletest3.txt\";\n$fullname3 = $realdirname.\"/\".$realfilename3;\n// Setup\n$s = oci_parse($c, \"drop table FileTest\");\n@oci_execute($s);\n$s = oci_parse($c, \"drop directory TestDir\");\n@oci_execute($s);\n$s = oci_parse($c, \"create directory TestDir as '$realdirname'\");\noci_execute($s);\nfile_put_contents($fullname1, 'Some text in the bfile 1');\nfile_put_contents($fullname2, 'Some text in the bfile 2');\nfile_put_contents($fullname3, 'Some text in the bfile 3');\n$s = oci_parse($c, \"create table FileTest (FileNum number, FileDesc varchar2(30), Image bfile)\");\noci_execute($s);\n$s = oci_parse($c, \"insert into FileTest (FileNum, FileDesc, Image) values (1, 'Description 1', bfilename('TESTDIR', '$realfilename1'))\");\noci_execute($s);\n$s = oci_parse($c, \"insert into FileTest (FileNum, FileDesc, Image) values (2, 'Description 2', bfilename('TESTDIR', '$realfilename2'))\");\noci_execute($s);\n$s = oci_parse($c, \"insert into FileTest (FileNum, FileDesc, Image) values (3, 'Description 3', bfilename('TESTDIR', '$realfilename3'))\");\noci_execute($s);\n// Run tests\necho \"Test 1. Check how many rows in the table\\n\";\n$s = oci_parse($c, \"select count(*) numrows from FileTest\");\noci_execute($s);\noci_fetch_all($s, $res);\nvar_dump($res);\necho \"Test 2\\n\";\n$s = oci_parse($c, \"select * from FileTest order by FileNum\");\noci_execute($s);\noci_fetch_all($s, $res);\nvar_dump($res);\necho \"Test 3\\n\";\n$d = oci_new_descriptor($c, OCI_D_FILE);\n$s = oci_parse($c, \"insert into FileTest (FileNum, FileDesc, Image) values (2, 'Description 2', bfilename('TESTDIR', '$realfilename1')) returning Image into :im\");\noci_bind_by_name($s, \":im\", $d, -1, OCI_B_BFILE);\noci_execute($s);\n$r = $d->read(40);\nvar_dump($r);\nunlink($fullname1);\nunlink($fullname2);\nunlink($fullname3);\n$s = oci_parse($c, \"drop table FileTest\");\noci_execute($s);\n$s = oci_parse($c, \"drop directory TestDir\");\noci_execute($s);\necho \"Done\\n\";\n?>")).toMatchSnapshot();
  });
});
