// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/oci8/tests/lob_035.phpt
  it("oci_lob_copy() - 2", function () {
    expect(parser.parseCode("<?php\nrequire __DIR__.'/connect.inc';\nrequire __DIR__.'/create_table.inc';\n$ora_sql = \"INSERT INTO\n                       \".$schema.$table_name.\" (id, blob)\n                      VALUES (1, empty_blob())\n                      RETURNING\n                               blob\n                      INTO :v_blob \";\n$statement = oci_parse($c,$ora_sql);\n$blob = oci_new_descriptor($c,OCI_D_LOB);\noci_bind_by_name($statement,\":v_blob\", $blob,-1,OCI_B_BLOB);\noci_execute($statement, OCI_DEFAULT);\necho \"Writing blob\\n\";\nvar_dump($blob->write(\"some string here. string, I said\"));\noci_commit($c);\n$ora_sql = \"INSERT INTO\n                       \".$schema.$table_name.\" (id, blob)\n                      VALUES (2, empty_blob())\n                      RETURNING\n                               blob\n                      INTO :v_blob \";\n$statement = oci_parse($c,$ora_sql);\n$blob = oci_new_descriptor($c,OCI_D_LOB);\noci_bind_by_name($statement,\":v_blob\", $blob,-1,OCI_B_BLOB);\noci_execute($statement, OCI_DEFAULT);\noci_commit($c);\n$select_sql = \"SELECT blob FROM \".$schema.$table_name.\" WHERE id = 1\";\n$s = oci_parse($c, $select_sql);\noci_execute($s);\n$row1 = oci_fetch_array($s);\n$select_sql = \"SELECT blob FROM \".$schema.$table_name.\" WHERE id = 2 FOR UPDATE\";\n$s = oci_parse($c, $select_sql);\noci_execute($s, OCI_DEFAULT);\n$row2 = oci_fetch_array($s);\n$dummy = oci_new_descriptor($c, OCI_D_LOB);\n//--------------------------------------------------\necho \"\\noci_lob_copy invalid args\\n\";\nvar_dump(oci_lob_copy($dummy, $row1[0]));\nvar_dump(oci_lob_copy($row2[0], $dummy));\nvar_dump(oci_lob_copy($row2[0], $row1[0], 0));\nvar_dump(oci_lob_copy($row2[0], $row1[0], 100000));\ntry {\n    var_dump(oci_lob_copy($row2[0], $row1[0], -1));\n} catch (ValueError $e) {\n    echo $e->getMessage(), \"\\n\";\n}\n//--------------------------------------------------\necho \"\\noci_lob_size tests\\n\";\nvar_dump(oci_lob_size($row2[0]));\nunset($dummy->descriptor);\nvar_dump(oci_lob_size($dummy));\noci_rollback($c);\n//--------------------------------------------------\necho \"\\nQuery test\\n\";\n$select_sql = \"SELECT blob FROM \".$schema.$table_name.\" WHERE id = 2 FOR UPDATE\";\n$s = oci_parse($c, $select_sql);\noci_execute($s, OCI_DEFAULT);\nvar_dump($row2 = oci_fetch_array($s, OCI_RETURN_LOBS));\nrequire __DIR__.'/drop_table.inc';\necho \"Done\\n\";\n?>")).toMatchSnapshot();
  });
});
