// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/standard/tests/array/rsort_basic.phpt
  it("Test rsort() function : basic functionality", function () {
    expect(parser.parseCode("<?php\n/*\n * Test basic functionality of rsort()\n */\necho \"*** Testing rsort() : basic functionality ***\\n\";\n// associative array containing unsorted string values\n$unsorted_strings = array(\n    \"l\" => \"lemon\", \"o\" => \"orange\",\n    \"O\" => \"Orange\", \"O1\" => \"Orange1\", \"o2\" => \"orange2\", \"O3\" => \"Orange3\", \"o20\" => \"orange20\",\n    \"b\" => \"banana\",\n);\n// array with default keys containing unsorted numeric values\n$unsorted_numerics =  array( 100, 33, 555, 22 );\necho \"\\n-- Testing rsort() by supplying string array, 'flag' value is default --\\n\";\n$temp_array = $unsorted_strings;\nvar_dump( rsort($temp_array) );\nvar_dump( $temp_array);\necho \"\\n-- Testing rsort() by supplying numeric array, 'flag' value is default --\\n\";\n$temp_array = $unsorted_numerics;\nvar_dump( rsort($temp_array) );\nvar_dump( $temp_array);\necho \"\\n-- Testing rsort() by supplying string array, 'flag' = SORT_REGULAR --\\n\";\n$temp_array = $unsorted_strings;\nvar_dump( rsort($temp_array, SORT_REGULAR) );\nvar_dump( $temp_array);\necho \"\\n-- Testing rsort() by supplying numeric array, 'flag' = SORT_REGULAR --\\n\";\n$temp_array = $unsorted_numerics;\nvar_dump( rsort($temp_array, SORT_REGULAR) );\nvar_dump( $temp_array);\necho \"\\n-- Testing rsort() by supplying string array, 'flag' = SORT_STRING --\\n\";\n$temp_array = $unsorted_strings;\nvar_dump( rsort($temp_array, SORT_STRING) );\nvar_dump( $temp_array);\necho \"\\n-- Testing rsort() by supplying string array (case insensitive), 'flag' = SORT_STRING|SORT_FLAG_CASE --\\n\";\n$temp_array = $unsorted_strings;\nvar_dump( rsort($temp_array, SORT_STRING|SORT_FLAG_CASE) ); // expecting : bool(true)\nvar_dump( $temp_array);\necho \"\\n-- Testing rsort() by supplying string array (natural), 'flag' = SORT_NATURAL --\\n\";\n$temp_array = $unsorted_strings;\nvar_dump( rsort($temp_array, SORT_NATURAL) ); // expecting : bool(true)\nvar_dump( $temp_array);\necho \"\\n-- Testing rsort() by supplying string array (natural, case insensitive), 'flag' = SORT_NATURAL|SORT_FLAG_CASE --\\n\";\n$temp_array = $unsorted_strings;\nvar_dump( rsort($temp_array, SORT_NATURAL|SORT_FLAG_CASE) ); // expecting : bool(true)\nvar_dump( $temp_array);\necho \"\\n-- Testing rsort() by supplying numeric array, 'flag' = SORT_NUMERIC --\\n\";\n$temp_array = $unsorted_numerics;\nvar_dump( rsort($temp_array, SORT_NUMERIC) );\nvar_dump( $temp_array);\necho \"Done\";\n?>")).toMatchSnapshot();
  });
});
