// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/phar/tests/022.phpt
  it("Phar: stream stat", function () {
    expect(parser.parseCode("<?php\n$fname = __DIR__ . '/' . basename(__FILE__, '.php') . '.phar.php';\n$pname = 'phar://' . $fname;\n$file = \"<?php\nPhar::mapPhar('hio');\n__HALT_COMPILER(); ?>\";\n$files = array();\n$files['a'] = 'abcdefg';\ninclude 'files/phar_test.inc';\ninclude $fname;\n$fp = fopen('phar://hio/a', 'r');\nvar_dump(ftell($fp));\necho 'fseek($fp, 1)';var_dump(fseek($fp, 1));\nvar_dump(ftell($fp));\necho 'fseek($fp, 1, SEEK_CUR)';var_dump(fseek($fp, 1, SEEK_CUR));\nvar_dump(ftell($fp));\necho 'fseek($fp, -1, SEEK_CUR)';var_dump(fseek($fp, -1, SEEK_CUR));\nvar_dump(ftell($fp));\necho 'fseek($fp, -1, SEEK_END)';var_dump(fseek($fp, -1, SEEK_END));\nvar_dump(ftell($fp));\necho 'fseek($fp, -8, SEEK_END)';var_dump(fseek($fp, -8, SEEK_END));\nvar_dump(ftell($fp));\necho 'fseek($fp, -7, SEEK_END)';var_dump(fseek($fp, -7, SEEK_END));\nvar_dump(ftell($fp));\necho 'fseek($fp, 0, SEEK_END)';var_dump(fseek($fp, 0, SEEK_END));\nvar_dump(ftell($fp));\necho 'fseek($fp, 1, SEEK_END)';var_dump(fseek($fp, 1, SEEK_END));\nvar_dump(ftell($fp));\necho 'fseek($fp, -8, SEEK_END)';var_dump(fseek($fp, -8, SEEK_END));\nvar_dump(ftell($fp));\necho 'fseek($fp, 6)';var_dump(fseek($fp, 6));\nvar_dump(ftell($fp));\necho 'fseek($fp, 8)';var_dump(fseek($fp, 8));\nvar_dump(ftell($fp));\necho 'fseek($fp, -1)';var_dump(fseek($fp, -1));\nvar_dump(ftell($fp));\necho \"next\\n\";\nfseek($fp, 4);\nvar_dump(ftell($fp));\necho 'fseek($fp, -5, SEEK_CUR)';var_dump(fseek($fp, -5, SEEK_CUR));\nvar_dump(ftell($fp));\nfseek($fp, 4);\nvar_dump(ftell($fp));\necho 'fseek($fp, 5, SEEK_CUR)';var_dump(fseek($fp, 5, SEEK_CUR));\nvar_dump(ftell($fp));\nfseek($fp, 4);\nvar_dump(ftell($fp));\necho 'fseek($fp, -4, SEEK_CUR)';var_dump(fseek($fp, -4, SEEK_CUR));\nvar_dump(ftell($fp));\nfseek($fp, 4);\nvar_dump(ftell($fp));\necho 'fseek($fp, 3, SEEK_CUR)';var_dump(fseek($fp, 3, SEEK_CUR));\nvar_dump(ftell($fp));\nfclose($fp);\n?>")).toMatchSnapshot();
  });
});
