// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/mysqli/tests/mysqli_real_escape_string_unicode.phpt
  it("mysqli_real_escape_string()", function () {
    expect(parser.parseCode("<?php\n    require_once(\"connect.inc\");\n    require('table.inc');\n    if ('фу\\\\\\\\бар' !== ($tmp = mysqli_real_escape_string($link, 'фу\\\\бар')))\n        printf(\"[004] Expecting фу\\\\\\\\бар, got %s\\n\", $tmp);\n    if ('бар\\\"фус' !== ($tmp = mysqli_real_escape_string($link, 'бар\"фус')))\n        printf(\"[005] Expecting бар\\\"фус, got %s\\n\", $tmp);\n    if (\"лала\\'лали\" !== ($tmp = mysqli_real_escape_string($link, \"лала'лали\")))\n        printf(\"[006] Expecting лала'лали, got %s\\n\", $tmp);\n    if (\"абра\\\\nкадабра\" !== ($tmp = mysqli_real_escape_string($link, \"абра\\nкадабра\")))\n        printf(\"[007] Expecting абра\\\\nкадабра, got %s\\n\", $tmp);\n    if (\"манда\\\\rин\" !== ($tmp = mysqli_real_escape_string($link, \"манда\\rин\")))\n        printf(\"[008] Expecting \\\\r, got %s\\n\", $tmp);\n    if (\"иху\\\\0аху\" !== ($tmp = mysqli_real_escape_string($link, \"иху\" . chr(0) . \"аху\")))\n        printf(\"[009] Expecting %s, got %s\\n\", \"иху\\\\0аху\", $tmp);\n    if (($exp='абра\\\\\\\\ка\\\"да\\\\'.\"'\".'бра\\Zсим\\\\nсала\\\\rби\\\\0м') !==\n        ($tmp = mysqli_real_escape_string($link, \"абра\\\\ка\\\"да'бра\\032сим\\nсала\\rби\" . chr(0) . \"м\")))\n    {\n        printf(\"[010] Expecting %s, got %s\\n\", $exp, $tmp, var_dump($exp, $tmp));\n    }\n    if ('富\\\\\\\\酒吧' !== ($tmp = mysqli_real_escape_string($link, '富\\\\酒吧')))\n        printf(\"[011] Expecting 富\\\\\\\\酒吧, got %s\\n\", $tmp);\n    if ('酒吧\\\"小题大做' !== ($tmp = mysqli_real_escape_string($link, '酒吧\"小题大做')))\n        printf(\"[012] Expecting 酒吧\\\"小题大做, got %s\\n\", $tmp);\n    if (\"拉拉\\'西雅图\" !== ($tmp = mysqli_real_escape_string($link, \"拉拉'西雅图\")))\n        printf(\"[013] Expecting 拉拉'西雅图, got %s\\n\", $tmp);\n    if (\"阿卜拉\\\\n轻\" !== ($tmp = mysqli_real_escape_string($link, \"阿卜拉\\n轻\")))\n        printf(\"[014] Expecting 阿卜拉\\\\n轻, got %s\\n\", $tmp);\n    if (\"张明安\\\\r在\" !== ($tmp = mysqli_real_escape_string($link, \"张明安\\r在\")))\n        printf(\"[015] Expecting 张明安\\\\r在, got %s\\n\", $tmp);\n    if (\"竺可桢\\\\0空调器\" !== ($tmp = mysqli_real_escape_string($link, \"竺可桢\" . chr(0) . \"空调器\")))\n        printf(\"[016] Expecting %s, got %s\\n\", \"竺可桢\\\\0空调器\", $tmp);\n    if (($exp='阿卜拉\\\\\\\\嘉\\\"达丰\\\\'.\"'\".'乳罩\\Z辛\\\\n萨拉\\\\r毕\\\\0米') !==\n        ($tmp = mysqli_real_escape_string($link, \"阿卜拉\\\\嘉\\\"达丰'乳罩\\032辛\\n萨拉\\r毕\" . chr(0) . \"米\")))\n    {\n        printf(\"[017] Expecting %s, got %s\\n\", $exp, $tmp, var_dump($exp, $tmp));\n    }\n    mysqli_close($link);\n    try {\n        mysqli_real_escape_string($link, 'foo');\n    } catch (Error $exception) {\n        echo $exception->getMessage() . \"\\n\";\n    }\n    print \"done!\";\n?>")).toMatchSnapshot();
  });
});
