// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/phar/tests/phar_isvalidpharfilename.phpt
  it("Phar: Phar::isValidPharFilename()", function () {
    expect(parser.parseCode("<?php\nchdir(__DIR__);\nvar_dump(Phar::isValidPharFilename('*'));\nvar_dump(Phar::isValidPharFilename('*', true));\nvar_dump(Phar::isValidPharFilename('*', false));\necho \"\\nboo.phar\\n\";\nvar_dump(Phar::isValidPharFilename('boo.phar'));\nvar_dump(Phar::isValidPharFilename('boo.phar', true));\nvar_dump(Phar::isValidPharFilename('boo.phar', false));\necho \"\\nboo.tar\\n\";\nvar_dump(Phar::isValidPharFilename('boo.tar'));\nvar_dump(Phar::isValidPharFilename('boo.tar', true));\nvar_dump(Phar::isValidPharFilename('boo.tar', false));\necho \"\\nboo.phar.tar\\n\";\nvar_dump(Phar::isValidPharFilename('boo.phar.tar'));\nvar_dump(Phar::isValidPharFilename('boo.phar.tar', true));\nvar_dump(Phar::isValidPharFilename('boo.phar.tar', false));\nmkdir(__DIR__ . '/.phar');\necho \"\\n.phar/boo.tar\\n\";\nvar_dump(Phar::isValidPharFilename('.phar/boo.tar'));\nvar_dump(Phar::isValidPharFilename('.phar/boo.tar', true));\nvar_dump(Phar::isValidPharFilename('.phar/boo.tar', false));\necho \"\\n.phar.tar\\n\";\nvar_dump(Phar::isValidPharFilename('.phar.tar'));\nvar_dump(Phar::isValidPharFilename('.phar.tar', true));\nvar_dump(Phar::isValidPharFilename('.phar.tar', false));\necho \"\\n.phar.phar\\n\";\nvar_dump(Phar::isValidPharFilename('.phar.phar'));\nvar_dump(Phar::isValidPharFilename('.phar.phar', true));\nvar_dump(Phar::isValidPharFilename('.phar.phar', false));\necho \"\\n.phar.phart\\n\";\nvar_dump(Phar::isValidPharFilename('.phar.phart'));\nvar_dump(Phar::isValidPharFilename('.phar.phart', true));\nvar_dump(Phar::isValidPharFilename('.phar.phart', false));\necho \"\\nmy.pharmy\\n\";\nvar_dump(Phar::isValidPharFilename('my.pharmy'));\nvar_dump(Phar::isValidPharFilename('my.pharmy', true));\nvar_dump(Phar::isValidPharFilename('my.pharmy', false));\necho \"\\nphar.zip\\n\";\nvar_dump(Phar::isValidPharFilename('phar.zip'));\nvar_dump(Phar::isValidPharFilename('phar.zip', true));\nvar_dump(Phar::isValidPharFilename('phar.zip', false));\necho \"\\nphar.zip.phar\\n\";\nvar_dump(Phar::isValidPharFilename('phar.zip.phar'));\nvar_dump(Phar::isValidPharFilename('phar.zip.phar', true));\nvar_dump(Phar::isValidPharFilename('phar.zip.phar', false));\necho \"\\ndir.phar.php\\n\";\nvar_dump(Phar::isValidPharFilename('dir.phar.php'));\nvar_dump(Phar::isValidPharFilename('dir.phar.php', true));\nvar_dump(Phar::isValidPharFilename('dir.phar.php', false));\n?>")).toMatchSnapshot();
  });
});
