// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/mysqli/tests/mysqli_pconnect.phpt
  it("mysqli_pconnect()", function () {
    expect(parser.parseCode("<?php\n    require_once(\"connect.inc\");\n    $host = 'p:' . $host;\n    if (!$link = my_mysqli_connect($host, $user, $passwd, $db, $port, $socket))\n        printf(\"[002] Cannot connect to the server using host=%s, user=%s, passwd=***, dbname=%s, port=%s, socket=%s\\n\",\n            $host, $user, $db, $port, $socket);\n    mysqli_close($link);\n    $num = 20;\n    $connections = array();\n    for ($i = 0; $i < $num; $i++) {\n        if (!$link = my_mysqli_connect($host, $user, $passwd, $db, $port, $socket))\n            printf(\"[003] Connect failed, [%d] %s\\n\", mysqli_connect_errno(), mysqli_connect_error());\n        $connections[] = $link;\n    }\n    while (count($connections)) {\n        do {\n            $index = mt_rand(0, $num);\n        } while (!isset($connections[$index]));\n        mysqli_close($connections[$index]);\n        unset($connections[$index]);\n    }\n    $connections = array();\n    $num = 20;\n    for ($i = 0; $i < $num; $i++) {\n        if (!$link = my_mysqli_connect($host, $user, $passwd, $db, $port, $socket))\n            printf(\"[004] Connect failed, [%d] %s\\n\", mysqli_connect_errno(), mysqli_connect_error());\n        $connections[] = $link;\n    }\n    $left = $num;\n    while (count($connections) && $left > 0) {\n        do {\n            $index = mt_rand(0, $num);\n        } while (!isset($connections[$index]) && $left > 0);\n        if (mt_rand(0, 1) > 0) {\n            $left--;\n            mysqli_close($connections[$index]);\n            unset($connections[$index]);\n        } else {\n            $left--;\n            if (!$connections[$index] = my_mysqli_connect($host, $user, $passwd, $db, $port, $socket))\n                printf(\"[004] Connect failed, [%d] %s\\n\", mysqli_connect_errno(), mysqli_connect_error());\n        }\n        flush();\n    }\n    while (count($connections)) {\n        do {\n            $index = mt_rand(0, $num);\n        } while (!isset($connections[$index]));\n        mysqli_close($connections[$index]);\n        unset($connections[$index]);\n    }\n    print \"done!\";\n?>")).toMatchSnapshot();
  });
});
