// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/curl/tests/curl_file_upload.phpt
  it("CURL file uploading", function () {
    expect(parser.parseCode("<?php\nfunction testcurl($ch, $name, $mime = '', $postname = '')\n{\n    if(!empty($postname)) {\n        $file = new CurlFile($name, $mime, $postname);\n    } else if(!empty($mime)) {\n        $file = new CurlFile($name, $mime);\n    } else {\n        $file = new CurlFile($name);\n    }\n    curl_setopt($ch, CURLOPT_POSTFIELDS, array(\"file\" => $file));\n    var_dump(curl_exec($ch));\n}\ninclude 'server.inc';\n$host = curl_cli_server_start();\n$ch = curl_init();\ncurl_setopt($ch, CURLOPT_URL, \"{$host}/get.inc?test=file\");\ncurl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);\ntestcurl($ch, __DIR__ . '/curl_testdata1.txt');\ntestcurl($ch, __DIR__ . '/curl_testdata1.txt', 'text/plain');\ntestcurl($ch, __DIR__ . '/curl_testdata1.txt', '', 'foo.txt');\ntestcurl($ch, __DIR__ . '/curl_testdata1.txt', 'text/plain', 'foo.txt');\n$file = new CurlFile(__DIR__ . '/curl_testdata1.txt');\n$file->setMimeType('text/plain');\nvar_dump($file->getMimeType());\nvar_dump($file->getFilename());\ncurl_setopt($ch, CURLOPT_POSTFIELDS, array(\"file\" => $file));\nvar_dump(curl_exec($ch));\n$file = curl_file_create(__DIR__ . '/curl_testdata1.txt');\n$file->setPostFilename('foo.txt');\nvar_dump($file->getPostFilename());\ncurl_setopt($ch, CURLOPT_POSTFIELDS, array(\"file\" => $file));\nvar_dump(curl_exec($ch));\ntry {\n    curl_setopt($ch, CURLOPT_SAFE_UPLOAD, 0);\n} catch (ValueError $exception) {\n    echo $exception->getMessage() . \"\\n\";\n}\n$params = array('file' => '@' . __DIR__ . '/curl_testdata1.txt');\ncurl_setopt($ch, CURLOPT_POSTFIELDS, $params);\nvar_dump(curl_exec($ch));\ncurl_setopt($ch, CURLOPT_SAFE_UPLOAD, true);\n$params = array('file' => '@' . __DIR__ . '/curl_testdata1.txt');\ncurl_setopt($ch, CURLOPT_POSTFIELDS, $params);\nvar_dump(curl_exec($ch));\ncurl_setopt($ch, CURLOPT_URL, \"{$host}/get.inc?test=post\");\n$params = array('file' => '@' . __DIR__ . '/curl_testdata1.txt');\ncurl_setopt($ch, CURLOPT_POSTFIELDS, $params);\nvar_dump(curl_exec($ch));\ncurl_close($ch);\n?>")).toMatchSnapshot();
  });
});
