// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/mysqli/tests/mysqli_change_user_oo.phpt
  it("mysqli->change_user()", function () {
    expect(parser.parseCode("<?php\n    include_once(\"connect.inc\");\n    $link\t= NULL;\n    $tmp\t= NULL;\n    if (!$mysqli = new my_mysqli($host, $user, $passwd, $db, $port, $socket))\n        printf(\"[001] Cannot connect to the server using host=%s, user=%s, passwd=***, dbname=%s, port=%s, socket=%s\\n\",\n            $host, $user, $db, $port, $socket);\n    if (false !== ($tmp = $mysqli->change_user($user . '_unknown_really', $passwd . 'non_empty', $db)))\n        printf(\"[006] Expecting false, got %s/%s\\n\", gettype($tmp), $tmp);\n    if (false !== ($tmp = $mysqli->change_user($user, $passwd . '_unknown_really', $db)))\n        printf(\"[007] Expecting false, got %s/%s\\n\", gettype($tmp), $tmp);\n    if (false !== ($tmp = $mysqli->change_user($user, $passwd, $db . '_unknown_really')))\n        printf(\"[008] Expecting false, got %s/%s\\n\", gettype($tmp), $tmp);\n    // Reconnect because after 3 failed change_user attempts, the server blocks you off.\n    if (!$mysqli = new my_mysqli($host, $user, $passwd, $db, $port, $socket))\n        printf(\"[001] Cannot connect to the server using host=%s, user=%s, passwd=***, dbname=%s, port=%s, socket=%s\\n\",\n            $host, $user, $db, $port, $socket);\n    if (!$mysqli->query('SET @mysqli_change_user_test_var=1'))\n        printf(\"[009] Failed to set test variable: [%d] %s\\n\", $mysqli->errno, $mysqli->error);\n    if (!$res = $mysqli->query('SELECT @mysqli_change_user_test_var AS test_var'))\n        printf(\"[010] [%d] %s\\n\", $mysqli->errno, $mysqli->error);\n    $tmp = $res->fetch_assoc();\n    $res->free_result();\n    if (1 != $tmp['test_var'])\n        printf(\"[011] Cannot set test variable\\n\");\n    if (true !== ($tmp = $mysqli->change_user($user, $passwd, $db)))\n        printf(\"[012] Expecting true, got %s/%s\\n\", gettype($tmp), $tmp);\n    if (!$res = $mysqli->query('SELECT database() AS dbname, user() AS user'))\n        printf(\"[013] [%d] %s\\n\", $mysqli->errno, $mysqli->error);\n    $tmp = $res->fetch_assoc();\n    $res->free_result();\n    if (substr($tmp['user'], 0, strlen($user)) !== $user)\n        printf(\"[014] Expecting user %s, got user() %s\\n\", $user, $tmp['user']);\n    if ($tmp['dbname'] != $db)\n        printf(\"[015] Expecting database %s, got database() %s\\n\", $db, $tmp['dbname']);\n    if (!$res = $mysqli->query('SELECT @mysqli_change_user_test_var AS test_var'))\n        printf(\"[016] [%d] %s\\n\", $mysqli->errno, $mysqli->error);\n    $tmp = $res->fetch_assoc();\n    $res->free_result();\n    if (NULL !== $tmp['test_var'])\n        printf(\"[017] Test variable is still set!\\n\");\n    $mysqli->close();\n    if (false !== ($tmp = @$mysqli->change_user($user, $passwd, $db)))\n        printf(\"[018] Expecting false, got %s/%s\\n\", gettype($tmp), $tmp);\n    print \"done!\";\n?>")).toMatchSnapshot();
  });
});
