// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/mysqli/tests/mysqli_fetch_column_libmysql.phpt
  it("mysqli_fetch_column()", function () {
    expect(parser.parseCode("<?php\nrequire_once \"connect.inc\";\nrequire 'table.inc';\nmysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);\n$res = mysqli_query($link, \"SELECT id, label FROM test ORDER BY id LIMIT 1\");\nprint \"[001]\\n\";\nvar_dump(mysqli_fetch_column($res));\nprint \"[002]\\n\";\nvar_dump(mysqli_fetch_column($res));\n$res = mysqli_query($link, \"SELECT\n    1 AS a,\n    2 AS a\n\");\nprint \"[003]\\n\";\nvar_dump(mysqli_fetch_column($res, 0));\n$res = mysqli_query($link, \"SELECT\n    1 AS a,\n    2 AS a\n\");\nprint \"[004]\\n\";\nvar_dump(mysqli_fetch_column($res, 1));\n$res = mysqli_query($link, \"SELECT\n    1 AS a,\n    2 AS a,\n    3\n\");\nprint \"[005]\\n\";\nvar_dump(mysqli_fetch_column($res, 2));\n$res = mysqli_query($link, \"SELECT\n    1 AS a,\n    2 AS a,\n    3,\n    NULL AS d\n\");\nprint \"[006]\\n\";\nvar_dump(mysqli_fetch_column($res, 3));\n$res = mysqli_query($link, \"SELECT\n    1 AS a,\n    2 AS a,\n    3,\n    NULL AS d,\n    true AS e\n\");\nprint \"[007]\\n\";\nvar_dump(mysqli_fetch_column($res, 4));\n$res = mysqli_query($link, \"SELECT\n    1.42 AS a\n\");\nprint \"[008]\\n\";\nvar_dump(mysqli_fetch_column($res, 0));\n$res = mysqli_query($link, \"SELECT\n    1.42E0 AS a\n\");\nprint \"[009]\\n\";\nvar_dump(mysqli_fetch_column($res, 0));\n$res = mysqli_query($link, \"SELECT id, label FROM test ORDER BY id LIMIT 1\");\nprint \"[010]\\n\";\ntry {\n    var_dump(mysqli_fetch_column($res, -1));\n} catch (\\ValueError $e) {\n    echo $e->getMessage(), \\PHP_EOL;\n}\n$res = mysqli_query($link, \"SELECT id, label FROM test ORDER BY id LIMIT 1\");\nprint \"[011]\\n\";\ntry {\n    var_dump(mysqli_fetch_column($res, 2));\n} catch (\\ValueError $e) {\n    echo $e->getMessage(), \\PHP_EOL;\n}\nmysqli_free_result($res);\ntry {\n\tmysqli_fetch_column($res);\n} catch (Error $exception) {\n\techo $exception->getMessage() . \"\\n\";\n}\n$res = $link->query(\"SELECT id, label FROM test ORDER BY id LIMIT 2\");\nprint \"[012]\\n\";\nvar_dump($res->fetch_column());\nprint \"[013]\\n\";\nvar_dump($res->fetch_column(1));\nmysqli_close($link);\n?>")).toMatchSnapshot();
  });
});
