// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/date/tests/date_time_immutable.phpt
  it("Tests for DateTimeImmutable.", function () {
    expect(parser.parseCode("<?php\n$tz = new DateTimeZone(\"Asia/Tokyo\");\n$current = \"2012-12-27 16:24:08\";\nfunction dump($a, $b, $c)\n{\n    echo 'orig:    ', $a->format('Y-m-d H:i:s e'), \"\\n\";\n    echo 'copy:    ', $b->format('Y-m-d H:i:s e'), \"\\n\";\n    echo 'changed: ', $c->format('Y-m-d H:i:s e'), \"\\n\";\n}\necho \"modify():\\n\";\n$v = date_create_immutable($current);\n$z = $v;\n$x = $z->modify(\"+2 days\");\ndump($v, $z, $x);\n$v = date_create($current);\n$z = $v;\n$x = $z->modify(\"+2 days\");\ndump($v, $z, $x);\necho \"\\nadd():\\n\";\n$v = date_create_immutable($current);\n$z = $v;\n$x = $z->add(new DateInterval(\"P2DT2S\"));\ndump($v, $z, $x);\n$v = date_create($current);\n$z = $v;\n$x = $z->add(new DateInterval(\"P2DT2S\"));\ndump($v, $z, $x);\necho \"\\nsub():\\n\";\n$v = date_create_immutable($current);\n$z = $v;\n$x = $z->sub(new DateInterval(\"P2DT2S\"));\ndump($v, $z, $x);\n$v = date_create($current);\n$z = $v;\n$x = $z->sub(new DateInterval(\"P2DT2S\"));\ndump($v, $z, $x);\necho \"\\nsetTimezone():\\n\";\n$v = date_create_immutable($current);\n$z = $v;\n$x = $z->setTimezone($tz);\ndump($v, $z, $x);\n$v = date_create($current);\n$z = $v;\n$x = $z->setTimezone($tz);\ndump($v, $z, $x);\n$v = new DateTimeImmutable($current);\n$z = $v;\n$x = $z->setTimezone($tz);\ndump($v, $z, $x);\necho \"\\nsetTime():\\n\";\n$v = date_create_immutable($current);\n$z = $v;\n$x = $z->setTime(5, 7, 19);\ndump($v, $z, $x);\n$v = date_create($current);\n$z = $v;\n$x = $z->setTime(5, 7, 19);\ndump($v, $z, $x);\necho \"\\nsetDate():\\n\";\n$v = date_create_immutable($current);\n$z = $v;\n$x = $z->setDate(5, 7, 19);\ndump($v, $z, $x);\n$v = date_create($current);\n$z = $v;\n$x = $z->setDate(5, 7, 19);\ndump($v, $z, $x);\necho \"\\nsetIsoDate():\\n\";\n$v = date_create_immutable($current);\n$z = $v;\n$x = $z->setIsoDate(2012, 2, 6);\ndump($v, $z, $x);\n$v = date_create($current);\n$z = $v;\n$x = $z->setIsoDate(2012, 2, 6);\ndump($v, $z, $x);\necho \"\\nsetTimestamp():\\n\";\n$v = date_create_immutable($current);\n$z = $v;\n$x = $z->setTimestamp(2012234222);\ndump($v, $z, $x);\n$v = date_create($current);\n$z = $v;\n$x = $z->setTimestamp(2012234222);\ndump($v, $z, $x);\n?>")).toMatchSnapshot();
  });
});
