// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/mysqli/tests/mysqli_expire_password.phpt
  it("MySQL 5.6 / MariaDB 10.4.3 EXPIRE PASSWORD protocol change", function () {
    expect(parser.parseCode("<?php\n    require_once('connect.inc');\n    require_once('table.inc');\n    /* default */\n    if (!$link = my_mysqli_connect($host, 'expiretest', 'expiredpassword', $db, $port, $socket)) {\n        printf(\"[001] Cannot connect [%d] %s\\n\",\n            mysqli_connect_errno(), mysqli_connect_error());\n    } else {\n        $link->query(\"SELECT id FROM test WHERE id = 1\");\n        printf(\"[002] Connect should fail, [%d] %s\\n\", $link->errno, $link->error);\n    }\n    /* explicitly requesting default */\n    $link = mysqli_init();\n    $link->options(MYSQLI_OPT_CAN_HANDLE_EXPIRED_PASSWORDS, 0);\n    if (!my_mysqli_real_connect($link, $host, 'expiretest', 'expiredpassword', $db, $port, $socket)) {\n        printf(\"[003] Cannot connect [%d] %s\\n\",\n            mysqli_connect_errno(), mysqli_connect_error());\n    } else {\n        $link->query(\"SELECT id FROM test WHERE id = 1\");\n        printf(\"[004] Connect should fail, [%d] %s\\n\", $link->errno, $link->error);\n    }\n    /* allow connect */\n    $link = mysqli_init();\n    $link->options(MYSQLI_OPT_CAN_HANDLE_EXPIRED_PASSWORDS, 1);\n    if (!my_mysqli_real_connect($link, $host, 'expiretest', 'expiredpassword', $db, $port, $socket)) {\n        printf(\"[005] Cannot connect [%d] %s\\n\",\n            mysqli_connect_errno(), mysqli_connect_error());\n    } else {\n        $link->query(\"SELECT id FROM test WHERE id = 1\");\n        printf(\"[006] Connect allowed, query fail, [%d] %s\\n\", $link->errno, $link->error);\n        $link->close();\n    }\n    /* allow connect, fix pw */\n    $link = mysqli_init();\n    $link->options(MYSQLI_OPT_CAN_HANDLE_EXPIRED_PASSWORDS, 1);\n    if (!my_mysqli_real_connect($link, $host, 'expiretest', 'expiredpassword', $db, $port, $socket)) {\n        printf(\"[007] Cannot connect [%d] %s\\n\",\n            mysqli_connect_errno(), mysqli_connect_error());\n    } else {\n        if (!$link->query(\"SET PASSWORD='expiretest'\")) {\n            $link->query(\"SET PASSWORD=PASSWORD('expiretest')\");\n        }\n        printf(\"[008] Connect allowed, pw set, [%d] %s\\n\", $link->errno, $link->error);\n        if ($res = $link->query(\"SELECT id FROM test WHERE id = 1\"))\n            var_dump($res->fetch_assoc());\n        $link->close();\n    }\n    /* check login */\n    if (!$link = my_mysqli_connect($host, 'expiretest', \"expiretest\", $db, $port, $socket)) {\n        printf(\"[001] Cannot connect [%d] %s\\n\",\n            mysqli_connect_errno(), mysqli_connect_error());\n    } else {\n        $link->query(\"SELECT id FROM test WHERE id = 1\");\n        if ($res = $link->query(\"SELECT id FROM test WHERE id = 1\"))\n            var_dump($res->fetch_assoc());\n        $link->close();\n    }\n    print \"done!\";\n?>")).toMatchSnapshot();
  });
});
