// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // ext/mysqli/tests/013.phpt
  it("mysqli fetch mixed / mysql_query (may fail when using 4.1 library with 5.x server)", function () {
    expect(parser.parseCode("<?php\n    require_once(\"connect.inc\");\n    /*** test mysqli_connect 127.0.0.1 ***/\n    $link = my_mysqli_connect($host, $user, $passwd, $db, $port, $socket);\n    if (!mysqli_query($link, \"DROP TABLE IF EXISTS test_bind_result\"))\n        printf(\"[001] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    $rc = mysqli_query($link, \"CREATE TABLE test_bind_result(c1 tinyint, c2 smallint,\n                                                        c3 int, c4 bigint,\n                                                        c5 decimal(4,2), c6 double,\n                                                        c7 varbinary(10),\n                                                        c8 varchar(10)) ENGINE=\" . $engine);\n    if (!$rc)\n        printf(\"[002] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    if (!mysqli_query($link, \"INSERT INTO test_bind_result VALUES(120,2999,3999,54,\n                                                              2.6,58.89,\n                                                              '206','6.7')\"))\n        printf(\"[003] [%d] %s\\n\", mysqli_errno($link), mysqli_error($link));\n    $stmt = mysqli_prepare($link, \"SELECT * FROM test_bind_result\");\n    $c = array(0,0,0,0,0,0,0,0);\n    $b_res= mysqli_stmt_bind_result($stmt, $c[0], $c[1], $c[2], $c[3], $c[4], $c[5], $c[6], $c[7]);\n    mysqli_stmt_execute($stmt);\n    mysqli_stmt_fetch($stmt);\n    mysqli_stmt_fetch($stmt);\n    mysqli_stmt_close($stmt);\n    $result = mysqli_query($link, \"select * from test_bind_result\");\n    $d = mysqli_fetch_row($result);\n    mysqli_free_result($result);\n    $test = \"\";\n    for ($i=0; $i < count($c); $i++)\n        $test .= ($c[$i] == $d[$i]) ? \"1\" : \"0\";\n    if ($test == \"11111111\")\n        echo \"ok\\n\";\n    else\n        echo \"error\";\n    mysqli_query($link, \"DROP TABLE IF EXISTS test_bind_result\");\n    mysqli_close($link);\n    print \"done!\";\n?>")).toMatchSnapshot();
  });
});
