// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // tests/classes/array_access_002.phpt
  it("ZE2 ArrayAccess::offsetSet without return", function () {
    expect(parser.parseCode("<?php\nclass ObjectOne implements ArrayAccess {\n    public $a = array('1st', 1, 2=>'3rd', '4th'=>4);\n    function offsetExists($index): bool {\n        echo __METHOD__ . \"($index)\\n\";\n        return array_key_exists($index, $this->a);\n    }\n    function offsetGet($index): mixed {\n        echo __METHOD__ . \"($index)\\n\";\n        return $this->a[$index];\n    }\n    function offsetSet($index, $newval): void {\n        echo __METHOD__ . \"($index,$newval)\\n\";\n        $this->a[$index] = $newval;\n    }\n    function offsetUnset($index): void {\n        echo __METHOD__ . \"($index)\\n\";\n        unset($this->a[$index]);\n    }\n}\n$obj = new ObjectOne;\nvar_dump($obj->a);\necho \"===EMPTY===\\n\";\nvar_dump(empty($obj[0]));\nvar_dump(empty($obj[1]));\nvar_dump(empty($obj[2]));\nvar_dump(empty($obj['4th']));\nvar_dump(empty($obj['5th']));\nvar_dump(empty($obj[6]));\necho \"===isset===\\n\";\nvar_dump(isset($obj[0]));\nvar_dump(isset($obj[1]));\nvar_dump(isset($obj[2]));\nvar_dump(isset($obj['4th']));\nvar_dump(isset($obj['5th']));\nvar_dump(isset($obj[6]));\necho \"===offsetGet===\\n\";\nvar_dump($obj[0]);\nvar_dump($obj[1]);\nvar_dump($obj[2]);\nvar_dump($obj['4th']);\nvar_dump($obj['5th']);\nvar_dump($obj[6]);\necho \"===offsetSet===\\n\";\necho \"WRITE 1\\n\";\n$obj[1] = 'Changed 1';\nvar_dump($obj[1]);\necho \"WRITE 2\\n\";\n$obj['4th'] = 'Changed 4th';\nvar_dump($obj['4th']);\necho \"WRITE 3\\n\";\n$obj['5th'] = 'Added 5th';\nvar_dump($obj['5th']);\necho \"WRITE 4\\n\";\n$obj[6] = 'Added 6';\nvar_dump($obj[6]);\nvar_dump($obj[0]);\nvar_dump($obj[2]);\n$x = $obj[6] = 'changed 6';\nvar_dump($obj[6]);\nvar_dump($x);\necho \"===unset===\\n\";\nvar_dump($obj->a);\nunset($obj[2]);\nunset($obj['4th']);\nunset($obj[7]);\nunset($obj['8th']);\nvar_dump($obj->a);\n?>")).toMatchSnapshot();
  });
});
