// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // tests/basic/precision.phpt
  it("precision setting test", function () {
    expect(parser.parseCode("<?php\n$v = array(123456789.012345678901234567890, 10/3, 987e100, 10.0000001);\necho \"INI\".PHP_EOL;\nini_set('precision', -1);\nini_set('serialize_precision', -1);\necho ini_get('precision'), PHP_EOL;\necho ini_get('serialize_precision'), PHP_EOL;\necho \"OUTPUTS\".PHP_EOL;\necho join(' ', $v).PHP_EOL;\nvar_dump(serialize($v));\nvar_export($v);echo PHP_EOL;\necho \"INI\".PHP_EOL;\nini_set('precision', 0);\nini_set('serialize_precision', 0);\necho ini_get('precision'), PHP_EOL;\necho ini_get('serialize_precision'), PHP_EOL;\necho \"OUTPUTS\".PHP_EOL;\necho join(' ', $v).PHP_EOL;\nvar_dump(serialize($v));\nvar_export($v);echo PHP_EOL;\necho \"INI\".PHP_EOL;\nini_set('precision', 9);\nini_set('serialize_precision', 9);\necho ini_get('precision'), PHP_EOL;\necho ini_get('serialize_precision'), PHP_EOL;\necho \"OUTPUTS\".PHP_EOL;\necho join(' ', $v).PHP_EOL;\nvar_dump(serialize($v));\nvar_export($v);echo PHP_EOL;\necho \"INI\".PHP_EOL;\nini_set('precision', 14);\nini_set('serialize_precision', 14);\necho ini_get('precision'), PHP_EOL;\necho ini_get('serialize_precision'), PHP_EOL;\necho \"OUTPUTS\".PHP_EOL;\necho join(' ', $v).PHP_EOL;\nvar_dump(serialize($v));\nvar_export($v);echo PHP_EOL;\necho \"INI\".PHP_EOL;\nini_set('precision', 17);\nini_set('serialize_precision', 17);\necho ini_get('precision'), PHP_EOL;\necho ini_get('serialize_precision'), PHP_EOL;\necho \"OUTPUTS\".PHP_EOL;\necho join(' ', $v).PHP_EOL;\nvar_dump(serialize($v));\nvar_export($v);echo PHP_EOL;\necho \"INI\".PHP_EOL;\nini_set('precision', 25);\nini_set('serialize_precision', 25);\necho ini_get('precision'), PHP_EOL;\necho ini_get('serialize_precision'), PHP_EOL;\necho \"OUTPUTS\".PHP_EOL;\necho join(' ', $v).PHP_EOL;\nvar_dump(serialize($v));\nvar_export($v);echo PHP_EOL;\necho \"INI\".PHP_EOL;\nini_set('precision', 100);\nini_set('serialize_precision', 100);\necho ini_get('precision'), PHP_EOL;\necho ini_get('serialize_precision'), PHP_EOL;\necho \"OUTPUTS\".PHP_EOL;\necho join(' ', $v).PHP_EOL;\nvar_dump(serialize($v));\nvar_export($v);echo PHP_EOL;\n?>")).toMatchSnapshot();
  });
});
