// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // tests/lang/foreachLoopObjects.003.phpt
  it("Foreach loop tests - modifying the object during the loop.", function () {
    expect(parser.parseCode("<?php\nclass C {\n    public $a = \"Original a\";\n    public $b = \"Original b\";\n    public $c = \"Original c\";\n    protected $d = \"Original d\";\n    private $e = \"Original e\";\n}\necho \"\\nDirectly changing object values.\\n\";\n$obj = new C;\nforeach ($obj as $k=>$v) {\n    $obj->$k=\"changed.$k\";\n    var_dump($v);\n}\nvar_dump($obj);\necho \"\\nModifying the foreach \\$value.\\n\";\n$obj = new C;\nforeach ($obj as $k=>$v) {\n    $v=\"changed.$k\";\n}\nvar_dump($obj);\necho \"\\nModifying the foreach &\\$value.\\n\";\n$obj = new C;\nforeach ($obj as $k=>&$v) {\n    $v=\"changed.$k\";\n}\nvar_dump($obj);\necho \"\\nAdding properties to an an object.\\n\";\n$obj = new C;\n$counter=0;\nforeach ($obj as $v) {\n    $newPropName = \"new$counter\";\n    $obj->$newPropName = \"Added property $counter\";\n    if ($counter++>10) {\n        echo \"Loop detected\\n\";\n        break;\n    }\n    var_dump($v);\n}\nvar_dump($obj);\necho \"\\nAdding properties to an an object, using &\\$value.\\n\";\n$obj = new C;\n$counter=0;\nforeach ($obj as &$v) {\n    $newPropName = \"new$counter\";\n    $obj->$newPropName = \"Added property $counter\";\n    if ($counter++>10) {\n        echo \"Loop detected\\n\";\n        break;\n    }\n    var_dump($v);\n}\nvar_dump($obj);\necho \"\\nRemoving properties from an object.\\n\";\n$obj = new C;\nforeach ($obj as $v) {\n    unset($obj->a);\n    unset($obj->b);\n    unset($obj->c);\n    var_dump($v);\n}\nvar_dump($obj);\necho \"\\nRemoving properties from an object, using &\\$value.\\n\";\n$obj = new C;\nforeach ($obj as &$v) {\n    unset($obj->a);\n    unset($obj->b);\n    unset($obj->c);\n    var_dump($v);\n}\nvar_dump($obj);\n?>")).toMatchSnapshot();
  });
});
