// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // Zend/tests/002.phpt
  it("func_get_arg() tests", function () {
    expect(parser.parseCode("<?php\nfunction test1() {\n    try {\n        var_dump(func_get_arg(-10));\n    } catch (\\ValueError $e) {\n        echo $e->getMessage() . \\PHP_EOL;\n    }\n    try {\n        var_dump(func_get_arg(0));\n    } catch (\\Error $e) {\n        echo $e->getMessage() . \\PHP_EOL;\n    }\n    try {\n        var_dump(func_get_arg(1));\n    } catch (\\Error $e) {\n        echo $e->getMessage() . \\PHP_EOL;\n    }\n}\nfunction test2($a) {\n    try {\n        var_dump(func_get_arg(0));\n    } catch (\\Error $e) {\n        echo $e->getMessage() . \\PHP_EOL;\n    }\n    try {\n        var_dump(func_get_arg(1));\n    } catch (\\Error $e) {\n        echo $e->getMessage() . \\PHP_EOL;\n    }\n}\nfunction test3($a, $b) {\n    try {\n        var_dump(func_get_arg(0));\n    } catch (\\Error $e) {\n        echo $e->getMessage() . \\PHP_EOL;\n    }\n    try {\n        var_dump(func_get_arg(1));\n    } catch (\\Error $e) {\n        echo $e->getMessage() . \\PHP_EOL;\n    }\n    try {\n        var_dump(func_get_arg(2));\n    } catch (\\Error $e) {\n        echo $e->getMessage() . \\PHP_EOL;\n    }\n}\ntest1();\ntest1(10);\ntest2(1);\ntry {\n    test2();\n} catch (Throwable $e) {\n    echo \"Exception: \" . $e->getMessage() . \"\\n\";\n}\ntest3(1,2);\ncall_user_func(\"test1\");\ntry {\n    call_user_func(\"test3\", 1);\n} catch (Throwable $e) {\n    echo \"Exception: \" . $e->getMessage() . \"\\n\";\n}\ncall_user_func(\"test3\", 1, 2);\nclass test {\n    static function test1($a) {\n        try {\n            var_dump(func_get_arg(0));\n        } catch (\\Error $e) {\n            echo $e->getMessage() . \\PHP_EOL;\n        }\n        try {\n            var_dump(func_get_arg(1));\n        } catch (\\Error $e) {\n            echo $e->getMessage() . \\PHP_EOL;\n        }\n    }\n}\ntest::test1(1);\ntry {\n    var_dump(func_get_arg(1));\n} catch (\\Error $e) {\n    echo $e->getMessage() . \\PHP_EOL;\n}\necho \"Done\\n\";\n?>")).toMatchSnapshot();
  });
});
