// eslint-disable prettier/prettier
const parser = require("../main");

describe("php-src tests", function () {
  // Zend/tests/named_params/basic.phpt
  it("Basic test", function () {
    expect(parser.parseCode("<?php\nfunction test($a, $b, $c = \"c\", $d = \"d\", $e = \"e\") {\n    echo \"a=$a, b=$b, c=$c, d=$d, e=$e\\n\";\n}\nfunction test3(&$a, &$b, &$c = \"c\", &$d = \"d\", &$e = \"e\") {\n    echo \"a=$a, b=$b, c=$c, d=$d, e=$e\\n\";\n}\nfunction &id($x) {\n    return $x;\n}\n$a = \"A\"; $b = \"B\"; $c = \"C\"; $d = \"D\"; $e = \"E\";\necho \"SEND_VAL:\\n\";\ntest(\"A\", \"B\", \"C\", d: \"D\", e: \"E\");\ntest(\"A\", \"B\", \"C\", e: \"E\", d: \"D\");\ntest(e: \"E\", a: \"A\", d: \"D\", b: \"B\", c: \"C\");\ntest(\"A\", \"B\", \"C\", e: \"E\");\necho \"SEND_VAL_EX:\\n\";\ntest2(\"A\", \"B\", \"C\", d: \"D\", e: \"E\");\ntest2(\"A\", \"B\", \"C\", e: \"E\", d: \"D\");\ntest2(e: \"E\", a: \"A\", d: \"D\", b: \"B\", c: \"C\");\ntest2(\"A\", \"B\", \"C\", e: \"E\");\necho \"SEND_VAR:\\n\";\ntest($a, $b, $c, d: $d, e: $e);\ntest($a, $b, $c, e: $e, d: $d);\ntest(e: $e, a: $a, d: $d, b: $b, c: $c);\ntest(a: $a, b: $b, c: $c, e: $e);\necho \"SEND_VAR_EX:\\n\";\ntest2($a, $b, $c, d: $d, e: $e);\ntest2($a, $b, $c, e: $e, d: $d);\ntest2(e: $e, a: $a, d: $d, b: $b, c: $c);\ntest2(a: $a, b: $b, c: $c, e: $e);\necho \"SEND_VAR_NO_REF:\\n\";\ntest3(id(\"A\"), id(\"B\"), id(\"C\"), d: id(\"D\"), e: id(\"E\"));\ntest3(id(\"A\"), id(\"B\"), id(\"C\"), e: id(\"E\"), d: id(\"D\"));\ntest3(e: id(\"E\"), a: id(\"A\"), d: id(\"D\"), b: id(\"B\"), c: id(\"C\"));\ntest3(id(\"A\"), id(\"B\"), id(\"C\"), e: id(\"E\"));\necho \"SEND_VAR_NO_REF_EX:\\n\";\ntest4(id(\"A\"), id(\"B\"), id(\"C\"), d: id(\"D\"), e: id(\"E\"));\ntest4(id(\"A\"), id(\"B\"), id(\"C\"), e: id(\"E\"), d: id(\"D\"));\ntest4(e: id(\"E\"), a: id(\"A\"), d: id(\"D\"), b: id(\"B\"), c: id(\"C\"));\ntest4(id(\"A\"), id(\"B\"), id(\"C\"), e: id(\"E\"));\necho \"SEND_REF:\\n\";\ntest3($a, $b, $c, d: $d, e: $e);\ntest3($a, $b, $c, e: $e, d: $d);\ntest3(e: $e, a: $a, d: $d, b: $b, c: $c);\ntest3(a: $a, b: $b, c: $c, e: $e);\nfunction test2($a, $b, $c = \"c\", $d = \"d\", $e = \"e\") {\n    echo \"a=$a, b=$b, c=$c, d=$d, e=$e\\n\";\n}\nfunction test4(&$a, &$b, &$c = \"c\", &$d = \"d\", &$e = \"e\") {\n    echo \"a=$a, b=$b, c=$c, d=$d, e=$e\\n\";\n}\n?>")).toMatchSnapshot();
  });
});
