
<ST_IN_SCRIPTING>"__CLASS__" {
	return T_CLASS_C;
}

<ST_IN_SCRIPTING>"__TRAIT__" {
	return T_TRAIT_C;
}

<ST_IN_SCRIPTING>"__FUNCTION__" {
	return T_FUNC_C;
}

<ST_IN_SCRIPTING>"__METHOD__" {
	return T_METHOD_C;
}

<ST_IN_SCRIPTING>"__LINE__" {
	return T_LINE;
}

<ST_IN_SCRIPTING>"__FILE__" {
	return T_FILE;
}

<ST_IN_SCRIPTING>"__DIR__" {
	return T_DIR;
}

<ST_IN_SCRIPTING>"__NAMESPACE__" {
	return T_NS_C;
}